import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // `.ai` is the ogen-ai submodule; the rest are the per-tool skill trees
  // ai-sync copies out of it. Vendored config, regenerated by
  // `python .ai/bin/ai-sync` — not this repo's code to lint.
  { ignores: ["dist", ".ai", ".agents", ".claude", ".cursor", ".github/skills"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      // eslint-plugin-react-hooks v7's "recommended" bundles a large set of
      // new rules (purity, set-state-in-effect, immutability, refs, globals,
      // static-components, …) that assume code will run through the React
      // Compiler. This app targets plain React 18 without the compiler, and
      // those rules flag long-standing, correct patterns throughout the
      // codebase (setState synchronously in an effect, reading a ref during
      // render, etc.) as errors. Keep only the two rules that matter without
      // the compiler — rules-of-hooks (correctness) and exhaustive-deps (deps
      // hygiene) — same effective rule set as v5's recommended config.
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
    },
  },
  {
    // Vercel Serverless Functions run under Node.js, not the browser.
    files: ["api/**/*.ts"],
    languageOptions: {
      globals: globals.node,
    },
  },
);
