// Round 7 of additional Reading, Listening and Speaking content.
// Weighted to A1-B1. Merged into the data set by the generator.

const R = (title, text, glossary, questions) => ({ title, text, glossary, questions });
const g = (word, partOfSpeech, definition, example, translation) => ({ word, partOfSpeech, definition, example, translation });
const q = (question, options, correctIndex, explanation) => ({ question, options, correctIndex, explanation });
const L = (transcript, questions) => ({ transcript, questions });

export const MORE_READINGS7 = {
  A1: [
    R("Feeding the Cat (מאכיל את החתול)",
      "We have a grey cat called Misha. Every morning I give her food and clean water. She rubs my leg and says 'meow'. After she eats, she sleeps in the sun by the window.",
      [g("grey", "adjective", "אפור", "A grey cat.", "אפור"), g("feed", "verb", "להאכיל", "I feed the cat.", "להאכיל"), g("clean", "adjective", "נקי", "Clean water.", "נקי")],
      [q("What is the cat's name?", ["Misha", "Max", "Lily", "Spot"], 0, "'a grey cat called Misha'."), q("Where does the cat sleep?", ["On the bed", "In the sun by the window", "On the floor", "Outside"], 1, "'she sleeps in the sun by the window'.")]),
    R("A Day at the Beach (יום בים)",
      "On Sunday we went to the beach. The sun was hot and the water was cool. I made a big castle in the sand. My dad and I swam together. Then we ate ice cream.",
      [g("beach", "noun", "חוף ים", "Go to the beach.", "חוף ים"), g("sand", "noun", "חול", "Castle in the sand.", "חול"), g("swam", "verb", "שחה", "We swam.", "שחה")],
      [q("What day did they go?", ["Saturday", "Sunday", "Monday", "Friday"], 1, "'On Sunday we went to the beach'."), q("What did the child make in the sand?", ["A hole", "A big castle", "A boat", "A road"], 1, "'I made a big castle in the sand'.")]),
    R("My Grandpa's Garden (הגינה של סבא)",
      "My grandpa has a small garden. He grows tomatoes, carrots and flowers. I help him water the plants. The tomatoes are red and sweet. We eat them at dinner.",
      [g("grow", "verb", "לגדל, לצמוח", "He grows tomatoes.", "לגדל/לצמוח"), g("water", "verb", "להשקות", "Water the plants.", "להשקות"), g("sweet", "adjective", "מתוק", "Sweet tomatoes.", "מתוק")],
      [q("What does Grandpa grow?", ["Only flowers", "Tomatoes, carrots and flowers", "Trees", "Grass"], 1, "'He grows tomatoes, carrots and flowers'."), q("How are the tomatoes?", ["Green and sour", "Red and sweet", "Small", "Hard"], 1, "'The tomatoes are red and sweet'.")]),
    R("The Birthday Cake (עוגת יום ההולדת)",
      "Today is my sister's birthday. Mum and I make a chocolate cake. We put seven candles on it. My sister is very happy. She blows out the candles and we all sing.",
      [g("candle", "noun", "נר", "Seven candles.", "נר"), g("blow out", "phrase", "לכבות בנשיפה", "Blow out the candles.", "לכבות בנשיפה"), g("happy", "adjective", "שמח", "Very happy.", "שמח")],
      [q("How many candles are on the cake?", ["Five", "Six", "Seven", "Eight"], 2, "'We put seven candles on it'."), q("What does the sister do?", ["Cut the cake", "Blow out the candles", "Cry", "Run"], 1, "'She blows out the candles'.")]),
    R("Waiting for the Rain to Stop (מחכים שהגשם ייפסק)",
      "We wanted to play outside, but it started to rain. So we sat by the window and watched the drops. My brother counted the cars in the street. When the sun came back, we ran out to play.",
      [g("rain", "verb", "לרדת גשם", "It started to rain.", "לרדת גשם"), g("drops", "noun", "טיפות", "Watch the drops.", "טיפות"), g("count", "verb", "לספור", "Count the cars.", "לספור")],
      [q("Why did they stay inside?", ["It was cold", "It started to rain", "It was late", "They were tired"], 1, "'it started to rain'."), q("What did the brother do?", ["Slept", "Counted the cars", "Read", "Sang"], 1, "'My brother counted the cars'.")]),
  ],
  A2: [
    R("The First Day at Work (היום הראשון בעבודה)",
      "Yesterday was my first day at the café. I was nervous and dropped a cup in the morning. But my manager was patient and showed me everything twice. By the afternoon, I felt much more confident.",
      [g("nervous", "adjective", "לחוץ, עצבני", "I was nervous.", "לחוץ"), g("manager", "noun", "מנהל", "My manager helped.", "מנהל"), g("confident", "adjective", "בטוח בעצמו", "I felt confident.", "בטוח בעצמו")],
      [q("Where did the writer start working?", ["A shop", "A café", "An office", "A school"], 1, "'my first day at the café'."), q("How was the manager?", ["Angry", "Patient", "Busy", "Late"], 1, "'my manager was patient'.")]),
    R("A Camping Trip (טיול קמפינג)",
      "Last weekend we went camping in the forest. We put up our tent near a small river. At night it was very dark, and we cooked dinner over a fire. I have never seen so many stars.",
      [g("camping", "noun", "מחנאות, קמפינג", "Go camping.", "מחנאות/קמפינג"), g("tent", "noun", "אוהל", "Put up a tent.", "אוהל"), g("forest", "noun", "יער", "In the forest.", "יער")],
      [q("Where did they camp?", ["On a beach", "In the forest", "In a field", "In the mountains"], 1, "'camping in the forest'."), q("How did they cook dinner?", ["On a stove", "Over a fire", "In a microwave", "They didn't"], 1, "'we cooked dinner over a fire'.")]),
    R("My Noisy Neighbours (השכנים הרועשים שלי)",
      "The people upstairs play loud music late at night. For weeks I could not sleep well. Finally I went up and spoke to them politely. They were friendly and turned the music down. A small talk solved a big problem.",
      [g("loud", "adjective", "רועש, בקול רם", "Loud music.", "רועש"), g("politely", "adverb", "בנימוס", "Spoke politely.", "בנימוס"), g("solve", "verb", "לפתור", "Solve a problem.", "לפתור")],
      [q("What was the problem?", ["A leak", "Loud music at night", "A smell", "No heating"], 1, "'play loud music late at night'."), q("How did the writer fix it?", ["Called the police", "Spoke to them politely", "Moved out", "Wrote a note"], 1, "'I went up and spoke to them politely'.")]),
    R("My First Time Cooking Alone (הפעם הראשונה שבישלתי לבד)",
      "When I moved out, I could only make toast. I decided to learn one new dish each week. At first I burned the rice and oversalted the soup. Now my friends actually ask me to cook for them.",
      [g("dish", "noun", "מנה, תבשיל", "A new dish.", "מנה/תבשיל"), g("burn", "verb", "לשרוף", "I burned the rice.", "לשרוף"), g("actually", "adverb", "באמת, למעשה", "They actually like it.", "באמת/למעשה")],
      [q("What could the writer make at first?", ["Soup", "Only toast", "Cakes", "Nothing"], 1, "'I could only make toast'."), q("What was the plan?", ["Eat out", "Learn one new dish each week", "Buy a book", "Take a class"], 1, "'learn one new dish each week'.")]),
    R("The Train Was Late (הרכבת איחרה)",
      "I had an important meeting, but the train was forty minutes late. I called ahead to explain and stayed calm. When I finally arrived, my colleagues were understanding. Sometimes things go wrong, and that is all right.",
      [g("important", "adjective", "חשוב", "An important meeting.", "חשוב"), g("explain", "verb", "להסביר", "I called to explain.", "להסביר"), g("understanding", "adjective", "מבין, סלחני", "They were understanding.", "מבין/סלחני")],
      [q("How late was the train?", ["Ten minutes", "Forty minutes", "An hour", "Two hours"], 1, "'forty minutes late'."), q("What did the writer do?", ["Got angry", "Called ahead and stayed calm", "Went home", "Gave up"], 1, "'I called ahead to explain and stayed calm'.")]),
  ],
  B1: [
    R("Saying No Without Guilt (לומר 'לא' בלי אשמה)",
      "For years I said yes to everything, afraid of disappointing people. I ended up exhausted and resentful. Learning to say a kind but firm 'no' changed my life. Protecting my time, I discovered, is not selfish — it is necessary.",
      [g("guilt", "noun", "אשמה", "Without guilt.", "אשמה"), g("resentful", "adjective", "ממורמר, מלא טינה", "Tired and resentful.", "ממורמר"), g("selfish", "adjective", "אנוכי, אגואיסט", "It is not selfish.", "אנוכי")],
      [q("Why did the writer used to say yes?", ["For money", "Afraid of disappointing people", "For fun", "By habit"], 1, "'afraid of disappointing people'."), q("What did the writer discover about protecting time?", ["It is selfish", "It is necessary", "It is rude", "It is easy"], 1, "'is not selfish — it is necessary'.")]),
    R("The Joy of a Long Walk (השמחה שבהליכה ארוכה)",
      "Whenever a problem feels stuck in my head, I go for a long walk. Something about the steady rhythm loosens my thoughts. Halfway through, the answer often arrives quietly, as if it had been waiting for me to slow down and listen.",
      [g("stuck", "adjective", "תקוע", "A stuck problem.", "תקוע"), g("rhythm", "noun", "קצב", "A steady rhythm.", "קצב"), g("loosen", "verb", "לשחרר, להרפות", "Loosen my thoughts.", "לשחרר/להרפות")],
      [q("What does the writer do when a problem feels stuck?", ["Sleeps", "Goes for a long walk", "Asks a friend", "Reads"], 1, "'I go for a long walk'."), q("When does the answer often arrive?", ["At the start", "Halfway through", "At home", "Never"], 1, "'Halfway through, the answer often arrives'.")]),
    R("Why I Keep a Journal (למה אני כותב יומן)",
      "Each night I write a few lines about my day. I am not a great writer, and no one else will read it. Yet putting the day into words helps me notice patterns, let go of small worries, and remember what I might otherwise forget.",
      [g("journal", "noun", "יומן", "Keep a journal.", "יומן"), g("pattern", "noun", "דפוס, תבנית", "Notice patterns.", "דפוס/תבנית"), g("worry", "noun", "דאגה", "Let go of worries.", "דאגה")],
      [q("How often does the writer write?", ["Each night", "Once a week", "Rarely", "Each morning"], 0, "'Each night I write a few lines'."), q("Name one benefit mentioned.", ["Fame", "Noticing patterns", "Money", "New friends"], 1, "'helps me notice patterns'.")]),
    R("Fixing Things Myself (מתקן דברים בעצמי)",
      "I used to throw away anything that broke. Then a friend showed me how to watch a short video and try a repair first. I have since fixed a lamp, a chair and a zip. Each small success makes me feel surprisingly capable.",
      [g("throw away", "phrase", "לזרוק לאשפה", "Throw it away.", "לזרוק"), g("repair", "noun", "תיקון", "Try a repair.", "תיקון"), g("capable", "adjective", "מסוגל, יכול", "I feel capable.", "מסוגל")],
      [q("What did the writer used to do with broken things?", ["Fix them", "Throw them away", "Sell them", "Store them"], 1, "'I used to throw away anything that broke'."), q("How does fixing things make the writer feel?", ["Tired", "Surprisingly capable", "Bored", "Angry"], 1, "'makes me feel surprisingly capable'.")]),
    R("The Quiet Morning Routine (שגרת הבוקר השקטה)",
      "I wake an hour before everyone else. In that quiet time I drink tea, stretch, and plan the day on paper. It is not much, but starting calmly seems to set the tone for everything that follows.",
      [g("routine", "noun", "שגרה", "A morning routine.", "שגרה"), g("stretch", "verb", "להתמתח", "I stretch.", "להתמתח"), g("set the tone", "phrase", "לתת את הטון, לקבוע אווירה", "It sets the tone.", "לתת את הטון")],
      [q("When does the writer wake up?", ["At noon", "An hour before everyone else", "Late", "At sunrise only"], 1, "'I wake an hour before everyone else'."), q("What does the calm start do?", ["Wastes time", "Sets the tone for the day", "Makes them tired", "Nothing"], 1, "'set the tone for everything that follows'.")]),
  ],
  B2: [
    R("The Cost of Always Being Reachable (מחיר הזמינות התמידית)",
      "A phone in every pocket means work can find us at any hour, and increasingly it does. The expectation of an instant reply erodes the boundary between labour and rest. Reclaiming the right to be unreachable may be the quiet luxury of our age.",
      [g("reachable", "adjective", "ניתן להשגה, זמין", "Always reachable.", "זמין"), g("erode", "verb", "לשחוק", "It erodes the boundary.", "לשחוק"), g("reclaim", "verb", "להשיב, לתבוע בחזרה", "Reclaim the right.", "להשיב/לתבוע בחזרה")],
      [q("What does instant-reply expectation erode?", ["Our skills", "The boundary between labour and rest", "Our phones", "Our income"], 1, "'erodes the boundary between labour and rest'."), q("What is called 'the quiet luxury of our age'?", ["A new phone", "The right to be unreachable", "More work", "Faster replies"], 1, "'the right to be unreachable'.")]),
    R("On Changing Your Mind (על שינוי דעה)",
      "We treat changing one's mind as weakness, a kind of defeat. In truth it is often the opposite: evidence of a mind still in contact with reality. The person who has held the same views for thirty years has not necessarily been right — only stubborn.",
      [g("defeat", "noun", "תבוסה, הפסד", "A kind of defeat.", "תבוסה/הפסד"), g("evidence", "noun", "ראיה, עדות", "Evidence of growth.", "ראיה/עדות"), g("stubborn", "adjective", "עקשן", "Only stubborn.", "עקשן")],
      [q("How do we usually treat changing one's mind?", ["As wisdom", "As weakness", "As normal", "As rare"], 1, "'as weakness, a kind of defeat'."), q("What might thirty years of the same views show?", ["Being right", "Being stubborn", "Being wise", "Being open"], 1, "'not necessarily been right — only stubborn'.")]),
    R("The Value of Boredom (ערכו של השעמום)",
      "We now fill every idle moment with a screen, terrified of the smallest gap. Yet boredom is the soil in which curiosity and imagination grow. A mind never left to wander rarely surprises itself — and it is in those wandering moments that ideas tend to appear.",
      [g("idle", "adjective", "פנוי, בטל", "An idle moment.", "פנוי/בטל"), g("soil", "noun", "אדמה, קרקע", "Fertile soil.", "אדמה/קרקע"), g("wander", "verb", "לשוטט, לנדוד", "Let the mind wander.", "לשוטט/לנדוד")],
      [q("What do we now fill every idle moment with?", ["Work", "A screen", "Talk", "Sleep"], 1, "'fill every idle moment with a screen'."), q("Boredom is called the soil for what?", ["Stress", "Curiosity and imagination", "Sleep", "Anger"], 1, "'the soil in which curiosity and imagination grow'.")]),
  ],
  C1: [
    R("The Streetlight Effect (אפקט פנס הרחוב)",
      "A man searches for his lost keys under a streetlight, not because he dropped them there, but because that is where the light is. Researchers and organisations do the same, studying what is easy to measure rather than what matters. The brightest data is not always the most relevant.",
      [g("streetlight", "noun", "פנס רחוב", "Under the streetlight.", "פנס רחוב"), g("relevant", "adjective", "רלוונטי, נוגע לעניין", "The most relevant.", "רלוונטי"), g("measure", "verb", "למדוד", "Easy to measure.", "למדוד")],
      [q("Why does the man search under the streetlight?", ["He dropped them there", "That is where the light is", "It is safer", "It is closer"], 1, "'because that is where the light is'."), q("What is the lesson for researchers?", ["Measure everything", "The brightest data isn't always the most relevant", "Avoid data", "Work faster"], 1, "'The brightest data is not always the most relevant'.")]),
    R("Path Dependence (תלות במסלול)",
      "The keyboard layout on your phone was designed to slow down mechanical typewriters, a problem solved a century ago. We keep it not because it is best, but because everyone already knows it. History, once set in motion, narrows the choices that feel possible today.",
      [g("layout", "noun", "פריסה, מתווה", "The keyboard layout.", "פריסה/מתווה"), g("mechanical", "adjective", "מכני", "Mechanical typewriters.", "מכני"), g("narrow", "verb", "לצמצם, להצר", "It narrows the choices.", "לצמצם/להצר")],
      [q("Why was the keyboard layout originally designed that way?", ["For speed", "To slow down mechanical typewriters", "For comfort", "By accident"], 1, "'designed to slow down mechanical typewriters'."), q("Why do we keep it?", ["It is best", "Everyone already knows it", "It is new", "It is cheap"], 1, "'because everyone already knows it'.")]),
    R("The Overton Window (חלון אוברטון)",
      "At any moment, only a narrow band of ideas counts as 'reasonable' to discuss in public; the rest are unthinkable or taboo. This window is not fixed. What sounds radical in one decade can become common sense in the next — which is why patient, unfashionable arguments sometimes matter most.",
      [g("taboo", "noun", "טאבו, אסור לדיון", "A social taboo.", "טאבו"), g("radical", "adjective", "קיצוני, רדיקלי", "It sounds radical.", "קיצוני/רדיקלי"), g("unfashionable", "adjective", "לא אופנתי, לא מקובל", "Unfashionable arguments.", "לא אופנתי/לא מקובל")],
      [q("What does the 'window' contain?", ["All ideas", "Ideas that count as reasonable to discuss", "Only laws", "Old ideas"], 1, "'only a narrow band of ideas counts as reasonable'."), q("What can happen to a radical idea over time?", ["It vanishes", "It can become common sense", "It stays taboo", "It is banned"], 1, "'can become common sense in the next'.")]),
  ],
  C2: [
    R("The Tyranny of the Explicit (עריצות המפורש)",
      "Modern institutions prize what can be written down — the rule, the metric, the documented procedure. Yet much of what makes an expert excellent is tacit: a feel, a judgement, a knowing-in-the-hands that resists articulation. In demanding that all knowledge be made explicit, we risk discarding the very part that cannot be.",
      [g("explicit", "adjective", "מפורש, גלוי", "Made explicit.", "מפורש/גלוי"), g("tacit", "adjective", "סמוי, מובלע", "Tacit knowledge.", "סמוי/מובלע"), g("articulation", "noun", "ניסוח, הבעה במילים", "It resists articulation.", "ניסוח")],
      [q("What do modern institutions prize?", ["Intuition", "What can be written down", "Silence", "Tradition"], 1, "'prize what can be written down'."), q("What is the risk of demanding all knowledge be explicit?", ["Slower work", "Discarding the part that cannot be made explicit", "Higher cost", "Confusion"], 1, "'discarding the very part that cannot be'.")]),
    R("Second-Order Consequences (השלכות מסדר שני)",
      "Every intervention solves a visible problem and quietly creates invisible ones. Pesticides kill the pest and the bird that ate it; a subsidy lowers a price and reshapes a whole industry. Wisdom lies less in the first move than in asking, patiently, 'and then what?'",
      [g("intervention", "noun", "התערבות", "Every intervention.", "התערבות"), g("subsidy", "noun", "סבסוד, תמיכה כספית", "A government subsidy.", "סבסוד"), g("reshape", "verb", "לעצב מחדש", "Reshape an industry.", "לעצב מחדש")],
      [q("What does every intervention do, per the text?", ["Only solves problems", "Solves one problem and creates invisible ones", "Always fails", "Costs nothing"], 1, "'solves a visible problem and quietly creates invisible ones'."), q("Where does wisdom lie?", ["In the first move", "In asking 'and then what?'", "In speed", "In confidence"], 1, "'asking, patiently, and then what?'.")]),
    R("The Map's Convenient Silences (השתיקות הנוחות של המפה)",
      "A map is useful precisely because it leaves things out; a chart showing every pebble would be useless. But the omissions are choices, and choices carry interests. To read any account critically is to ask not only what it shows, but what it has quietly declined to mention, and whom that silence serves.",
      [g("omission", "noun", "השמטה, חיסרון", "The omissions matter.", "השמטה"), g("interest", "noun", "אינטרס, עניין", "Choices carry interests.", "אינטרס/עניין"), g("critically", "adverb", "בביקורתיות", "Read critically.", "בביקורתיות")],
      [q("Why is a map useful, per the text?", ["It shows everything", "Precisely because it leaves things out", "It is colourful", "It is small"], 1, "'useful precisely because it leaves things out'."), q("What should a critical reader also ask?", ["Only what it shows", "What it declined to mention, and whom the silence serves", "Who drew it", "How long it took"], 1, "'what it has quietly declined to mention, and whom that silence serves'.")]),
  ],
};

export const MORE_LISTENINGS7 = {
  A1: [
    L("Hello, children! Today we will paint. Please put on your aprons and take one brush each. We will paint a big yellow sun.",
      [q("What will the children do today?", ["Read", "Paint", "Sing", "Run"], 1, "'Today we will paint'."), q("What will they paint?", ["A tree", "A big yellow sun", "A house", "A cat"], 1, "'paint a big yellow sun'.")]),
    L("This is the bus to the city. The next stop is the hospital. The bus is warm, so please sit down and hold on.",
      [q("Where is the bus going?", ["The beach", "The city", "The school", "The park"], 1, "'the bus to the city'."), q("What is the next stop?", ["The market", "The hospital", "The station", "The bank"], 1, "'The next stop is the hospital'.")]),
    L("Good morning! Look outside — it is sunny today. Let's go to the park and play with the ball. Don't forget your hat!",
      [q("What is the weather like?", ["Rainy", "Sunny", "Snowy", "Windy"], 1, "'it is sunny today'."), q("What should you not forget?", ["A coat", "Your hat", "An umbrella", "A book"], 1, "'Don't forget your hat'.")]),
    L("Dinner is ready! Tonight we have rice and chicken. Please wash your hands and come to the table.",
      [q("What is for dinner?", ["Soup", "Rice and chicken", "Pizza", "Fish"], 1, "'we have rice and chicken'."), q("What should you do first?", ["Sit down", "Wash your hands", "Pour water", "Set the table"], 1, "'wash your hands and come to the table'.")]),
    L("Welcome to the toy shop. The teddy bears are on the left. The balls and games are at the back. Please ask me if you need help.",
      [q("Where are the teddy bears?", ["At the back", "On the left", "On the right", "By the door"], 1, "'The teddy bears are on the left'."), q("What is at the back?", ["Bears", "Balls and games", "Books", "Hats"], 1, "'The balls and games are at the back'.")]),
  ],
  A2: [
    L("Good evening. This is a reminder that the swimming pool closes early tomorrow, at four o'clock, for cleaning. Normal hours return on Friday.",
      [q("Why does the pool close early?", ["A holiday", "For cleaning", "No staff", "An event"], 1, "'closes early tomorrow... for cleaning'."), q("When do normal hours return?", ["Thursday", "Friday", "Saturday", "Monday"], 1, "'Normal hours return on Friday'.")]),
    L("Hi, it's Dana. I'm running about twenty minutes late because of traffic. Please order me a coffee and I'll be there soon. Sorry!",
      [q("Why is Dana late?", ["She overslept", "Because of traffic", "She is lost", "She is sick"], 1, "'late because of traffic'."), q("What does Dana ask for?", ["A taxi", "A coffee ordered", "A table", "Directions"], 1, "'Please order me a coffee'.")]),
    L("Attention passengers: the flight to Rome is now boarding at gate twelve. Please have your passport and boarding pass ready.",
      [q("Where is the flight going?", ["Paris", "Rome", "London", "Madrid"], 1, "'the flight to Rome'."), q("What gate is boarding?", ["Gate two", "Gate twelve", "Gate twenty", "Gate ten"], 1, "'boarding at gate twelve'.")]),
    L("Thank you for calling the dentist. We are closed now. Our hours are nine to five, Monday to Friday. For emergencies, press one.",
      [q("What are the opening hours?", ["Nine to five, Mon–Fri", "All day", "Weekends only", "Eight to four"], 0, "'nine to five, Monday to Friday'."), q("What should you do in an emergency?", ["Wait", "Press one", "Call back", "Email"], 1, "'For emergencies, press one'.")]),
    L("Welcome to the gym. New members get a free class this week. The changing rooms are downstairs, and towels are by the door.",
      [q("What do new members get?", ["A free drink", "A free class this week", "A discount", "A locker"], 1, "'a free class this week'."), q("Where are the towels?", ["Downstairs", "By the door", "Upstairs", "In the office"], 1, "'towels are by the door'.")]),
  ],
  B1: [
    L("Good morning, team. Quick update: the client moved the deadline to next Wednesday. Let's focus on the main report first and leave the extra charts for later if there's time.",
      [q("What changed?", ["The budget", "The deadline moved to next Wednesday", "The team", "The client"], 1, "'the client moved the deadline to next Wednesday'."), q("What should the team focus on first?", ["The charts", "The main report", "A meeting", "Emails"], 1, "'focus on the main report first'.")]),
    L("This is a community announcement. The local park will host a free outdoor film on Saturday evening. Bring a blanket and something to sit on. The film starts at sunset.",
      [q("What is happening Saturday evening?", ["A market", "A free outdoor film", "A concert", "A race"], 1, "'a free outdoor film on Saturday evening'."), q("What should people bring?", ["Food only", "A blanket and something to sit on", "Tickets", "Nothing"], 1, "'Bring a blanket and something to sit on'.")]),
    L("Hello, this is the clinic. Your test results are normal, so there is nothing to worry about. The doctor suggests a check-up again in one year. Take care.",
      [q("What were the test results?", ["Bad", "Normal", "Unclear", "Lost"], 1, "'Your test results are normal'."), q("When is the next check-up suggested?", ["In a month", "In one year", "Never", "In a week"], 1, "'a check-up again in one year'.")]),
    L("Attention shoppers: we are now offering a repair service for clothes. Instead of throwing away a torn item, bring it to the counter and we'll mend it for a small fee.",
      [q("What new service is offered?", ["Free delivery", "A repair service for clothes", "Gift wrapping", "Cleaning"], 1, "'a repair service for clothes'."), q("What can you do with a torn item?", ["Throw it away", "Bring it to be mended", "Return it", "Donate it"], 1, "'bring it to the counter and we'll mend it'.")]),
    L("Welcome to the night class. Please switch your phones to silent. If you miss a session, the notes are shared online the next morning, so don't worry.",
      [q("What should students do with phones?", ["Turn them off", "Switch to silent", "Leave them outside", "Nothing"], 1, "'switch your phones to silent'."), q("What happens if you miss a session?", ["You fail", "Notes are shared online next morning", "You repeat it", "Nothing"], 1, "'the notes are shared online the next morning'.")]),
  ],
  B2: [
    L("A thought on decision-making: when a choice is easily reversible, decide fast and learn by doing. Save your slow, careful deliberation for the rare decisions that are genuinely hard to undo.",
      [q("How should you treat easily reversible choices?", ["Deliberate slowly", "Decide fast and learn by doing", "Avoid them", "Delegate them"], 1, "'decide fast and learn by doing'."), q("What deserves slow deliberation?", ["Every choice", "Decisions that are hard to undo", "Small choices", "None"], 1, "'the rare decisions that are genuinely hard to undo'.")]),
    L("Linguists remind us that no language is more 'logical' than another; each simply carves up experience differently. What feels natural is mostly what we grew up with, not some universal standard of clarity.",
      [q("What do linguists say about languages?", ["Some are more logical", "None is more logical than another", "English is best", "Older is better"], 1, "'no language is more logical than another'."), q("What feels 'natural', per the talk?", ["A universal standard", "Mostly what we grew up with", "The simplest one", "The newest one"], 1, "'mostly what we grew up with'.")]),
    L("A note on negotiation: the person who can most comfortably walk away usually holds the power. So before any important talk, quietly develop your alternatives — they are your real source of leverage.",
      [q("Who usually holds the power?", ["The loudest", "The one who can walk away", "The richest", "The first to speak"], 1, "'the person who can most comfortably walk away'."), q("What is your real source of leverage?", ["Charm", "Your alternatives", "Speed", "Volume"], 1, "'develop your alternatives — they are your real source of leverage'.")]),
  ],
  C1: [
    L("Consider the sunk cost fallacy. Money or effort already spent is gone, yet we keep investing in failing projects to 'not waste' it. The rational question is never what we've spent, but what the next dollar or hour will actually buy.",
      [q("What is the sunk cost fallacy?", ["Saving too much", "Investing more to avoid 'wasting' what's already spent", "Spending fast", "Ignoring costs"], 1, "'we keep investing in failing projects to not waste it'."), q("What is the rational question?", ["What we've spent", "What the next dollar or hour will buy", "Who is to blame", "How long it took"], 1, "'what the next dollar or hour will actually buy'.")]),
    L("There's a concept called the availability heuristic. We judge how likely something is by how easily examples come to mind. Vivid, recent events therefore feel far more probable than they really are — which is why news can distort our sense of risk.",
      [q("What is the availability heuristic?", ["Counting carefully", "Judging likelihood by how easily examples come to mind", "Ignoring data", "Asking experts"], 1, "'how easily examples come to mind'."), q("Why can the news distort our sense of risk?", ["It lies", "Vivid, recent events feel more probable", "It is slow", "It is boring"], 1, "'Vivid, recent events therefore feel far more probable'.")]),
    L("Philosophers speak of 'the ship of Theseus'. If you replace every plank of a ship over time, is it still the same ship? The puzzle isn't really about boats; it asks what makes anything — a person, a company — the same thing across change.",
      [q("What is the puzzle of the ship of Theseus?", ["How to build ships", "Whether a fully replaced ship is the same ship", "How fast ships sail", "Who owns the ship"], 1, "'is it still the same ship?'."), q("What is the puzzle really about?", ["Boats", "What makes anything the same across change", "Wood", "Sailing"], 1, "'what makes anything... the same thing across change'.")]),
  ],
  C2: [
    L("Note the difference between a reason and a rationalisation. The first comes before the conclusion and shapes it; the second arrives afterward to defend a conclusion already reached. The unsettling part is how rarely we can tell, from the inside, which one we are doing.",
      [q("What is a rationalisation, per the talk?", ["A careful reason", "A defence that arrives after the conclusion", "A measurement", "A question"], 1, "'arrives afterward to defend a conclusion already reached'."), q("What is the 'unsettling part'?", ["It is rare", "We rarely can tell which one we're doing", "It is illegal", "It is obvious"], 1, "'how rarely we can tell, from the inside, which one we are doing'.")]),
    L("There's an idea called the 'narrative fallacy'. We crave stories with neat causes and effects, so we impose them on a world that is largely noisy and accidental. The danger is that a satisfying story can feel like understanding while delivering none.",
      [q("What does the narrative fallacy describe?", ["Telling lies", "Imposing neat cause-and-effect stories on a noisy world", "Forgetting stories", "Avoiding stories"], 1, "'we impose them on a world that is largely noisy and accidental'."), q("What is the danger?", ["Boredom", "A satisfying story can feel like understanding while delivering none", "Too much data", "Slow thinking"], 1, "'can feel like understanding while delivering none'.")]),
    L("Beware the seduction of a single cause. Complex outcomes — a recession, an illness, a war — usually emerge from many interacting factors, yet our minds reach for one villain or hero. Monocausal explanations are satisfying precisely because they are too simple to be true.",
      [q("How do complex outcomes usually emerge?", ["From one cause", "From many interacting factors", "By chance only", "From villains"], 1, "'emerge from many interacting factors'."), q("Why are monocausal explanations satisfying?", ["They are correct", "They are too simple to be true", "They are detailed", "They are rare"], 1, "'satisfying precisely because they are too simple to be true'.")]),
  ],
};

export const MORE_SPEAKING7 = {
  A1: [
    { text: "I am hungry. Can we eat?", translation: "אני רעב. אפשר לאכול?" },
    { text: "My favourite colour is blue.", translation: "הצבע האהוב עליי הוא כחול." },
    { text: "Please open the window.", translation: "בבקשה תפתח את החלון." },
  ],
  A2: [
    { text: "I'm sorry I'm late; the bus was slow.", translation: "סליחה שאיחרתי; האוטובוס היה איטי." },
    { text: "Can you show me how to do this?", translation: "תוכל להראות לי איך עושים את זה?" },
    { text: "I'd like to learn something new this year.", translation: "הייתי רוצה ללמוד משהו חדש השנה." },
  ],
  B1: [
    { text: "I've decided to take on fewer commitments.", translation: "החלטתי לקחת על עצמי פחות מחויבויות." },
    { text: "Do you mind if we talk about this later?", translation: "אכפת לך אם נדבר על זה מאוחר יותר?" },
    { text: "Let me think it over and get back to you.", translation: "תן לי לחשוב על זה ואחזור אליך." },
  ],
  B2: [
    { text: "If it's reversible, I'd rather just try it and learn.", translation: "אם זה הפיך, אני מעדיף פשוט לנסות וללמוד." },
    { text: "I want to be reachable less and present more.", translation: "אני רוצה להיות זמין פחות ונוכח יותר." },
    { text: "Let's pressure-test that assumption before we commit.", translation: "בוא נבחן את ההנחה הזו לעומק לפני שנתחייב." },
  ],
  C1: [
    { text: "I'm wary of measuring what's easy instead of what matters.", translation: "אני חושש ממדידה של מה שקל במקום של מה שחשוב." },
    { text: "We may be stuck with this simply out of habit.", translation: "ייתכן שאנחנו תקועים עם זה פשוט מתוך הרגל." },
    { text: "Before we act, let's ask 'and then what?'", translation: "לפני שנפעל, בוא נשאל 'ואז מה?'" },
  ],
  C2: [
    { text: "I'd want to separate a reason from a rationalisation here.", translation: "הייתי רוצה להפריד כאן בין סיבה לבין רציונליזציה." },
    { text: "Let's resist the comfort of a single, tidy cause.", translation: "בוא לא ניפול לנוחות של סיבה אחת ומסודרת." },
    { text: "What is this account quietly choosing not to mention?", translation: "מה התיאור הזה בוחר בשקט שלא להזכיר?" },
  ],
};
