// Additional Reading and Listening items per level, merged into the pools by
// the generator. Kept separate so the base passage bank stays stable and we can
// keep adding rounds.

const R = (title, text, glossary, questions) => ({ title, text, glossary, questions });
const g = (word, partOfSpeech, definition, example, translation) => ({ word, partOfSpeech, definition, example, translation });
const q = (question, options, correctIndex, explanation) => ({ question, options, correctIndex, explanation });
const L = (transcript, questions) => ({ transcript, questions });

export const MORE_READINGS = {
  A1: [
    R("At the Park (בפארק)",
      "On Saturday we go to the park. My father plays football with me. My mother sits and reads a book. Later we eat sandwiches on the grass. I like Saturdays.",
      [g("park", "noun", "שטח ירוק ציבורי", "We play in the park.", "פארק"), g("football", "noun", "משחק כדור פופולרי", "I like football.", "כדורגל"), g("grass", "noun", "הצמח הירוק שעל הקרקע", "Sit on the grass.", "דשא")],
      [q("What does the father do at the park?", ["Reads", "Plays football", "Sleeps", "Cooks"], 1, "'plays football with me'."), q("Where do they eat?", ["At home", "On the grass", "In a café", "On a bench"], 1, "'eat sandwiches on the grass'.")]),
    R("My School Bag (התיק שלי)",
      "This is my school bag. It is blue. Inside I have three books, two pens and an apple. The bag is heavy, but I carry it every day.",
      [g("bag", "noun", "תיק לנשיאת דברים", "A school bag.", "תיק"), g("heavy", "adjective", "כבד, קשה לשאת", "A heavy box.", "כבד"), g("carry", "verb", "לשאת משהו", "I carry the bag.", "לשאת")],
      [q("What colour is the bag?", ["Red", "Blue", "Green", "Black"], 1, "'It is blue'."), q("What fruit is in the bag?", ["A banana", "An apple", "An orange", "A pear"], 1, "'an apple'.")]),
    R("Rainy Day (יום גשום)",
      "Today it is raining. I cannot play outside. So I stay at home and draw pictures. My sister helps me. We have fun together, even on a rainy day.",
      [g("raining", "verb", "כשיורד גשם", "It is raining.", "יורד גשם"), g("outside", "adverb", "מחוץ לבית", "Play outside.", "בחוץ"), g("draw", "verb", "ליצור תמונה בעיפרון", "I draw a cat.", "לצייר")],
      [q("Why can't the child play outside?", ["It is night", "It is raining", "It is cold", "It is late"], 1, "'it is raining'."), q("What do they do at home?", ["Sleep", "Draw pictures", "Cook", "Read"], 1, "'draw pictures'.")]),
  ],
  A2: [
    R("The Job Interview (ראיון העבודה)",
      "Last week I had my first job interview. I was nervous, so I arrived early and wore my best clothes. The manager asked me about my experience. I tried to stay calm and answer clearly. Two days later, they offered me the job!",
      [g("interview", "noun", "פגישה לבדיקת מועמד לעבודה", "A job interview.", "ראיון"), g("calm", "adjective", "רגוע, לא לחוץ", "Stay calm.", "רגוע"), g("offer", "verb", "להציע משהו למישהו", "They offered a job.", "להציע")],
      [q("How did the writer feel before the interview?", ["Bored", "Nervous", "Angry", "Sleepy"], 1, "'I was nervous'."), q("What happened two days later?", ["They said no", "They offered the job", "Another interview", "Nothing"], 1, "'they offered me the job'.")]),
    R("Cooking Together (מבשלים ביחד)",
      "My friends and I meet every month to cook a meal together. Each person brings one ingredient. We do not always know what we will make! Last time we made a big vegetable soup, and it was delicious.",
      [g("meal", "noun", "ארוחה", "A healthy meal.", "ארוחה"), g("ingredient", "noun", "מרכיב במתכון", "Add one ingredient.", "מרכיב"), g("delicious", "adjective", "טעים מאוד", "Delicious food.", "טעים מאוד")],
      [q("How often do they meet?", ["Every week", "Every month", "Every day", "Every year"], 1, "'every month'."), q("What did they make last time?", ["A cake", "Vegetable soup", "Pizza", "Salad"], 1, "'a big vegetable soup'.")]),
    R("Lost in the City (אבודים בעיר)",
      "When we visited a new city, we got lost. The map on my phone stopped working. We asked a friendly woman for directions. She walked with us part of the way. Thanks to her, we found our hotel.",
      [g("lost", "adjective", "לא יודע איפה אתה", "We got lost.", "אבוד"), g("directions", "noun", "הוראות איך להגיע", "Ask for directions.", "הוראות הגעה"), g("hotel", "noun", "מקום לינה בתשלום", "A nice hotel.", "מלון")],
      [q("Why did they get lost?", ["No map", "The phone map stopped working", "It was dark", "No money"], 1, "'The map on my phone stopped working'."), q("Who helped them?", ["A police officer", "A friendly woman", "A taxi driver", "A child"], 1, "'a friendly woman'.")]),
  ],
  B1: [
    R("The Power of Habit (כוחו של ההרגל)",
      "Most of what we do each day is not a real decision but a habit. We brush our teeth, check our phones, and make coffee almost without thinking. This can work for us or against us. The trick is to design good habits so that the easy choice becomes the right one.",
      [g("habit", "noun", "הרגל — פעולה אוטומטית", "A good habit.", "הרגל"), g("decision", "noun", "החלטה מודעת", "A big decision.", "החלטה"), g("design", "verb", "לתכנן בכוונה", "Design your day.", "לתכנן")],
      [q("What is most daily behaviour, according to the text?", ["Careful decisions", "Habit", "Luck", "Planning"], 1, "'not a real decision but a habit'."), q("What is 'the trick'?", ["Work harder", "Design good habits", "Avoid coffee", "Think more"], 1, "'design good habits'.")]),
    R("Volunteering (התנדבות)",
      "After I retired, my days felt empty. A friend suggested I volunteer at the local library. At first I only helped sort books, but soon I was reading stories to children. I gained far more than I gave: purpose, friends, and a reason to get up in the morning.",
      [g("retired", "verb", "פרש מעבודה בגיל מבוגר", "She retired last year.", "פרש לגמלאות"), g("volunteer", "verb", "לעבוד בהתנדבות, ללא שכר", "I volunteer weekly.", "להתנדב"), g("purpose", "noun", "מטרה ותחושת משמעות", "A sense of purpose.", "מטרה/משמעות")],
      [q("Why did the writer start volunteering?", ["For money", "Their days felt empty", "It was required", "To learn"], 1, "'my days felt empty'."), q("What did the writer gain?", ["Only money", "Purpose and friends", "A new job", "Nothing"], 1, "'purpose, friends, and a reason'.")]),
    R("Slow Travel (תיירות איטית)",
      "Instead of visiting ten cities in a week, more travellers now choose to stay in one place. They rent a flat, shop at the local market, and learn a few words of the language. They see fewer sights, but they understand the place far better. Sometimes less really is more.",
      [g("travellers", "noun", "אנשים שמטיילים", "Many travellers.", "מטיילים"), g("rent", "verb", "לשכור תמורת תשלום", "Rent a flat.", "לשכור"), g("sights", "noun", "אתרים שכדאי לראות", "Famous sights.", "אתרי תיירות")],
      [q("What do 'slow' travellers do?", ["Visit many cities", "Stay in one place", "Travel fast", "Avoid markets"], 1, "'stay in one place'."), q("What is the trade-off?", ["More money", "Fewer sights but deeper understanding", "Less rest", "More flights"], 1, "'fewer sights, but... understand... better'.")]),
  ],
  B2: [
    R("The Attention Economy (כלכלת הקשב)",
      "Many free apps are not really free; we pay with our attention. Their business depends on keeping us scrolling, because more time means more advertising revenue. Recognising this does not mean we must delete everything, but it does mean using these tools deliberately rather than letting them use us.",
      [g("revenue", "noun", "הכנסה כספית", "Advertising revenue.", "הכנסה"), g("deliberately", "adverb", "במכוון, בכוונה תחילה", "Choose deliberately.", "במכוון"), g("recognise", "verb", "להכיר בעובדה או להבין", "Recognise the danger.", "להכיר ב-")],
      [q("How do 'free' apps make money?", ["Subscriptions", "Our attention and ads", "Donations", "Selling devices"], 1, "'more time means more advertising revenue'."), q("What does the writer recommend?", ["Delete everything", "Use the tools deliberately", "Pay for apps", "Ignore the issue"], 1, "'using these tools deliberately'.")]),
    R("Failure as Data (כישלון כמידע)",
      "In many successful companies, failure is not punished but studied. A failed experiment is treated as information: it rules out one path and points toward better ones. This mindset is hard to adopt because failure feels personal, yet teams that learn to separate the result from their self-worth tend to improve fastest.",
      [g("punished", "verb", "נענש על מעשה", "He was punished.", "נענש"), g("mindset", "noun", "תפיסת חשיבה, גישה", "A growth mindset.", "תפיסת חשיבה"), g("self-worth", "noun", "תחושת הערך העצמי", "Tie of self-worth.", "ערך עצמי")],
      [q("How is failure treated in these companies?", ["Punished", "Studied as information", "Ignored", "Hidden"], 1, "'treated as information'."), q("Why is the mindset hard to adopt?", ["It costs money", "Failure feels personal", "It is slow", "It is illegal"], 1, "'failure feels personal'.")]),
    R("The Myth of Multitasking (מיתוס ריבוי המשימות)",
      "We pride ourselves on multitasking, yet research suggests the brain does not truly do two demanding things at once. Instead, it switches rapidly between tasks, and each switch carries a hidden cost in time and accuracy. What feels efficient is often slower and more error-prone than simply doing one thing at a time.",
      [g("pride", "verb", "להתגאות במשהו", "We pride ourselves.", "להתגאות"), g("switches", "verb", "עובר במהירות מאחד לשני", "It switches tasks.", "מחליף/עובר"), g("error-prone", "adjective", "נוטה לטעויות", "An error-prone process.", "נוטה לטעויות")],
      [q("What does the brain actually do when 'multitasking'?", ["Two things at once", "Switches rapidly between tasks", "Stops", "Slows down only"], 1, "'switches rapidly between tasks'."), q("What is the hidden cost?", ["Money", "Time and accuracy", "Memory only", "Sleep"], 1, "'a hidden cost in time and accuracy'.")]),
  ],
  C1: [
    R("The Expert's Blind Spot (הנקודה העיוורת של המומחה)",
      "Expertise is double-edged. The same deep knowledge that lets a specialist diagnose a problem instantly can also blind them to solutions outside their framework. Having seen a thousand cases, they may stop truly looking at the one in front of them. Sometimes the naive question of a newcomer cuts closer to the truth than the confident answer of a veteran.",
      [g("expertise", "noun", "מומחיות, ידע מעמיק", "Years of expertise.", "מומחיות"), g("framework", "noun", "מסגרת חשיבה", "A mental framework.", "מסגרת"), g("naive", "adjective", "תמים, חסר ניסיון", "A naive question.", "תמים/נאיבי")],
      [q("Why is expertise 'double-edged'?", ["It is rare", "It can blind one to outside solutions", "It is slow", "It is cheap"], 1, "'blind them to solutions outside their framework'."), q("What can the newcomer's question do?", ["Waste time", "Cut closer to the truth", "Confuse experts", "Nothing"], 1, "'cuts closer to the truth'.")]),
    R("Manufactured Scarcity (מחסור מלאכותי)",
      "Much of what feels rare is rare by design. Limited editions, countdown timers and 'only three left' notices exploit a deep instinct: we want most what we might not be able to have. Understanding the trick does not fully disarm it, but it does buy us a moment's pause — and that pause is often where wiser decisions live.",
      [g("scarcity", "noun", "מחסור, נדירות", "Artificial scarcity.", "מחסור/נדירות"), g("exploit", "verb", "לנצל לטובת מטרה", "Exploit a weakness.", "לנצל"), g("disarm", "verb", "לנטרל, להחליש כוח", "Disarm the trick.", "לנטרל")],
      [q("According to the text, much scarcity is…", ["Natural", "Rare by design", "Random", "Illegal"], 1, "'rare by design'."), q("What does understanding the trick give us?", ["Full immunity", "A moment's pause", "More money", "Nothing"], 1, "'it does buy us a moment's pause'.")]),
    R("The Tyranny of the Urgent (עריצות הדחוף)",
      "The urgent and the important are not the same, yet the urgent almost always wins. A ringing phone demands attention now; a long-term goal waits patiently and is therefore neglected. The discipline of progress lies in protecting time for what matters before the day fills with what merely shouts loudest.",
      [g("urgent", "adjective", "דחוף, דורש פעולה מיידית", "An urgent message.", "דחוף"), g("neglected", "verb", "הוזנח, לא קיבל תשומת לב", "A neglected garden.", "הוזנח"), g("discipline", "noun", "משמעת עצמית", "It takes discipline.", "משמעת")],
      [q("What 'almost always wins'?", ["The important", "The urgent", "The easy", "The cheap"], 1, "'the urgent almost always wins'."), q("Where does the discipline of progress lie?", ["In speed", "In protecting time for what matters", "In answering calls", "In multitasking"], 1, "'protecting time for what matters'.")]),
  ],
  C2: [
    R("The Aesthetics of Imperfection (אסתטיקה של אי-שלמות)",
      "Where Western design has often chased flawless symmetry, other traditions have prized the crack, the asymmetry, the trace of the maker's hand. There is a quiet wisdom in this: perfection, once attained, has nowhere left to go, while imperfection keeps a thing alive, unfinished, open to the eye that returns to it. The flaw is not a failure of beauty but a condition of it.",
      [g("symmetry", "noun", "סימטריה, איזון מושלם", "Perfect symmetry.", "סימטריה"), g("prized", "verb", "העריך מאוד, החשיב", "Highly prized.", "הוקיר/העריך"), g("flaw", "noun", "פגם, ליקוי", "A small flaw.", "פגם")],
      [q("What have some traditions prized?", ["Flawless symmetry", "The crack and asymmetry", "Speed", "Sameness"], 1, "'prized the crack, the asymmetry'."), q("How does the writer reframe the flaw?", ["A failure of beauty", "A condition of beauty", "An accident", "A cost"], 1, "'not a failure of beauty but a condition of it'.")]),
    R("The Map of Knowledge (מפת הידע)",
      "The more one learns, the larger the perimeter of one's ignorance becomes. Each answer opens several new questions, so that the educated mind is, paradoxically, more aware of what it does not know than the novice who imagines the field to be small. Genuine expertise is thus accompanied not by certainty but by a refined sense of doubt.",
      [g("perimeter", "noun", "היקף, גבול חיצוני", "The perimeter grows.", "היקף/גבול"), g("paradoxically", "adverb", "באופן פרדוקסלי, סותר לכאורה", "Paradoxically true.", "באופן פרדוקסלי"), g("novice", "noun", "מתחיל, חסר ניסיון", "A complete novice.", "מתחיל/טירון")],
      [q("What grows as one learns more?", ["Certainty", "The perimeter of ignorance", "Speed", "Income"], 1, "'the larger the perimeter of one's ignorance'."), q("What accompanies genuine expertise?", ["Certainty", "A refined sense of doubt", "Arrogance", "Silence"], 1, "'not by certainty but by a refined sense of doubt'.")]),
    R("Against Efficiency (נגד היעילות)",
      "Efficiency is the unquestioned virtue of our age, but applied without limit it quietly devours the things that resist measurement. A perfectly efficient conversation is an interrogation; a perfectly efficient friendship is a transaction. Some of life's deepest goods — wandering, lingering, play — are precisely the ones that an efficiency mindset cannot help but classify as waste.",
      [g("virtue", "noun", "מעלה, תכונה טובה", "A great virtue.", "מעלה"), g("devours", "verb", "בולע, מכלה", "It devours time.", "בולע/מכלה"), g("lingering", "noun", "השתהות, שהייה ללא חיפזון", "Lingering over coffee.", "השתהות")],
      [q("What does limitless efficiency 'devour'?", ["Money", "Things that resist measurement", "Machines", "Time only"], 1, "'devours the things that resist measurement'."), q("How would an efficiency mindset classify wandering and play?", ["As virtues", "As waste", "As work", "As profit"], 1, "'cannot help but classify as waste'.")]),
  ],
};

export const MORE_LISTENINGS = {
  A1: [
    L("Hello, this is the library. The book you want is ready. Please come before five today.",
      [q("Who is calling?", ["A shop", "The library", "A school", "A friend"], 1, "'this is the library'."), q("By when should you come?", ["Before three", "Before five", "Before seven", "Tomorrow"], 1, "'before five today'.")]),
    L("Good morning, class. Today we will read a story and then draw a picture. Please open your books.",
      [q("What will the class do first?", ["Draw", "Read a story", "Sing", "Play"], 1, "'read a story and then draw'."), q("Who is speaking?", ["A doctor", "A teacher", "A driver", "A cook"], 1, "מדבר ל-'class' ומבקש לפתוח ספרים.")]),
    L("Hi Mum, I'm at the bus stop. The bus is late. I will be home at six. See you soon!",
      [q("Where is the speaker?", ["At home", "At the bus stop", "At school", "At work"], 1, "'I'm at the bus stop'."), q("When will they be home?", ["At five", "At six", "At seven", "At eight"], 1, "'home at six'.")]),
  ],
  A2: [
    L("Thank you for calling Sunny Gym. We are open from six in the morning to ten at night. The first class is free for new members.",
      [q("When does the gym open?", ["Six a.m.", "Eight a.m.", "Ten a.m.", "Noon"], 0, "'six in the morning'."), q("What is free for new members?", ["A towel", "The first class", "Parking", "A drink"], 1, "'first class is free'.")]),
    L("Hi, it's the cinema. Your booking for tonight is confirmed: two tickets for the eight o'clock film. Please arrive ten minutes early.",
      [q("How many tickets were booked?", ["One", "Two", "Three", "Four"], 1, "'two tickets'."), q("When should they arrive?", ["On time", "Ten minutes early", "Late", "An hour early"], 1, "'ten minutes early'.")]),
    L("Attention shoppers. The supermarket will close in fifteen minutes. Please bring your items to the checkout now. Thank you.",
      [q("How long until the supermarket closes?", ["Five minutes", "Ten minutes", "Fifteen minutes", "An hour"], 2, "'close in fifteen minutes'."), q("What should shoppers do?", ["Keep shopping", "Go to the checkout", "Leave bags", "Wait"], 1, "'bring your items to the checkout'.")]),
  ],
  B1: [
    L("Hello, this is Dr. Levi's office calling to confirm your appointment tomorrow at half past nine. If you need to cancel, please call us before the end of the day.",
      [q("What time is the appointment?", ["9:00", "9:15", "9:30", "10:00"], 2, "'half past nine'."), q("By when should you call to cancel?", ["Before the end of the day", "Tomorrow morning", "In an hour", "Next week"], 0, "'before the end of the day'.")]),
    L("Hi, it's Sam from the team. The meeting has moved to Thursday because two people are away on Wednesday. Same time, same room. Let me know if that's a problem.",
      [q("Why did the meeting move?", ["The room was busy", "Two people are away", "A holiday", "Bad weather"], 1, "'two people are away on Wednesday'."), q("What stays the same?", ["The day", "The time and room", "Nothing", "The topic"], 1, "'Same time, same room'.")]),
    L("Welcome to the museum's audio guide. This tour takes about forty minutes. You can pause at any time, and headphones are available at the front desk if you need them.",
      [q("How long is the tour?", ["Twenty minutes", "Forty minutes", "An hour", "Two hours"], 1, "'about forty minutes'."), q("Where can you get headphones?", ["The shop", "The front desk", "The café", "Online"], 1, "'available at the front desk'.")]),
  ],
  B2: [
    L("Good afternoon. Due to essential maintenance, the lifts in the building will be out of service this Sunday. We apologise for the inconvenience and recommend using the stairs.",
      [q("Why will the lifts be out of service?", ["A power cut", "Essential maintenance", "An accident", "A holiday"], 1, "'Due to essential maintenance'."), q("What is recommended?", ["Stay home", "Use the stairs", "Wait", "Use another building"], 1, "'recommend using the stairs'.")]),
    L("Thanks for joining the webinar. A quick note: your microphones are muted by default. If you have a question, please type it in the chat, and we'll address questions in the last fifteen minutes.",
      [q("How should participants ask questions?", ["Unmute and speak", "Type in the chat", "Email later", "Raise a hand"], 1, "'type it in the chat'."), q("When will questions be addressed?", ["At the start", "In the last fifteen minutes", "Never", "Anytime"], 1, "'in the last fifteen minutes'.")]),
    L("This is a customer-service update. We've noticed longer wait times this week due to high demand. If your issue isn't urgent, our online help centre can often resolve it faster than the phone line.",
      [q("Why are wait times longer?", ["A strike", "High demand", "A holiday", "Fewer staff only"], 1, "'due to high demand'."), q("What is suggested for non-urgent issues?", ["Call back later", "Use the online help centre", "Visit in person", "Wait on hold"], 1, "'online help centre can... resolve it faster'.")]),
  ],
  C1: [
    L("Before we begin, a brief caveat: the figures I'm about to present are provisional. They're based on the first three weeks of data, so treat any trend you see as suggestive rather than conclusive.",
      [q("What does the speaker say about the figures?", ["They are final", "They are provisional", "They are wrong", "They are old"], 1, "'the figures... are provisional'."), q("How should trends be treated?", ["As conclusive", "As suggestive rather than conclusive", "As errors", "As proven"], 1, "'suggestive rather than conclusive'.")]),
    L("I want to push back gently on the previous point. It's not that the strategy failed, but that we never defined what success would look like — and without that, we can't really say whether it worked at all.",
      [q("What is the speaker's main argument?", ["The strategy clearly failed", "Success was never defined", "The strategy succeeded", "Data is missing"], 1, "'we never defined what success would look like'."), q("What follows from that, per the speaker?", ["We can't judge if it worked", "It definitely worked", "We should stop", "Nothing"], 0, "'we can't really say whether it worked'.")]),
    L("The renovation is behind schedule, and I won't pretend otherwise. That said, the delay buys us a chance to fix a design flaw we'd otherwise have lived with for years, so I'm inclined to see it as a blessing in disguise.",
      [q("What is the status of the renovation?", ["Ahead of schedule", "Behind schedule", "Finished", "Cancelled"], 1, "'behind schedule'."), q("How does the speaker view the delay?", ["A disaster", "A blessing in disguise", "Meaningless", "A lie"], 1, "'a blessing in disguise'.")]),
  ],
  C2: [
    L("Let me complicate the picture slightly. The policy did reduce costs, yes, but it did so by shifting them onto households rather than eliminating them — which is less a saving than an act of accounting.",
      [q("How did the policy reduce costs?", ["By eliminating them", "By shifting them onto households", "By raising taxes", "By cutting staff"], 1, "'shifting them onto households'."), q("How does the speaker characterise this?", ["A real saving", "An act of accounting", "A failure", "A success"], 1, "'less a saving than an act of accounting'.")]),
    L("I'd resist the temptation to call this a turning point. Turning points are visible only in retrospect; at the time, they look indistinguishable from the thousand other moments that lead nowhere.",
      [q("What does the speaker resist calling this?", ["A mistake", "A turning point", "A success", "An ending"], 1, "'resist the temptation to call this a turning point'."), q("When are turning points visible, per the speaker?", ["Immediately", "Only in retrospect", "Never", "In advance"], 1, "'visible only in retrospect'.")]),
    L("The translation is faithful, almost to a fault. In rendering every word precisely, it loses the music of the original — reminding us that fidelity and beauty are not always the same allegiance.",
      [q("What is the criticism of the translation?", ["It is inaccurate", "It loses the music of the original", "It is too free", "It is incomplete"], 1, "'it loses the music of the original'."), q("What distinction does the speaker draw?", ["Speed vs cost", "Fidelity vs beauty", "Old vs new", "Long vs short"], 1, "'fidelity and beauty are not always the same'.")]),
  ],
};
