// Round 2 of additional Reading, Listening and Speaking content, merged into
// the pools by the generator alongside passages.mjs / passages-extra.mjs.

const R = (title, text, glossary, questions) => ({ title, text, glossary, questions });
const g = (word, partOfSpeech, definition, example, translation) => ({ word, partOfSpeech, definition, example, translation });
const q = (question, options, correctIndex, explanation) => ({ question, options, correctIndex, explanation });
const L = (transcript, questions) => ({ transcript, questions });

export const MORE_READINGS2 = {
  A1: [
    R("The Birthday (יום ההולדת)",
      "Today is my birthday. I am ten years old. My friends come to my house. We eat cake and play games. I am very happy.",
      [g("birthday", "noun", "יום ההולדת של אדם", "Happy birthday!", "יום הולדת"), g("cake", "noun", "עוגה מתוקה", "A chocolate cake.", "עוגה"), g("happy", "adjective", "שמח", "I am happy.", "שמח")],
      [q("How old is the writer?", ["Eight", "Nine", "Ten", "Eleven"], 2, "'I am ten years old'."), q("What do they eat?", ["Bread", "Cake", "Fruit", "Soup"], 1, "'We eat cake'.")]),
    R("My Favourite Food (האוכל האהוב עליי)",
      "My favourite food is pizza. I eat it on Friday with my family. We make it at home. I put cheese and tomato on top. It is delicious!",
      [g("favourite", "adjective", "האהוב ביותר", "My favourite song.", "אהוב/מועדף"), g("cheese", "noun", "מאכל מחלב", "I like cheese.", "גבינה"), g("top", "noun", "החלק העליון", "On top.", "למעלה/חלק עליון")],
      [q("What is the writer's favourite food?", ["Pasta", "Pizza", "Rice", "Soup"], 1, "'My favourite food is pizza'."), q("When do they eat it?", ["Monday", "Friday", "Sunday", "Every day"], 1, "'on Friday'.")]),
    R("Going to the Zoo (ביקור בגן החיות)",
      "On Sunday we go to the zoo. I see lions, monkeys and a big elephant. The monkeys are funny. My little brother likes the birds. We have a great day.",
      [g("zoo", "noun", "מקום עם חיות לצפייה", "We go to the zoo.", "גן חיות"), g("elephant", "noun", "חיה גדולה מאוד", "A grey elephant.", "פיל"), g("funny", "adjective", "מצחיק", "A funny story.", "מצחיק")],
      [q("What animal does the brother like?", ["Lions", "Monkeys", "Birds", "Elephants"], 2, "'my little brother likes the birds'."), q("Which animal is described as big?", ["The monkey", "The elephant", "The bird", "The lion"], 1, "'a big elephant'.")]),
  ],
  A2: [
    R("A New Language (שפה חדשה)",
      "Last year I started to learn Spanish. At first it was hard to remember the words. Now I practise a little every day with an app. I can already understand simple sentences, and that makes me proud.",
      [g("practise", "verb", "להתאמן שוב ושוב", "I practise daily.", "להתאמן"), g("simple", "adjective", "פשוט, לא מסובך", "A simple sentence.", "פשוט"), g("proud", "adjective", "גאה בהישג", "I'm proud of you.", "גאה")],
      [q("What language is the writer learning?", ["French", "Spanish", "Italian", "German"], 1, "'started to learn Spanish'."), q("How does the writer practise now?", ["With a teacher", "With an app every day", "At school", "Not at all"], 1, "'with an app... every day'.")]),
    R("The Broken Phone (הטלפון השבור)",
      "Yesterday I dropped my phone and the screen broke. I took it to a shop near my office. The man said he could fix it in one hour. It was not cheap, but now it works again.",
      [g("dropped", "verb", "הפיל בטעות", "I dropped the cup.", "הפיל"), g("screen", "noun", "מסך המכשיר", "A cracked screen.", "מסך"), g("fix", "verb", "לתקן", "Fix the phone.", "לתקן")],
      [q("What happened to the phone?", ["It was lost", "The screen broke", "It was stolen", "It got wet"], 1, "'the screen broke'."), q("How long did the repair take?", ["One hour", "One day", "One week", "Ten minutes"], 0, "'fix it in one hour'.")]),
    R("Saving for a Trip (חיסכון לטיול)",
      "My sister and I want to travel to Italy next summer. Every month we save a little money. We don't buy things we don't need. It is not easy, but the idea of seeing Rome keeps us going.",
      [g("save", "verb", "לחסוך כסף", "Save for a car.", "לחסוך"), g("need", "verb", "להזדקק למשהו", "I need help.", "להזדקק/לצרוך"), g("idea", "noun", "רעיון", "A good idea.", "רעיון")],
      [q("Where do they want to travel?", ["Spain", "Italy", "France", "Greece"], 1, "'travel to Italy'."), q("How do they save money?", ["They work more", "They don't buy things they don't need", "They borrow", "They sell things"], 1, "'don't buy things we don't need'.")]),
  ],
  B1: [
    R("The Quiet Carriage (קרון השקט)",
      "On my morning train there is a 'quiet carriage' where phone calls are not allowed. At first I thought it was silly, but now I look forward to it. For twenty minutes, no one is shouting into a phone, and I can actually think. Small rules can protect something valuable.",
      [g("carriage", "noun", "קרון ברכבת", "The first carriage.", "קרון"), g("allowed", "verb", "מותר", "Photos are allowed.", "מותר"), g("valuable", "adjective", "בעל ערך", "Valuable time.", "בעל ערך")],
      [q("What is not allowed in the quiet carriage?", ["Eating", "Phone calls", "Reading", "Sitting"], 1, "'phone calls are not allowed'."), q("How does the writer feel about it now?", ["It's silly", "Looks forward to it", "Hates it", "Doesn't care"], 1, "'now I look forward to it'.")]),
    R("Learning From a Coach (ללמוד ממאמן)",
      "When I started running, I thought I just needed to run more. A coach showed me I was wrong: rest days, good shoes and slow runs mattered as much as hard effort. Sometimes an outside eye sees what we are too close to notice.",
      [g("coach", "noun", "מאמן", "A running coach.", "מאמן"), g("effort", "noun", "מאמץ", "It took effort.", "מאמץ"), g("notice", "verb", "להבחין", "I didn't notice.", "להבחין")],
      [q("What did the writer first believe?", ["Rest matters", "Just run more", "Buy shoes", "Hire a coach"], 1, "'I just needed to run more'."), q("What lesson does the text give?", ["Run alone", "An outside eye can help", "Avoid coaches", "Run fast only"], 1, "'an outside eye sees what we... notice'.")]),
    R("The Repair Café (בית הקפה לתיקונים)",
      "In my town there is a 'repair café' where volunteers help you fix broken things for free. Last month they helped me mend a lamp I almost threw away. Beyond saving money, it felt good to keep something useful instead of buying new.",
      [g("volunteers", "noun", "מתנדבים", "Kind volunteers.", "מתנדבים"), g("mend", "verb", "לתקן", "Mend the shirt.", "לתקן"), g("useful", "adjective", "שימושי", "A useful tool.", "שימושי")],
      [q("What does the repair café do?", ["Sells lamps", "Helps fix broken things for free", "Serves coffee only", "Buys old items"], 1, "'help you fix broken things for free'."), q("Why did it 'feel good'?", ["Saved money only", "Kept something useful instead of buying new", "Met friends", "Got a free lamp"], 1, "'keep something useful instead of buying new'.")]),
  ],
  B2: [
    R("The Cost of Free (המחיר של חינם)",
      "A 'free' trial that quietly turns into a paid subscription relies on one thing: that we forget to cancel. Companies know our intentions are weak and our calendars are full. The lesson isn't cynicism but a small habit — set a reminder the moment you sign up, before the convenience makes you forget.",
      [g("subscription", "noun", "מנוי בתשלום", "Cancel the subscription.", "מנוי"), g("intentions", "noun", "כוונות", "Good intentions.", "כוונות"), g("cynicism", "noun", "ציניות", "Avoid cynicism.", "ציניות")],
      [q("What do 'free' trials rely on?", ["Good products", "That we forget to cancel", "Advertising", "Low prices"], 1, "'that we forget to cancel'."), q("What habit does the writer suggest?", ["Never sign up", "Set a reminder when you sign up", "Pay upfront", "Avoid all apps"], 1, "'set a reminder the moment you sign up'.")]),
    R("Open-Plan Offices (משרדים פתוחים)",
      "Open-plan offices were sold as a way to boost collaboration. In practice, studies suggest they often do the opposite: people put on headphones, send more messages, and talk face-to-face less. Removing walls, it turns out, can build invisible ones.",
      [g("collaboration", "noun", "שיתוף פעולה", "Team collaboration.", "שיתוף פעולה"), g("practice", "noun", "מעשה בפועל (לעומת תאוריה)", "In practice.", "מעשה בפועל"), g("invisible", "adjective", "בלתי נראה", "Invisible walls.", "בלתי נראה")],
      [q("How were open-plan offices 'sold'?", ["To save money", "To boost collaboration", "To look modern", "To fit more people"], 1, "'a way to boost collaboration'."), q("What do studies suggest happens?", ["More talking", "People interact face-to-face less", "More walls", "Better focus"], 1, "'talk face-to-face less'.")]),
    R("The Expert and the Crowd (המומחה וההמון)",
      "For certain questions, the averaged guess of a large crowd can beat the lone expert — a phenomenon known as the wisdom of crowds. But it has a catch: it works only when people decide independently. Once they start copying one another, the crowd grows confident and wrong at the same time.",
      [g("averaged", "verb", "ממוצע", "The averaged result.", "ממוצע"), g("phenomenon", "noun", "תופעה", "A strange phenomenon.", "תופעה"), g("independently", "adverb", "באופן עצמאי", "Decide independently.", "באופן עצמאי")],
      [q("When can a crowd beat an expert?", ["Always", "When people decide independently", "When they copy each other", "Never"], 1, "'only when people decide independently'."), q("What happens when people copy each other?", ["Better answers", "Confident and wrong", "Faster results", "No change"], 1, "'confident and wrong at the same time'.")]),
  ],
  C1: [
    R("The Tyranny of the Quantified Self (עריצות העצמי הנמדד)",
      "Step counters and sleep trackers promise self-knowledge, but they can subtly rewrite our goals. We start walking not to feel well but to close a ring; we judge a night's sleep by a score rather than how rested we feel. The measure, designed to serve the goal, quietly becomes the goal.",
      [g("subtly", "adverb", "בעדינות, באופן בלתי מורגש", "Subtly changed.", "בעדינות"), g("rewrite", "verb", "לכתוב מחדש, לשנות", "Rewrite the rules.", "לכתוב מחדש"), g("rested", "adjective", "נח, רענן", "I feel rested.", "נח/רענן")],
      [q("What can trackers 'subtly rewrite'?", ["Our data", "Our goals", "Our sleep", "Our steps"], 1, "'subtly rewrite our goals'."), q("What is the central irony?", ["Trackers fail", "The measure becomes the goal", "Walking is bad", "Sleep can't be scored"], 1, "'the measure... quietly becomes the goal'.")]),
    R("On Second Languages (על שפות זרות)",
      "Speaking a second language is sometimes said to give you a second personality. The truth is gentler but no less strange: a new language offers a new set of defaults — of politeness, of humour, of distance — and in adopting them, we discover that parts of who we are were never fixed, only habitual.",
      [g("defaults", "noun", "ברירות מחדל", "Cultural defaults.", "ברירות מחדל"), g("adopting", "verb", "לאמץ", "Adopting a habit.", "לאמץ"), g("habitual", "adjective", "הרגלי, מתוך הרגל", "A habitual gesture.", "הרגלי")],
      [q("What does a new language offer, per the text?", ["A second personality", "A new set of defaults", "Better memory", "Nothing"], 1, "'a new set of defaults'."), q("What do we discover about ourselves?", ["We can't change", "Parts of us were habitual, not fixed", "Language is useless", "Personality is fixed"], 1, "'never fixed, only habitual'.")]),
    R("The Decline of Repair (שקיעת התיקון)",
      "There was a time when a broken radio was opened, diagnosed and mended. Today many devices are sealed shut, cheaper to replace than to repair. Something is lost in this beyond landfill: the quiet competence of understanding the things we own, and the dignity of fixing rather than discarding.",
      [g("diagnosed", "verb", "אובחן, זוהתה תקלתו", "Diagnosed the fault.", "אובחן"), g("sealed", "verb", "אטום, סגור הרמטית", "A sealed box.", "אטום"), g("dignity", "noun", "כבוד, ערך", "Human dignity.", "כבוד/יוקרה")],
      [q("How were broken radios once treated?", ["Replaced", "Opened and mended", "Thrown away", "Ignored"], 1, "'opened, diagnosed and mended'."), q("What does the writer say is lost?", ["Money", "Competence and the dignity of fixing", "Time", "Radios"], 1, "'the quiet competence... and the dignity of fixing'.")]),
  ],
  C2: [
    R("The Seduction of the Counterintuitive (פיתוי הבלתי-אינטואיטיבי)",
      "There is a particular prestige attached to the counterintuitive claim — the finding that overturns common sense feels deeper, cleverer, more worth repeating. Yet common sense is often common because it is right, and an idea's surprise value is no measure of its truth. The contrarian who is reflexively contrarian is merely conventional in reverse.",
      [g("prestige", "noun", "יוקרה", "Academic prestige.", "יוקרה"), g("overturns", "verb", "הופך, מבטל", "Overturns the rule.", "הופך/מבטל"), g("contrarian", "noun", "מי שמתנגד לדעת הרוב", "A born contrarian.", "מתנגד/הולך נגד הזרם")],
      [q("What feels 'deeper', per the text?", ["Common sense", "The counterintuitive claim", "Old ideas", "Simple facts"], 1, "'the counterintuitive claim... feels deeper'."), q("What does the writer say about the reflexive contrarian?", ["They are wise", "They are conventional in reverse", "They are always right", "They are rare"], 1, "'merely conventional in reverse'.")]),
    R("Translation and Loss (תרגום ואובדן)",
      "To translate is to choose, repeatedly, what to sacrifice. A pun cannot survive intact in another tongue; a rhythm bends; a connotation evaporates. The finest translators are not those who lose nothing — that is impossible — but those who choose their losses with such care that the reader never feels the wound.",
      [g("sacrifice", "verb", "להקריב, לוותר על", "Sacrifice quality.", "להקריב"), g("connotation", "noun", "קונוטציה, משמעות לוואי", "A negative connotation.", "קונוטציה/משמעות לוואי"), g("evaporates", "verb", "מתאדה, נעלם", "Hope evaporates.", "מתאדה")],
      [q("What does translating involve, per the text?", ["Losing nothing", "Choosing what to sacrifice", "Copying exactly", "Adding meaning"], 1, "'what to sacrifice'."), q("What marks the finest translators?", ["They lose nothing", "They choose their losses with care", "They translate fast", "They avoid puns"], 1, "'choose their losses with such care'.")]),
    R("The Comfort of Pessimism (נחמת הפסימיות)",
      "Pessimism wears the costume of wisdom. To predict disaster is to risk nothing: if it comes, you were right; if it doesn't, you were merely prudent. Optimism, by contrast, is a wager that can be lost in public. Perhaps that is why gloom so often passes for depth, while hope is mistaken for naivety.",
      [g("costume", "noun", "תחפושת, מסווה", "A clever costume.", "תחפושת/מסווה"), g("prudent", "adjective", "זהיר ונבון", "A prudent choice.", "זהיר/נבון"), g("wager", "noun", "הימור", "A risky wager.", "הימור")],
      [q("Why is predicting disaster 'risk-free'?", ["It's always right", "Right if it comes, prudent if not", "No one listens", "It's optimistic"], 1, "'if it comes, you were right; if it doesn't... prudent'."), q("What is hope often mistaken for?", ["Wisdom", "Naivety", "Depth", "Strength"], 1, "'hope is mistaken for naivety'.")]),
  ],
};

export const MORE_LISTENINGS2 = {
  A1: [
    L("Hi, I'm Anna. This is my dog, Max. He is big and brown. We walk in the park every morning.",
      [q("What is the dog's name?", ["Anna", "Max", "Sam", "Rex"], 1, "'my dog, Max'."), q("When do they walk?", ["Every evening", "Every morning", "On Sunday", "At night"], 1, "'every morning'.")]),
    L("Welcome to the shop. Today apples are cheap. Three apples for two shekels. Have a nice day!",
      [q("What is cheap today?", ["Bread", "Apples", "Milk", "Eggs"], 1, "'apples are cheap'."), q("How much for three apples?", ["One shekel", "Two shekels", "Three shekels", "Five shekels"], 1, "'three apples for two shekels'.")]),
    L("It is my sister's birthday today. She is seven. We have a cake and we will sing a song.",
      [q("Whose birthday is it?", ["The speaker's", "The sister's", "The mother's", "A friend's"], 1, "'my sister's birthday'."), q("How old is she?", ["Six", "Seven", "Eight", "Nine"], 1, "'She is seven'.")]),
  ],
  A2: [
    L("Good evening. The film starts at eight, but the doors open at half past seven. Please turn off your phones.",
      [q("What time does the film start?", ["7:00", "7:30", "8:00", "8:30"], 2, "'starts at eight'."), q("What should people do?", ["Eat", "Turn off their phones", "Stand up", "Leave"], 1, "'turn off your phones'.")]),
    L("Hello, this is the garage. Your car is ready. The brakes are fixed. You can pick it up before six today.",
      [q("What was fixed on the car?", ["The engine", "The brakes", "The lights", "The tyres"], 1, "'The brakes are fixed'."), q("By when can it be picked up?", ["Before five", "Before six", "Before seven", "Tomorrow"], 1, "'before six today'.")]),
    L("Attention, please. The 9:15 train to Tel Aviv is delayed by twenty minutes. We apologise for the delay.",
      [q("Where is the train going?", ["Haifa", "Tel Aviv", "Jerusalem", "Eilat"], 1, "'train to Tel Aviv'."), q("How long is the delay?", ["Ten minutes", "Twenty minutes", "Thirty minutes", "An hour"], 1, "'delayed by twenty minutes'.")]),
  ],
  B1: [
    L("Hi, this is the dry cleaner's. Your jacket is ready, but the stain on the sleeve didn't come out completely. Let us know if you'd like us to try again.",
      [q("What item is ready?", ["A shirt", "A jacket", "Trousers", "A coat"], 1, "'Your jacket is ready'."), q("What is the problem?", ["It's lost", "The stain didn't fully come out", "It shrank", "Wrong colour"], 1, "'the stain... didn't come out completely'.")]),
    L("Good morning, team. Quick update: the client moved the deadline forward by a week, so we'll need to prioritise. Let's meet at eleven to decide what to cut.",
      [q("What did the client do?", ["Cancelled", "Moved the deadline forward", "Added budget", "Left"], 1, "'moved the deadline forward by a week'."), q("Why meet at eleven?", ["To celebrate", "To decide what to cut", "To hire staff", "To rest"], 1, "'decide what to cut'.")]),
    L("Thanks for calling the help line. We're experiencing high call volume. Your estimated wait is ten minutes, or you can request a callback by pressing two.",
      [q("Why is the wait long?", ["A holiday", "High call volume", "Staff shortage", "A fault"], 1, "'experiencing high call volume'."), q("How can you get a callback?", ["Press one", "Press two", "Press three", "Hold"], 1, "'request a callback by pressing two'.")]),
  ],
  B2: [
    L("A brief announcement before boarding: due to a tight connection schedule, we'll be boarding by group number today. Please wait for your group to be called to keep the gate area clear.",
      [q("How will boarding work today?", ["First come first served", "By group number", "By seat row", "Randomly"], 1, "'boarding by group number'."), q("Why the special procedure?", ["Bad weather", "A tight connection schedule", "A VIP", "Staff shortage"], 1, "'due to a tight connection schedule'.")]),
    L("Quick reminder about the survey: it's completely anonymous, it takes about five minutes, and your honest feedback genuinely shapes next year's programme, so please don't just tick the middle box.",
      [q("How long does the survey take?", ["One minute", "Five minutes", "Ten minutes", "Half an hour"], 1, "'about five minutes'."), q("What does the speaker ask people not to do?", ["Skip it", "Just tick the middle box", "Sign it", "Rush"], 1, "'don't just tick the middle box'.")]),
    L("I'll keep this short. The pilot project exceeded expectations, but scaling it will require hiring, and hiring requires budget we don't yet have. So the next step is a proposal to the board, not a launch.",
      [q("How did the pilot project do?", ["It failed", "It exceeded expectations", "It was average", "It was cancelled"], 1, "'exceeded expectations'."), q("What is the actual next step?", ["A launch", "A proposal to the board", "Hiring now", "Nothing"], 1, "'a proposal to the board, not a launch'.")]),
  ],
  C1: [
    L("I want to flag a subtle risk. The model performs beautifully on historical data, but historical data is exactly where it was trained — so strong results there tell us less about the future than the dashboard implies.",
      [q("Where does the model perform well?", ["On future data", "On historical data", "Everywhere", "Nowhere"], 1, "'performs beautifully on historical data'."), q("What is the speaker's concern?", ["It's too slow", "Strong past results may not predict the future", "It's expensive", "It's inaccurate everywhere"], 1, "'tell us less about the future than the dashboard implies'.")]),
    L("Let me reframe the complaint. It's not that customers dislike the new design; it's that we changed it without warning. People can adapt to almost anything except a surprise sprung on them.",
      [q("What is the real problem, per the speaker?", ["The design is ugly", "It was changed without warning", "It's too slow", "It costs more"], 1, "'we changed it without warning'."), q("What can people not adapt to easily?", ["New colours", "A surprise sprung on them", "Slower speed", "More features"], 1, "'except a surprise sprung on them'.")]),
    L("In fairness to the previous team, they were solving a different problem with the tools they had. It's easy to look back and call their choices shortsighted, but foresight is far rarer than hindsight pretends.",
      [q("How does the speaker treat the previous team?", ["Blames them", "Defends them in fairness", "Ignores them", "Praises them fully"], 1, "'In fairness to the previous team'."), q("What is the speaker's point about foresight?", ["It's common", "It's rarer than hindsight pretends", "It's useless", "It's easy"], 1, "'foresight is far rarer than hindsight pretends'.")]),
  ],
  C2: [
    L("I'd enter one caveat to all this enthusiasm. The metric we're celebrating measures engagement, not value — and the two diverge precisely when content is designed to provoke rather than to inform.",
      [q("What does the celebrated metric measure?", ["Value", "Engagement", "Accuracy", "Revenue"], 1, "'measures engagement, not value'."), q("When do the two diverge?", ["Never", "When content provokes rather than informs", "When it's free", "Always"], 1, "'designed to provoke rather than to inform'.")]),
    L("The proposal is elegant, and I mean that as only a half-compliment. Elegance can be a warning sign — reality is rarely as tidy as our models, and a theory with no loose ends has usually hidden them rather than resolved them.",
      [q("Why is calling it 'elegant' only a half-compliment?", ["It's ugly", "Elegance can be a warning sign", "It's complex", "It's cheap"], 1, "'Elegance can be a warning sign'."), q("What does a theory with no loose ends usually do?", ["Solve everything", "Hide the loose ends", "Fail", "Simplify honestly"], 1, "'hidden them rather than resolved them'.")]),
    L("Let's not confuse consensus with truth. A room can agree unanimously and still be wrong, especially if everyone is drawing on the same flawed source and mistaking its echo for independent confirmation.",
      [q("What does the speaker warn against confusing?", ["Speed and cost", "Consensus with truth", "Old and new", "Data and opinion"], 1, "'confuse consensus with truth'."), q("What mistake do people make with a shared flawed source?", ["Ignore it", "Mistake its echo for independent confirmation", "Reject it", "Improve it"], 1, "'mistaking its echo for independent confirmation'.")]),
  ],
};

// Extra speaking sentences per level, merged into the speaking pool.
export const MORE_SPEAKING = {
  A1: [
    { text: "I have a brother and a sister.", translation: "יש לי אח ואחות." },
    { text: "Can I have some water, please?", translation: "אפשר קצת מים, בבקשה?" },
    { text: "I don't understand. Can you help me?", translation: "אני לא מבין. תוכל לעזור לי?" },
    { text: "My favourite colour is blue.", translation: "הצבע האהוב עליי הוא כחול." },
    { text: "See you tomorrow!", translation: "נתראה מחר!" },
    { text: "I am a little tired today.", translation: "אני קצת עייף היום." },
  ],
  A2: [
    { text: "I'm looking for the train station.", translation: "אני מחפש את תחנת הרכבת." },
    { text: "Could I have the bill, please?", translation: "אפשר את החשבון, בבקשה?" },
    { text: "I went to the doctor yesterday.", translation: "הלכתי לרופא אתמול." },
    { text: "What do you usually do on weekends?", translation: "מה אתה בדרך כלל עושה בסופי שבוע?" },
    { text: "It's a bit too expensive for me.", translation: "זה קצת יקר מדי בשבילי." },
    { text: "Can you speak more slowly, please?", translation: "תוכל לדבר לאט יותר, בבקשה?" },
  ],
  B1: [
    { text: "I'm thinking about changing my job.", translation: "אני שוקל להחליף עבודה." },
    { text: "Could you recommend a good place to eat?", translation: "תוכל להמליץ על מקום טוב לאכול?" },
    { text: "I'm afraid I can't make it on Friday.", translation: "אני חושש שלא אוכל להגיע ביום שישי." },
    { text: "What would you do in my situation?", translation: "מה היית עושה במצב שלי?" },
    { text: "It depends on the weather, I suppose.", translation: "זה תלוי במזג האוויר, אני מניח." },
    { text: "Let me think about it and get back to you.", translation: "תן לי לחשוב על זה ואחזור אליך." },
  ],
  B2: [
    { text: "I'd like to raise a point about the schedule.", translation: "אשמח להעלות נקודה לגבי לוח הזמנים." },
    { text: "To be honest, I have mixed feelings about it.", translation: "למען האמת, יש לי רגשות מעורבים לגבי זה." },
    { text: "Could we revisit this issue next week?", translation: "נוכל לחזור לסוגיה הזו בשבוע הבא?" },
    { text: "That depends on a number of factors.", translation: "זה תלוי במספר גורמים." },
    { text: "I see what you mean, but consider this.", translation: "אני מבין למה אתה מתכוון, אבל שקול את זה." },
    { text: "Let's not lose sight of our main goal.", translation: "בוא לא נאבד את המטרה המרכזית שלנו." },
  ],
  C1: [
    { text: "I'd like to play devil's advocate for a moment.", translation: "אני רוצה לשחק עורך דין של השטן לרגע." },
    { text: "On balance, I think the risk is justified.", translation: "בסך הכול, אני חושב שהסיכון מוצדק." },
    { text: "That's a valid concern, and worth addressing.", translation: "זו חשש לגיטימי, וכדאי להתייחס אליו." },
    { text: "I'd hesitate to draw firm conclusions yet.", translation: "הייתי נמנע מלהסיק מסקנות נחרצות בשלב זה." },
    { text: "Let's distinguish the symptom from the cause.", translation: "בוא נבחין בין הסימפטום לסיבה." },
    { text: "With the benefit of hindsight, we'd do it differently.", translation: "בחוכמה שבדיעבד, היינו עושים זאת אחרת." },
  ],
  C2: [
    { text: "I'd be wary of overstating the significance here.", translation: "הייתי נזהר מלהפריז במשמעות כאן." },
    { text: "That framing, while neat, rather begs the question.", translation: "המסגור הזה, אף שהוא מסודר, די מניח את המבוקש." },
    { text: "We're conflating two quite separate issues.", translation: "אנחנו מערבבים שתי סוגיות נפרדות לגמרי." },
    { text: "I'd sooner reserve judgement than commit prematurely.", translation: "אעדיף להשהות שיפוט מאשר להתחייב בטרם עת." },
    { text: "The exception, far from disproving the rule, refines it.", translation: "החריג, רחוק מלהפריך את הכלל, מחדד אותו." },
    { text: "Let's resist the temptation of a tidy narrative.", translation: "בוא ננגד את הפיתוי של נרטיב מסודר מדי." },
  ],
};
