// Round 8 of additional Reading, Listening and Speaking content.
// Weighted to A1-B1. Merged into the data set by the generator.

const R = (title, text, glossary, questions) => ({ title, text, glossary, questions });
const g = (word, partOfSpeech, definition, example, translation) => ({ word, partOfSpeech, definition, example, translation });
const q = (question, options, correctIndex, explanation) => ({ question, options, correctIndex, explanation });
const L = (transcript, questions) => ({ transcript, questions });

export const MORE_READINGS8 = {
  A1: [
    R("What's in My Bag Today (מה יש היום בתיק שלי)",
      "I have a blue school bag. Inside there are books, pens and a small box for lunch. The bag is heavy on Mondays. I carry it on my back every day.",
      [g("bag", "noun", "תיק", "A school bag.", "תיק"), g("heavy", "adjective", "כבד", "It is heavy.", "כבד"), g("carry", "verb", "לשאת, לסחוב", "I carry it.", "לשאת/לסחוב")],
      [q("What colour is the bag?", ["Red", "Blue", "Green", "Black"], 1, "'a blue school bag'."), q("When is the bag heavy?", ["On Fridays", "On Mondays", "On Sundays", "Every night"], 1, "'heavy on Mondays'.")]),
    R("The Little Red Ball (הכדור האדום הקטן)",
      "My dog Rex loves his little red ball. I throw it and he runs fast. He brings it back to me every time. We play in the garden until the sun goes down.",
      [g("throw", "verb", "לזרוק", "I throw the ball.", "לזרוק"), g("fast", "adverb", "מהר", "He runs fast.", "מהר"), g("bring", "verb", "להביא", "He brings it back.", "להביא")],
      [q("What does Rex love?", ["A bone", "His little red ball", "A stick", "Food"], 1, "'his little red ball'."), q("Where do they play?", ["In the park", "In the garden", "Inside", "On the street"], 1, "'We play in the garden'.")]),
    R("Brushing My Teeth (מצחצח שיניים)",
      "Every morning and every night I brush my teeth. I use a green toothbrush and white toothpaste. It takes two minutes. Clean teeth are healthy and strong.",
      [g("brush", "verb", "לצחצח, להבריש", "Brush your teeth.", "לצחצח"), g("teeth", "noun", "שיניים", "Clean teeth.", "שיניים"), g("healthy", "adjective", "בריא", "Healthy teeth.", "בריא")],
      [q("How often does the child brush?", ["Once a day", "Morning and night", "Once a week", "Never"], 1, "'Every morning and every night'."), q("How long does it take?", ["One minute", "Two minutes", "Five minutes", "Ten minutes"], 1, "'It takes two minutes'.")]),
    R("A Visit to the Farm (ביקור בחווה)",
      "On the farm we see cows, sheep and a brown horse. The farmer gives us fresh milk. I feed the chickens with corn. The farm smells of grass and animals.",
      [g("farm", "noun", "חווה, משק", "On the farm.", "חווה/משק"), g("sheep", "noun", "כבשה/כבשים", "We see sheep.", "כבשה/כבשים"), g("feed", "verb", "להאכיל", "I feed the chickens.", "להאכיל")],
      [q("What colour is the horse?", ["Black", "Brown", "White", "Grey"], 1, "'a brown horse'."), q("What does the child feed the chickens?", ["Bread", "Corn", "Grass", "Milk"], 1, "'I feed the chickens with corn'.")]),
    R("My Best Friend (החבר הכי טוב שלי)",
      "My best friend is Omar. We sit together at school and share our snacks. He is funny and makes me laugh. After school we ride our bikes home.",
      [g("share", "verb", "לחלוק", "We share snacks.", "לחלוק"), g("funny", "adjective", "מצחיק", "He is funny.", "מצחיק"), g("laugh", "verb", "לצחוק", "He makes me laugh.", "לצחוק")],
      [q("Who is the best friend?", ["Omar", "Rex", "Sam", "Ben"], 0, "'My best friend is Omar'."), q("What do they do after school?", ["Study", "Ride their bikes home", "Watch TV", "Sleep"], 1, "'we ride our bikes home'.")]),
  ],
  A2: [
    R("The Power Cut (הפסקת חשמל)",
      "Last night the power went out during a storm. The whole house was suddenly dark. We lit some candles and played cards together. Strangely, it became one of the nicest evenings we had had in months.",
      [g("power cut", "noun", "הפסקת חשמל", "A sudden power cut.", "הפסקת חשמל"), g("candle", "noun", "נר", "Light a candle.", "נר"), g("strangely", "adverb", "באופן מוזר", "Strangely nice.", "באופן מוזר")],
      [q("Why did the power go out?", ["A fault", "During a storm", "No reason", "Repairs"], 1, "'the power went out during a storm'."), q("What did the family do?", ["Slept", "Lit candles and played cards", "Left the house", "Watched TV"], 1, "'We lit some candles and played cards'.")]),
    R("A Job Interview (ראיון עבודה)",
      "I had a job interview this morning. I wore my best shirt and arrived ten minutes early. The questions were hard, but I stayed calm and honest. They said they will call me next week.",
      [g("interview", "noun", "ראיון", "A job interview.", "ראיון"), g("arrive", "verb", "להגיע", "I arrived early.", "להגיע"), g("honest", "adjective", "כן, ישר", "Calm and honest.", "כן/ישר")],
      [q("When did the writer arrive?", ["Late", "Ten minutes early", "On time", "An hour early"], 1, "'arrived ten minutes early'."), q("When will they call?", ["Today", "Next week", "Never", "Tomorrow"], 1, "'they will call me next week'.")]),
    R("Planting a Tree (שותלים עץ)",
      "On Saturday our class planted a tree in the schoolyard. We dug a hole, placed the young tree inside, and covered the roots with soil. The teacher said that one day it will give shade to other children.",
      [g("plant", "verb", "לשתול", "Plant a tree.", "לשתול"), g("dig", "verb", "לחפור", "We dug a hole.", "לחפור"), g("shade", "noun", "צל", "Give shade.", "צל")],
      [q("Where did they plant the tree?", ["In a park", "In the schoolyard", "At home", "In a field"], 1, "'planted a tree in the schoolyard'."), q("What will the tree give one day?", ["Fruit", "Shade", "Flowers", "Wood"], 1, "'it will give shade to other children'.")]),
    R("The Wrong Bus (האוטובוס הלא נכון)",
      "I was in a hurry and jumped on the first bus I saw. Ten minutes later I realised it was going the wrong way! I got off, crossed the road, and waited for the right one. I still made it on time.",
      [g("hurry", "noun", "חיפזון, מהירות", "In a hurry.", "חיפזון"), g("realise", "verb", "להבין, לקלוט", "I realised my mistake.", "להבין/לקלוט"), g("cross", "verb", "לחצות", "Cross the road.", "לחצות")],
      [q("What mistake did the writer make?", ["Lost a ticket", "Took the wrong bus", "Missed the bus", "Forgot money"], 1, "'it was going the wrong way'."), q("Did the writer arrive on time?", ["No", "Yes, still on time", "Very late", "Early"], 1, "'I still made it on time'.")]),
    R("A Gift for My Mother (מתנה לאמא שלי)",
      "My mother's birthday was coming, and I had little money. So I decided to make her a gift instead of buying one. I painted a picture of our house and wrote her a card. She said it was the best present ever.",
      [g("gift", "noun", "מתנה", "A handmade gift.", "מתנה"), g("instead", "adverb", "במקום", "Make instead of buy.", "במקום"), g("present", "noun", "מתנה", "The best present.", "מתנה")],
      [q("Why did the writer make a gift?", ["For fun", "Had little money", "It was a rule", "By mistake"], 1, "'I had little money'."), q("What did the writer make?", ["A cake", "A painting and a card", "A scarf", "A song"], 1, "'I painted a picture... and wrote her a card'.")]),
  ],
  B1: [
    R("Cooking for One (לבשל לאחד)",
      "When I started living alone, cooking for just myself felt pointless. Gradually I learned to see it differently: a good meal is a way of caring for yourself. Now I light a candle, plate the food nicely, and enjoy my own company.",
      [g("pointless", "adjective", "חסר טעם, חסר תועלת", "It felt pointless.", "חסר טעם/חסר תועלת"), g("gradually", "adverb", "בהדרגה", "Gradually I learned.", "בהדרגה"), g("company", "noun", "חברה, נוכחות", "My own company.", "חברה/נוכחות")],
      [q("How did cooking for one feel at first?", ["Fun", "Pointless", "Easy", "Exciting"], 1, "'cooking for just myself felt pointless'."), q("How does the writer see it now?", ["A chore", "A way of caring for yourself", "A waste", "A hobby only"], 1, "'a way of caring for yourself'.")]),
    R("The Second-Hand Bookshop (חנות הספרים המשומשים)",
      "There is an old bookshop near my home where every book has already lived another life. I love finding notes in the margins left by strangers. Buying a used book feels like joining a quiet conversation that began long before me.",
      [g("second-hand", "adjective", "יד שנייה, משומש", "A second-hand book.", "יד שנייה/משומש"), g("margin", "noun", "שוליים", "Notes in the margins.", "שוליים"), g("stranger", "noun", "זר, אדם לא מוכר", "Left by strangers.", "זר")],
      [q("What does the writer love finding?", ["New books", "Notes in the margins", "Cheap prices", "Maps"], 1, "'finding notes in the margins'."), q("Buying a used book feels like what?", ["Wasting money", "Joining a quiet conversation", "A risk", "A chore"], 1, "'joining a quiet conversation'.")]),
    R("Walking the Dog at Dawn (מטייל עם הכלב עם שחר)",
      "My dog wakes me at five, whether I like it or not. At first I resented those early walks. Now I treasure them: the empty streets, the cool air, the city before it remembers to be busy. He gave me the mornings I never knew I wanted.",
      [g("dawn", "noun", "שחר, עלות השחר", "Walk at dawn.", "שחר"), g("resent", "verb", "לכעוס על, להתמרמר", "I resented it.", "להתמרמר על"), g("treasure", "verb", "להוקיר, לאהוב מאוד", "I treasure them.", "להוקיר")],
      [q("When does the dog wake the writer?", ["At seven", "At five", "At noon", "At dawn-plus"], 1, "'wakes me at five'."), q("How does the writer feel about the walks now?", ["Annoyed", "Treasures them", "Bored", "Tired"], 1, "'Now I treasure them'.")]),
    R("Learning an Instrument as an Adult (ללמוד נגינה בגיל מבוגר)",
      "I started learning the piano at forty. My fingers are slow and my progress is humbling. But there is a special freedom in being a beginner again, with nothing to prove and everything to discover. I play badly, and I love it.",
      [g("instrument", "noun", "כלי נגינה", "Learn an instrument.", "כלי נגינה"), g("humbling", "adjective", "מצניע, מלמד ענווה", "A humbling progress.", "מצניע/מלמד ענווה"), g("beginner", "noun", "מתחיל", "A beginner again.", "מתחיל")],
      [q("When did the writer start the piano?", ["At twenty", "At forty", "As a child", "At sixty"], 1, "'started learning the piano at forty'."), q("What is special about being a beginner?", ["It is fast", "Freedom, with nothing to prove", "It is easy", "It is cheap"], 1, "'nothing to prove and everything to discover'.")]),
    R("Turning Off Notifications (לכבות את ההתראות)",
      "My phone used to buzz every few minutes, pulling my attention in all directions. One day I turned off almost every notification. The silence was strange at first, then wonderful. I check things when I choose to now — not when a screen demands it.",
      [g("notification", "noun", "התראה, הודעה", "Turn off notifications.", "התראה"), g("buzz", "verb", "לזמזם, לרטוט", "The phone buzzed.", "לזמזם/לרטוט"), g("demand", "verb", "לדרוש", "The screen demands it.", "לדרוש")],
      [q("What did the phone used to do?", ["Stay silent", "Buzz every few minutes", "Switch off", "Ring loudly"], 1, "'buzz every few minutes'."), q("How does the writer check things now?", ["Constantly", "When they choose to", "Never", "Every minute"], 1, "'I check things when I choose to now'.")]),
  ],
  B2: [
    R("The Trap of Comparison (מלכודת ההשוואה)",
      "Social media offers an endless stream of other people's highlights, against which our ordinary days look dull. But we are comparing our backstage to everyone else's polished stage. The contest is rigged from the start, and the only winning move is to stop playing.",
      [g("highlight", "noun", "רגע שיא, נקודת אור", "Other people's highlights.", "רגע שיא"), g("polished", "adjective", "מלוטש, מהוקצע", "A polished stage.", "מלוטש"), g("rigged", "adjective", "מכור, מסודר מראש", "The contest is rigged.", "מכור/מסודר מראש")],
      [q("What do we compare, per the text?", ["Two stages", "Our backstage to others' polished stage", "Incomes", "Photos only"], 1, "'comparing our backstage to everyone else's polished stage'."), q("What is the 'only winning move'?", ["Win the contest", "Stop playing", "Post more", "Compare harder"], 1, "'the only winning move is to stop playing'.")]),
    R("Why Deadlines Help (למה מועדי יעד עוזרים)",
      "We resent deadlines, yet a task without one tends to expand to fill all available time, or never to end at all. A firm date forces the hundred small decisions that 'someday' endlessly postpones. The constraint we resist is often the structure we secretly need.",
      [g("deadline", "noun", "מועד אחרון, דדליין", "A firm deadline.", "מועד אחרון/דדליין"), g("expand", "verb", "להתרחב, להתפשט", "Work expands.", "להתרחב"), g("postpone", "verb", "לדחות", "Someday postpones it.", "לדחות")],
      [q("What happens to a task without a deadline?", ["It ends fast", "It expands or never ends", "It improves", "It shrinks"], 1, "'expand to fill all available time, or never to end'."), q("How is a deadline reframed?", ["A burden", "The structure we secretly need", "A trick", "A waste"], 1, "'the structure we secretly need'.")]),
    R("The Skill of Listening (אומנות ההקשבה)",
      "Most of us listen only to find the gap where we can insert our own reply. Real listening is rarer and harder: holding your response in suspension long enough to actually understand the other person. Done well, it can feel to the speaker like being seen for the first time.",
      [g("insert", "verb", "להכניס, לשבץ", "Insert a reply.", "להכניס/לשבץ"), g("suspension", "noun", "השהיה, דחייה", "Hold in suspension.", "השהיה"), g("rarer", "adjective", "נדיר יותר", "Rarer and harder.", "נדיר יותר")],
      [q("What do most people listen for?", ["Understanding", "A gap to insert their reply", "Facts", "Mistakes"], 1, "'find the gap where we can insert our own reply'."), q("What can real listening feel like to the speaker?", ["Boring", "Being seen for the first time", "A test", "An attack"], 1, "'like being seen for the first time'.")]),
  ],
  C1: [
    R("Loss Aversion (סלידה מהפסד)",
      "Experiments show that losing ten dollars hurts roughly twice as much as gaining ten dollars pleases. This asymmetry quietly steers our choices, making us cling to what we have and shy away from worthwhile risks. Understanding the bias does not remove it, but it can loosen its grip.",
      [g("aversion", "noun", "סלידה, רתיעה", "Loss aversion.", "סלידה/רתיעה"), g("asymmetry", "noun", "אי-סימטריה, חוסר איזון", "This asymmetry.", "אי-סימטריה"), g("cling", "verb", "להיאחז, להיצמד", "Cling to what we have.", "להיאחז")],
      [q("How much more does a loss hurt than a gain pleases?", ["The same", "Roughly twice as much", "Half as much", "Ten times"], 1, "'twice as much as gaining ten dollars pleases'."), q("What does understanding the bias do?", ["Removes it", "Can loosen its grip", "Makes it worse", "Nothing"], 1, "'it can loosen its grip'.")]),
    R("The Pareto Principle (עקרון פארטו)",
      "In many systems, roughly eighty percent of results flow from twenty percent of causes — a fifth of customers, of effort, of code. The insight is not the exact numbers but the shape: contributions are rarely equal. Find the vital few, and you can often let the trivial many wait.",
      [g("flow from", "phrase", "לנבוע מ-", "Results flow from causes.", "לנבוע מ-"), g("vital", "adjective", "חיוני, מכריע", "The vital few.", "חיוני/מכריע"), g("trivial", "adjective", "זניח, שולי", "The trivial many.", "זניח/שולי")],
      [q("What does the principle claim?", ["All causes are equal", "~80% of results from ~20% of causes", "Effort wasted", "Nothing matters"], 1, "'eighty percent of results flow from twenty percent of causes'."), q("What is the real insight?", ["The exact numbers", "Contributions are rarely equal", "Work harder", "Count everything"], 1, "'not the exact numbers but the shape'.")]),
    R("Confirmation Bias (הטיית האישור)",
      "Once we hold a belief, we unconsciously hunt for evidence that supports it and explain away whatever does not. The mind behaves less like a scientist testing a theory than a lawyer defending a client. Genuine thinking begins only when we deliberately seek the case against ourselves.",
      [g("unconsciously", "adverb", "באופן לא מודע", "We unconsciously hunt.", "באופן לא מודע"), g("explain away", "phrase", "לתרץ, להסביר ולבטל", "Explain away the rest.", "לתרץ/להסביר ולבטל"), g("deliberately", "adverb", "במכוון, בכוונה", "Deliberately seek.", "במכוון")],
      [q("What does the mind hunt for, per the text?", ["The truth", "Evidence that supports our belief", "New ideas", "Nothing"], 1, "'hunt for evidence that supports it'."), q("When does genuine thinking begin?", ["Right away", "When we seek the case against ourselves", "Never", "With more data"], 1, "'when we deliberately seek the case against ourselves'.")]),
  ],
  C2: [
    R("Epistemic Humility (ענווה אפיסטמית)",
      "The more deeply one studies almost any field, the more vividly its frontier of ignorance comes into view; expertise expands the perimeter of the known and, with it, the awareness of all that borders it. The confident pronouncements tend to come from the foothills, not the summit.",
      [g("epistemic", "adjective", "הקשור לידע ולהכרה", "Epistemic humility.", "אפיסטמי/הקשור לידע"), g("frontier", "noun", "גבול, חזית", "Frontier of ignorance.", "גבול/חזית"), g("perimeter", "noun", "היקף, גבול", "The perimeter of the known.", "היקף")],
      [q("What comes into view with deeper study?", ["Certainty", "The frontier of ignorance", "Wealth", "Fame"], 1, "'its frontier of ignorance comes into view'."), q("Where do confident pronouncements tend to come from?", ["The summit", "The foothills", "Experts", "Nowhere"], 1, "'from the foothills, not the summit'.")]),
    R("The Observer Effect (אפקט הצופה)",
      "In some systems, the very act of measuring alters what is measured: a thermometer warms the liquid, a survey shifts the opinion it records, a watched worker behaves unnaturally. Pure, detached observation is often a comforting fiction; to look is, frequently, already to interfere.",
      [g("alter", "verb", "לשנות", "Measuring alters it.", "לשנות"), g("detached", "adjective", "מנותק, אובייקטיבי", "Detached observation.", "מנותק"), g("interfere", "verb", "להתערב, להפריע", "To look is to interfere.", "להתערב/להפריע")],
      [q("What can the act of measuring do?", ["Nothing", "Alter what is measured", "Improve accuracy", "Stop the system"], 1, "'the very act of measuring alters what is measured'."), q("How is 'detached observation' described?", ["A fact", "A comforting fiction", "Easy", "Common"], 1, "'a comforting fiction'.")]),
    R("Moral Luck (מזל מוסרי)",
      "Two drivers are equally careless; one happens upon an empty road, the other on a child. We condemn the second far more harshly, though the difference between them was pure chance. Much of what we call desert, on close inspection, turns out to rest uneasily on luck.",
      [g("careless", "adjective", "רשלן, חסר זהירות", "Equally careless.", "רשלן/חסר זהירות"), g("condemn", "verb", "לגנות, להוקיע", "We condemn the second.", "לגנות/להוקיע"), g("desert", "noun", "מה שמגיע לאדם, גמול ראוי", "What we call desert.", "גמול ראוי")],
      [q("How do the two careless drivers differ?", ["In skill", "By pure chance (the road)", "In intent", "In speed"], 1, "'the difference between them was pure chance'."), q("What does 'desert' often rest on, per the text?", ["Merit", "Luck", "Effort", "Law"], 1, "'turns out to rest uneasily on luck'.")]),
  ],
};

export const MORE_LISTENINGS8 = {
  A1: [
    L("Hello! It is time for music. Please take a drum or a bell. We will sing a happy song together. Are you ready?",
      [q("What time is it?", ["Lunch time", "Music time", "Bed time", "Story time"], 1, "'it is time for music'."), q("What can the children take?", ["A book", "A drum or a bell", "A ball", "A pen"], 1, "'take a drum or a bell'.")]),
    L("This is the train to the zoo. The doors are closing now. Please keep your ticket. We arrive in ten minutes.",
      [q("Where is the train going?", ["The city", "The zoo", "The beach", "School"], 1, "'the train to the zoo'."), q("When does it arrive?", ["In five minutes", "In ten minutes", "Now", "In an hour"], 1, "'We arrive in ten minutes'.")]),
    L("Look, it is snowing! Let's put on our coats and gloves. We can make a snowman in the garden. It will be cold but fun.",
      [q("What is the weather?", ["Sunny", "Snowing", "Rainy", "Windy"], 1, "'it is snowing'."), q("What will they make?", ["A cake", "A snowman", "A fire", "A house"], 1, "'make a snowman in the garden'.")]),
    L("Good night, Sami. Put your toys in the box, please. Then we read one story. Sweet dreams!",
      [q("Where should the toys go?", ["On the bed", "In the box", "On the floor", "Outside"], 1, "'Put your toys in the box'."), q("How many stories?", ["One", "Two", "Three", "None"], 0, "'we read one story'.")]),
    L("Welcome to the café. We have apple juice, milk and water for children. The cakes are fresh today. What would you like?",
      [q("Which drink is for children?", ["Coffee", "Apple juice, milk and water", "Tea", "Soda"], 1, "'apple juice, milk and water for children'."), q("What is fresh today?", ["The bread", "The cakes", "The fruit", "The soup"], 1, "'The cakes are fresh today'.")]),
  ],
  A2: [
    L("Good afternoon. Because of road work, bus number five will not stop at Main Street today. Please use the stop on Park Road instead.",
      [q("Why is the stop changed?", ["An accident", "Road work", "A holiday", "A parade"], 1, "'Because of road work'."), q("Which stop should people use?", ["Main Street", "Park Road", "City Hall", "The station"], 1, "'use the stop on Park Road instead'.")]),
    L("Hi, this is the library. The book you reserved has arrived. Please collect it within seven days, or it will go back on the shelf.",
      [q("What has arrived?", ["A fine", "The reserved book", "A card", "A letter"], 1, "'The book you reserved has arrived'."), q("How long to collect it?", ["Three days", "Seven days", "One day", "A month"], 1, "'within seven days'.")]),
    L("Attention, please. The museum closes in thirty minutes. The last entry to the dinosaur hall is in ten minutes. Thank you for visiting.",
      [q("When does the museum close?", ["In ten minutes", "In thirty minutes", "Now", "In an hour"], 1, "'closes in thirty minutes'."), q("When is the last entry to the dinosaur hall?", ["In thirty minutes", "In ten minutes", "Closed", "Tomorrow"], 1, "'last entry... is in ten minutes'.")]),
    L("Hello, it's the garage. Your car is ready. We changed the tyre and checked the brakes. The total is sixty dollars. We're open till five.",
      [q("What did the garage do?", ["Washed the car", "Changed the tyre and checked the brakes", "Painted it", "Nothing"], 1, "'changed the tyre and checked the brakes'."), q("What is the total?", ["Fifty dollars", "Sixty dollars", "Sixteen dollars", "Free"], 1, "'The total is sixty dollars'.")]),
    L("Welcome to the cooking class. Tonight we make a simple tomato soup. Aprons are by the sink, and please wash your hands before we begin.",
      [q("What will they make?", ["Bread", "Tomato soup", "Salad", "Cake"], 1, "'a simple tomato soup'."), q("What should students do before starting?", ["Sit down", "Wash their hands", "Pay", "Read"], 1, "'wash your hands before we begin'.")]),
  ],
  B1: [
    L("Good morning, everyone. A reminder that the office will work from home this Friday while the lifts are repaired. Please make sure your laptop is charged and take it home tonight.",
      [q("Why will people work from home?", ["A holiday", "The lifts are being repaired", "Bad weather", "A meeting"], 1, "'while the lifts are repaired'."), q("What should people do tonight?", ["Stay late", "Take their charged laptop home", "Email the boss", "Nothing"], 1, "'take it home tonight'.")]),
    L("This is a neighbourhood notice. We're starting a tool-sharing shed in the community garden. Instead of everyone buying a ladder they use once, we'll share one. Sign up at Saturday's meeting.",
      [q("What is being started?", ["A shop", "A tool-sharing shed", "A class", "A market"], 1, "'a tool-sharing shed'."), q("When can people sign up?", ["Online", "At Saturday's meeting", "By phone", "Anytime"], 1, "'Sign up at Saturday's meeting'.")]),
    L("Hello, this is the dentist's office. We have to move your Tuesday appointment because the dentist is unwell. Could you call us back to choose a new time? Sorry for the trouble.",
      [q("Why is the appointment moved?", ["The patient is late", "The dentist is unwell", "A holiday", "A mistake"], 1, "'the dentist is unwell'."), q("What should the patient do?", ["Come anyway", "Call back to choose a new time", "Wait", "Cancel"], 1, "'call us back to choose a new time'.")]),
    L("Welcome to the hiking group. Today's trail is about two hours and has one steep part near the top. Drink water often, and stay behind the leader at the front.",
      [q("How long is today's trail?", ["One hour", "About two hours", "All day", "Thirty minutes"], 1, "'about two hours'."), q("What should hikers do?", ["Run ahead", "Stay behind the leader", "Skip water", "Turn back"], 1, "'stay behind the leader at the front'.")]),
    L("This is your captain speaking. We expect a little turbulence as we cross the mountains, so please keep your seatbelt fastened. We should land on time, at about three o'clock.",
      [q("Why keep seatbelts fastened?", ["Take-off", "Expected turbulence over the mountains", "Landing only", "A rule"], 1, "'a little turbulence as we cross the mountains'."), q("When should the plane land?", ["At two", "At about three o'clock", "Late", "At four"], 1, "'land on time, at about three o'clock'.")]),
  ],
  B2: [
    L("A quick thought on habits: don't rely on motivation, which comes and goes. Design your environment instead. Put the book on your pillow and the snacks out of sight, and the right choice becomes the easy one.",
      [q("What does the speaker say about motivation?", ["Rely on it", "It comes and goes", "It is constant", "It is enough"], 1, "'motivation, which comes and goes'."), q("What should you design instead?", ["Your goals", "Your environment", "Your friends", "Your schedule"], 1, "'Design your environment instead'.")]),
    L("Historians warn against judging the past purely by today's standards. People acted within the knowledge and norms of their time. Understanding why something happened is not the same as excusing it — but it is where honest history must begin.",
      [q("What do historians warn against?", ["Reading old texts", "Judging the past purely by today's standards", "Asking questions", "Writing books"], 1, "'judging the past purely by today's standards'."), q("Understanding why something happened is not the same as what?", ["Studying it", "Excusing it", "Recording it", "Teaching it"], 1, "'not the same as excusing it'.")]),
    L("On teamwork: a group where everyone agrees quickly isn't harmonious, it's asleep. Healthy disagreement, voiced early and respectfully, is how teams catch the flaws that polite silence would let through.",
      [q("What does quick agreement suggest?", ["Harmony", "The group is asleep", "Success", "Skill"], 1, "'isn't harmonious, it's asleep'."), q("What does healthy disagreement help teams do?", ["Waste time", "Catch flaws polite silence would miss", "Argue more", "Avoid work"], 1, "'catch the flaws that polite silence would let through'.")]),
  ],
  C1: [
    L("Consider 'anchoring'. The first number mentioned in a negotiation quietly drags every later figure toward it, even when it's arbitrary. Knowing this, you can either set the anchor yourself or consciously discount one that's been set for you.",
      [q("What does anchoring describe?", ["The last offer wins", "The first number drags later figures toward it", "Splitting the difference", "Ignoring numbers"], 1, "'the first number... quietly drags every later figure toward it'."), q("What can you do, knowing this?", ["Nothing", "Set the anchor or discount one set for you", "Always agree", "Leave"], 1, "'set the anchor yourself or consciously discount one'.")]),
    L("There's a notion called 'the tyranny of small decisions'. No single choice to drive instead of walk, or click instead of read, seems to matter — yet their sum quietly shapes a life and a planet. The big outcomes hide inside the tiny, unexamined ones.",
      [q("What does the 'tyranny of small decisions' describe?", ["One big choice", "How tiny choices sum to large outcomes", "Avoiding decisions", "Voting"], 1, "'their sum quietly shapes a life and a planet'."), q("Where do the big outcomes hide?", ["In big choices", "Inside the tiny, unexamined ones", "In luck", "Nowhere"], 1, "'hide inside the tiny, unexamined ones'.")]),
    L("Economists distinguish 'stocks' from 'flows'. Your bank balance is a stock; your monthly income a flow. Many arguments go nowhere because two people are debating a flow as though it were a stock — confusing the rate of change with the thing itself.",
      [q("What is a 'flow', per the talk?", ["A balance", "Something like monthly income", "A debt", "A total"], 1, "'your monthly income a flow'."), q("Why do many arguments go nowhere?", ["Too few facts", "Debating a flow as though it were a stock", "No data", "Bad manners"], 1, "'confusing the rate of change with the thing itself'.")]),
  ],
  C2: [
    L("Reflect on the difference between 'risk' and 'uncertainty'. Risk is a game with known odds, like a dice roll; uncertainty is a game whose very rules are hidden. We comfort ourselves by dressing the second up as the first, attaching crisp probabilities to things we simply cannot know.",
      [q("How is 'risk' defined here?", ["Hidden rules", "A game with known odds", "Total ignorance", "A guess"], 1, "'Risk is a game with known odds'."), q("How do we comfort ourselves?", ["By admitting ignorance", "By dressing uncertainty up as risk", "By waiting", "By guessing"], 1, "'dressing the second up as the first'.")]),
    L("There's a subtle trap in hindsight: once we know how a story ended, it feels as though it could never have gone otherwise. This 'creeping determinism' erases the genuine uncertainty that the people involved actually faced, and makes us harsher judges than we have any right to be.",
      [q("What does hindsight make events feel like?", ["Surprising", "As though they could never have gone otherwise", "Random", "Unimportant"], 1, "'it feels as though it could never have gone otherwise'."), q("What does 'creeping determinism' erase?", ["The facts", "The genuine uncertainty people faced", "The ending", "The dates"], 1, "'erases the genuine uncertainty that the people involved actually faced'.")]),
    L("Note how often a 'compromise' is mistaken for wisdom. Splitting the difference between a true claim and a false one does not yield a half-truth; it yields a confident error. Balance is a virtue between reasonable positions, not a substitute for judging which positions are reasonable.",
      [q("What does splitting the difference between true and false yield?", ["A half-truth", "A confident error", "Wisdom", "Balance"], 1, "'it yields a confident error'."), q("Balance is a virtue between what?", ["Any positions", "Reasonable positions", "Numbers", "People"], 1, "'a virtue between reasonable positions'.")]),
  ],
};

export const MORE_SPEAKING8 = {
  A1: [
    { text: "This is my school bag.", translation: "זה התיק שלי." },
    { text: "I want to play outside.", translation: "אני רוצה לשחק בחוץ." },
    { text: "Good night, see you tomorrow.", translation: "לילה טוב, נתראה מחר." },
  ],
  A2: [
    { text: "Excuse me, is this the right bus?", translation: "סליחה, זה האוטובוס הנכון?" },
    { text: "I made this gift myself.", translation: "הכנתי את המתנה הזו בעצמי." },
    { text: "Can you tell me when it's ready?", translation: "תוכל לומר לי מתי זה יהיה מוכן?" },
  ],
  B1: [
    { text: "I've started cooking proper meals for myself.", translation: "התחלתי לבשל לעצמי ארוחות אמיתיות." },
    { text: "I turned off most of my notifications last week.", translation: "כיביתי את רוב ההתראות שלי בשבוע שעבר." },
    { text: "Would you be willing to hear me out first?", translation: "תהיה מוכן לשמוע אותי עד הסוף קודם?" },
  ],
  B2: [
    { text: "I try to design my environment, not rely on willpower.", translation: "אני משתדל לעצב את הסביבה שלי, לא להסתמך על כוח רצון." },
    { text: "Let's not compare our drafts to other people's finished work.", translation: "בוא לא נשווה את הטיוטות שלנו לעבודה הגמורה של אחרים." },
    { text: "A little honest disagreement here would actually help.", translation: "קצת מחלוקת כנה כאן דווקא תעזור." },
  ],
  C1: [
    { text: "Let's be careful not to anchor on that first figure.", translation: "בוא ניזהר לא להיתפס למספר הראשון הזה." },
    { text: "I suspect we're seeing confirmation bias in this data.", translation: "אני חושד שאנחנו רואים כאן הטיית אישור בנתונים." },
    { text: "The small, repeated choices are what worry me most.", translation: "הבחירות הקטנות והחוזרות הן מה שמדאיג אותי יותר מכול." },
  ],
  C2: [
    { text: "We're treating deep uncertainty as if it were measurable risk.", translation: "אנחנו מתייחסים לאי-ודאות עמוקה כאילו הייתה סיכון מדיד." },
    { text: "With hindsight it looks inevitable, but it wasn't to them.", translation: "במבט לאחור זה נראה בלתי נמנע, אבל עבורם זה לא היה כך." },
    { text: "Splitting the difference here would just buy us a confident error.", translation: "פשרה כאן רק תקנה לנו טעות בטוחה בעצמה." },
  ],
};
