// Round 6 of additional Reading, Listening and Speaking content.
// Weighted to A1-B1, where comprehensible input matters most for learners
// and Hebrew glossing is reliable. Merged into the data set by the generator.

const R = (title, text, glossary, questions) => ({ title, text, glossary, questions });
const g = (word, partOfSpeech, definition, example, translation) => ({ word, partOfSpeech, definition, example, translation });
const q = (question, options, correctIndex, explanation) => ({ question, options, correctIndex, explanation });
const L = (transcript, questions) => ({ transcript, questions });

export const MORE_READINGS6 = {
  A1: [
    R("My Favourite Toy (הצעצוע האהוב עליי)",
      "I have a brown teddy bear. His name is Pip. He sleeps in my bed every night. When I am sad, I hug him. Pip is small, but he is my best friend.",
      [g("teddy bear", "noun", "דובון צעצוע", "A brown teddy bear.", "דובון"), g("hug", "verb", "לחבק", "I hug him.", "לחבק"), g("best", "adjective", "הכי טוב", "My best friend.", "הכי טוב")],
      [q("What is the toy's name?", ["Max", "Pip", "Sam", "Ben"], 1, "'His name is Pip'."), q("What does the child do when sad?", ["Cry", "Hug Pip", "Sleep", "Run"], 1, "'When I am sad, I hug him'.")]),
    R("At the Zoo (בגן החיות)",
      "Today we go to the zoo. I see a big lion and two monkeys. The monkeys jump and play. My little sister likes the elephant best. We eat lunch near the ducks.",
      [g("zoo", "noun", "גן חיות", "Go to the zoo.", "גן חיות"), g("lion", "noun", "אריה", "A big lion.", "אריה"), g("elephant", "noun", "פיל", "The big elephant.", "פיל")],
      [q("How many monkeys does the child see?", ["One", "Two", "Three", "Four"], 1, "'two monkeys'."), q("Which animal does the sister like best?", ["The lion", "The elephant", "The duck", "The monkey"], 1, "'likes the elephant best'.")]),
    R("Helping Mum Cook (עוזר לאמא לבשל)",
      "I help my mum in the kitchen. I wash the carrots and she cuts them. We make a big pot of soup. It smells very good. After dinner, I help to wash the plates.",
      [g("kitchen", "noun", "מטבח", "In the kitchen.", "מטבח"), g("wash", "verb", "לשטוף", "Wash the carrots.", "לשטוף"), g("soup", "noun", "מרק", "A pot of soup.", "מרק")],
      [q("What does the child wash first?", ["The plates", "The carrots", "The pot", "The table"], 1, "'I wash the carrots'."), q("What do they make?", ["Cake", "Soup", "Bread", "Salad"], 1, "'a big pot of soup'.")]),
    R("A Snowy Day (יום מושלג)",
      "It snowed last night. Everything is white! My brother and I put on warm coats and boots. We make a snowman with a carrot nose. Then we drink hot tea inside.",
      [g("snow", "verb", "לרדת שלג", "It snowed.", "לרדת שלג"), g("boots", "noun", "מגפיים", "Warm boots.", "מגפיים"), g("snowman", "noun", "איש שלג", "Make a snowman.", "איש שלג")],
      [q("What colour is everything?", ["Green", "White", "Blue", "Grey"], 1, "'Everything is white'."), q("What do they use for the nose?", ["A stone", "A carrot", "A stick", "A button"], 1, "'a snowman with a carrot nose'.")]),
    R("My New Shoes (הנעליים החדשות שלי)",
      "Mum bought me new shoes today. They are blue with white laces. They fit my feet just right. I want to run and jump in them. I will wear them to school tomorrow.",
      [g("shoes", "noun", "נעליים", "New shoes.", "נעליים"), g("laces", "noun", "שרוכים", "White laces.", "שרוכים"), g("fit", "verb", "להתאים (במידה)", "They fit me.", "להתאים")],
      [q("What colour are the shoes?", ["Red", "Blue", "Black", "Green"], 1, "'They are blue with white laces'."), q("When will the child wear them?", ["Today", "Tomorrow to school", "Never", "On Sunday"], 1, "'wear them to school tomorrow'.")]),
  ],
  A2: [
    R("Lost and Found (אבדות ומציאות)",
      "Yesterday I lost my phone at the train station. I was worried because all my photos are on it. I went back and asked at the office. A kind woman had found it and handed it in. I was so relieved.",
      [g("lost", "verb", "איבד", "I lost my phone.", "איבד"), g("worried", "adjective", "מודאג", "I was worried.", "מודאג"), g("relieved", "adjective", "מוקל, רגוע", "I felt relieved.", "מוקל/רגוע")],
      [q("Where did the writer lose the phone?", ["At home", "At the train station", "At school", "In a shop"], 1, "'I lost my phone at the train station'."), q("Why was the writer worried?", ["It was new", "All the photos are on it", "It was a gift", "It was expensive"], 1, "'all my photos are on it'.")]),
    R("The Farmers' Market (שוק האיכרים)",
      "Every Sunday morning a market opens in the square. Farmers sell fresh fruit, vegetables and honey. I like to taste the cheese before I buy. The food is not cheap, but it is much better than the supermarket.",
      [g("market", "noun", "שוק", "A busy market.", "שוק"), g("fresh", "adjective", "טרי", "Fresh fruit.", "טרי"), g("taste", "verb", "לטעום", "Taste the cheese.", "לטעום")],
      [q("When does the market open?", ["Every day", "Sunday morning", "Friday night", "Monday"], 1, "'Every Sunday morning'."), q("What does the writer like to do before buying?", ["Pay", "Taste the cheese", "Ask the price", "Smell the fruit"], 1, "'taste the cheese before I buy'.")]),
    R("My First Swimming Lesson (שיעור השחייה הראשון שלי)",
      "When I was a child, I was afraid of deep water. Last summer I finally took swimming lessons. At first I could only float near the wall. Now I can swim across the whole pool. I wish I had started sooner.",
      [g("afraid", "adjective", "מפחד", "Afraid of water.", "מפחד"), g("float", "verb", "לצוף", "Float on the water.", "לצוף"), g("pool", "noun", "בריכה", "Across the pool.", "בריכה")],
      [q("What was the writer afraid of?", ["Heights", "Deep water", "The dark", "Crowds"], 1, "'afraid of deep water'."), q("What can the writer do now?", ["Only float", "Swim across the whole pool", "Dive", "Teach others"], 1, "'I can swim across the whole pool'.")]),
    R("A Letter from Grandma (מכתב מסבתא)",
      "My grandmother does not use a computer, so she writes me letters by hand. Her writing is hard to read, but I love getting them. She tells me about her garden and her cat. I always write back the same week.",
      [g("by hand", "phrase", "בכתב יד", "Written by hand.", "בכתב יד"), g("garden", "noun", "גינה", "Her garden.", "גינה"), g("write back", "phrase", "לכתוב בחזרה, להשיב", "I write back.", "לכתוב בחזרה")],
      [q("Why does Grandma write by hand?", ["She likes pens", "She does not use a computer", "It is faster", "She has no phone"], 1, "'she does not use a computer'."), q("What does Grandma write about?", ["The news", "Her garden and her cat", "Money", "The weather"], 1, "'about her garden and her cat'.")]),
    R("Moving to a New Town (מעבר לעיר חדשה)",
      "Last month my family moved to a new town for my father's job. At first I missed my old friends very much. But my new neighbours are friendly, and I have already joined a football team. It is starting to feel like home.",
      [g("moved", "verb", "עבר דירה", "We moved.", "עבר (דירה)"), g("missed", "verb", "התגעגע", "I missed them.", "התגעגע"), g("neighbours", "noun", "שכנים", "Friendly neighbours.", "שכנים")],
      [q("Why did the family move?", ["For school", "For the father's job", "For the weather", "For family"], 1, "'for my father's job'."), q("What has the writer already joined?", ["A class", "A football team", "A club", "A choir"], 1, "'joined a football team'.")]),
  ],
  B1: [
    R("The Power of Small Habits (כוחם של הרגלים קטנים)",
      "I used to believe that change required dramatic effort. Then I tried reading just ten pages a day. It felt almost too small to matter, yet over a year it added up to fifteen books. Tiny habits, repeated, quietly reshape a life.",
      [g("dramatic", "adjective", "דרמטי, גדול", "Dramatic effort.", "דרמטי"), g("habit", "noun", "הרגל", "A daily habit.", "הרגל"), g("reshape", "verb", "לעצב מחדש", "Reshape a life.", "לעצב מחדש")],
      [q("What did the writer try?", ["Reading ten pages a day", "Writing a book", "A reading class", "Speed reading"], 1, "'reading just ten pages a day'."), q("What was the result over a year?", ["One book", "Fifteen books", "No change", "Five books"], 1, "'it added up to fifteen books'.")]),
    R("Why I Stopped Watching the News (למה הפסקתי לצפות בחדשות)",
      "For years I watched the news every evening, and it left me anxious and tired. I decided to read one good article a week instead. Surprisingly, I missed nothing important — friends still told me what mattered. I feel calmer and, oddly, better informed.",
      [g("anxious", "adjective", "חרד, מודאג", "It made me anxious.", "חרד"), g("instead", "adverb", "במקום זאת", "Read instead.", "במקום זאת"), g("informed", "adjective", "מעודכן, בקיא", "Well informed.", "מעודכן/בקיא")],
      [q("How did the daily news make the writer feel?", ["Calm", "Anxious and tired", "Happy", "Bored"], 1, "'left me anxious and tired'."), q("What did the writer do instead?", ["Stopped reading", "Read one good article a week", "Watched more", "Listened to radio"], 1, "'read one good article a week instead'.")]),
    R("A Garden on the Balcony (גינה במרפסת)",
      "I live in a small flat with no garden, but I refused to give up on growing things. I filled my balcony with pots of herbs and tomatoes. Caring for them each morning has become a calm ritual. A tiny space, it turns out, is enough.",
      [g("flat", "noun", "דירה", "A small flat.", "דירה"), g("herbs", "noun", "עשבי תיבול", "Pots of herbs.", "עשבי תיבול"), g("ritual", "noun", "טקס, מנהג קבוע", "A calm ritual.", "טקס/מנהג")],
      [q("What does the writer's home lack?", ["A balcony", "A garden", "Light", "Water"], 1, "'a small flat with no garden'."), q("What grows on the balcony?", ["Flowers only", "Herbs and tomatoes", "Trees", "Grass"], 1, "'pots of herbs and tomatoes'.")]),
    R("Volunteering at the Shelter (התנדבות במקלט)",
      "Every Saturday I volunteer at an animal shelter. I clean cages, feed the dogs and take them for walks. The work is tiring and sometimes sad, but watching a frightened animal learn to trust again is worth every minute.",
      [g("volunteer", "verb", "להתנדב", "I volunteer here.", "להתנדב"), g("shelter", "noun", "מקלט, מחסה", "An animal shelter.", "מקלט/מחסה"), g("trust", "verb", "לבטוח", "Learn to trust.", "לבטוח")],
      [q("How often does the writer volunteer?", ["Every day", "Every Saturday", "Once a month", "Rarely"], 1, "'Every Saturday'."), q("What makes the work worth it?", ["The pay", "Watching an animal learn to trust again", "The exercise", "Meeting people"], 1, "'learn to trust again is worth every minute'.")]),
    R("Fixing Things Together (מתקנים ביחד)",
      "In our town there is a 'repair café' where volunteers fix broken things for free. Instead of throwing away a toaster or a torn coat, you bring it and learn to mend it yourself. It saves money, reduces waste, and brings neighbours together.",
      [g("repair", "verb", "לתקן", "Repair the toaster.", "לתקן"), g("mend", "verb", "לתקן, לאחות", "Mend a coat.", "לתקן/לאחות"), g("waste", "noun", "פסולת, בזבוז", "Reduce waste.", "פסולת/בזבוז")],
      [q("What happens at the repair café?", ["Things are sold", "Volunteers fix broken things for free", "Coffee is served only", "New items are made"], 1, "'volunteers fix broken things for free'."), q("Name one benefit mentioned.", ["More shopping", "It reduces waste", "Faster service", "Free coffee"], 1, "'reduces waste, and brings neighbours together'.")]),
  ],
  B2: [
    R("The Comfort of Constraints (נחמת המגבלות)",
      "We tend to imagine that limitless freedom would unleash our creativity, yet the blank page is precisely what paralyses us. Constraints — a strict word count, a small budget, a single colour — narrow the field of choice and, in doing so, set the imagination free to work.",
      [g("unleash", "verb", "לשחרר, להתיר", "Unleash creativity.", "לשחרר"), g("paralyses", "verb", "משתק", "Fear paralyses us.", "משתק"), g("constraint", "noun", "מגבלה, אילוץ", "A useful constraint.", "מגבלה/אילוץ")],
      [q("What does the 'blank page' do, per the text?", ["Inspires us", "Paralyses us", "Frees us", "Nothing"], 1, "'the blank page is precisely what paralyses us'."), q("What do constraints do?", ["Limit creativity fully", "Narrow choice and free the imagination", "Waste time", "Add cost"], 1, "'set the imagination free to work'.")]),
    R("Reading Slowly in a Fast World (קריאה איטית בעולם מהיר)",
      "We have learned to skim — to harvest the gist of an article in seconds and move on. Something is lost in the rush. A difficult sentence, read slowly and even reread, can lodge in the mind for years, while a hundred skimmed ones evaporate by evening.",
      [g("skim", "verb", "לקרוא בדילוג, לרפרף", "Skim the text.", "לקרוא בדילוג/לרפרף"), g("gist", "noun", "תמצית, עיקר", "Get the gist.", "תמצית/עיקר"), g("evaporate", "verb", "להתאדות, להיעלם", "The ideas evaporate.", "להתאדות")],
      [q("What habit does the writer describe?", ["Deep reading", "Skimming for the gist", "Memorising", "Listening"], 1, "'We have learned to skim'."), q("What happens to a hundred skimmed sentences?", ["They stay", "They evaporate by evening", "They inspire us", "They are saved"], 1, "'a hundred skimmed ones evaporate by evening'.")]),
    R("Behind Every Breakthrough (מאחורי כל פריצת דרך)",
      "We love stories of solitary genius — the inventor in the garage, the artist in the attic. Yet look closely and you find a web of teachers, rivals, collaborators and lucky timing behind every breakthrough. Ideas are less a private spark than a social harvest.",
      [g("solitary", "adjective", "בודד, יחיד", "A solitary genius.", "בודד"), g("collaborator", "noun", "שותף ליצירה", "Many collaborators.", "שותף"), g("breakthrough", "noun", "פריצת דרך", "A great breakthrough.", "פריצת דרך")],
      [q("What myth does the text question?", ["Teamwork", "The lone genius", "Luck", "Hard work"], 1, "'We love stories of solitary genius'."), q("What lies behind breakthroughs, per the text?", ["A private spark only", "A web of people and timing", "Pure talent", "Money"], 1, "'a web of teachers, rivals, collaborators and lucky timing'.")]),
  ],
  C1: [
    R("When Numbers Distort the Truth (כשמספרים מעוותים את האמת)",
      "When a measure becomes a target, it ceases to be a good measure. Schools chase test scores, hospitals optimise waiting times, and the underlying goods — learning, health — quietly slip from view. What is counted comes to crowd out what actually counts.",
      [g("metric", "noun", "מדד, מדידה", "A misleading metric.", "מדד"), g("optimise", "verb", "למטב, לייעל", "Optimise the score.", "למטב/לייעל"), g("crowd out", "phrase", "לדחוק החוצה", "Crowd out quality.", "לדחוק החוצה")],
      [q("What happens when a measure becomes a target?", ["It improves", "It ceases to be a good measure", "It disappears", "Nothing"], 1, "'it ceases to be a good measure'."), q("What gets crowded out?", ["Numbers", "What actually counts", "Targets", "Reports"], 1, "'crowd out what actually counts'.")]),
    R("Negative Space (חלל שלילי)",
      "In painting, the empty area around a subject is called negative space, and skilled artists treat it as carefully as the subject itself. The principle travels well beyond art: the pause in a conversation, the white margin on a page, the unscheduled hour — absence is not the failure of presence but a form of it.",
      [g("negative space", "noun", "חלל שלילי (השטח הריק)", "Use the negative space.", "חלל שלילי"), g("margin", "noun", "שוליים", "The page margin.", "שוליים"), g("absence", "noun", "היעדר, חיסרון", "A meaningful absence.", "היעדר")],
      [q("What is 'negative space'?", ["The subject", "The empty area around a subject", "A frame", "A colour"], 1, "'the empty area around a subject'."), q("How does the writer reframe absence?", ["As failure", "As a form of presence", "As error", "As emptiness"], 1, "'absence is not the failure of presence but a form of it'.")]),
    R("The Half-Life of Facts (זמן מחצית החיים של עובדות)",
      "Much of what we confidently 'know' has an expiry date. Whole fields revise their certainties every generation, so the diet advice or medical rule we treat as settled may be quietly overturned within a decade. Holding knowledge a little more loosely is not ignorance; it is honesty about how learning actually works.",
      [g("expiry date", "noun", "תאריך תפוגה", "It has an expiry date.", "תאריך תפוגה"), g("certainty", "noun", "ודאות", "Revise our certainties.", "ודאות"), g("overturned", "verb", "נהפך, בוטל", "The rule was overturned.", "נהפך/בוטל")],
      [q("What does the writer say about much of what we 'know'?", ["It is permanent", "It has an expiry date", "It is useless", "It is secret"], 1, "'has an expiry date'."), q("Holding knowledge loosely is described as what?", ["Ignorance", "Honesty about how learning works", "Weakness", "Doubt"], 1, "'it is honesty about how learning actually works'.")]),
  ],
  C2: [
    R("Finding Beauty in Flaws (למצוא יופי בפגמים)",
      "Some traditions prize the cracked bowl over the flawless one, mending its fracture with gold so the wound becomes the most beautiful part. There is wisdom in this refusal of seamlessness: a life, like an object, earns its character precisely through the marks that a frictionless existence would never leave.",
      [g("flawless", "adjective", "מושלם, ללא פגם", "A flawless bowl.", "מושלם/ללא פגם"), g("fracture", "noun", "שבר, סדק", "Mend the fracture.", "שבר/סדק"), g("seamlessness", "noun", "חלקות, היעדר תפרים", "A refusal of seamlessness.", "חלקות/היעדר תפרים")],
      [q("How is the cracked bowl's fracture treated?", ["Hidden", "Mended with gold", "Discarded", "Painted over"], 1, "'mending its fracture with gold'."), q("How does a life earn its character, per the text?", ["Through perfection", "Through the marks a frictionless existence would not leave", "Through wealth", "Through ease"], 1, "'the marks that a frictionless existence would never leave'.")]),
    R("Against the Cult of Originality (נגד פולחן המקוריות)",
      "We demand that art be original, as though novelty were the highest virtue, yet most enduring work is openly indebted — a reworking, a reply, a variation on an inherited theme. Originality, rightly understood, is not the absence of influence but the digestion of it: the old material made unmistakably one's own.",
      [g("novelty", "noun", "חידוש, חדשנות", "The cult of novelty.", "חידוש/חדשנות"), g("indebted", "adjective", "חב חוב, אסיר תודה", "Openly indebted.", "חב חוב"), g("digestion", "noun", "עיכול, הטמעה", "The digestion of influence.", "עיכול/הטמעה")],
      [q("What does the writer say about most enduring work?", ["It is wholly new", "It is openly indebted", "It is forgotten", "It is original"], 1, "'most enduring work is openly indebted'."), q("How is originality redefined?", ["Absence of influence", "The digestion of influence", "Pure novelty", "Imitation"], 1, "'not the absence of influence but the digestion of it'.")]),
    R("The Seduction of the Definitive (פיתוי הנחרצות)",
      "A confident, sweeping verdict is intoxicating both to deliver and to receive; it spares everyone the discomfort of doubt. But the world rarely yields to such tidiness, and the thinker who insists on a clean answer often does so by quietly amputating the parts of reality that refuse to fit.",
      [g("verdict", "noun", "פסק דין, הכרעה", "A sweeping verdict.", "פסק דין/הכרעה"), g("intoxicating", "adjective", "משכר, מסחרר", "An intoxicating idea.", "משכר/מסחרר"), g("amputating", "verb", "קוטע, כורת", "Amputating the facts.", "קוטע/כורת")],
      [q("Why is a definitive verdict 'intoxicating'?", ["It is correct", "It spares everyone the discomfort of doubt", "It is rare", "It is long"], 1, "'it spares everyone the discomfort of doubt'."), q("How does the thinker achieve a 'clean answer'?", ["By research", "By amputating parts of reality that don't fit", "By asking others", "By waiting"], 1, "'quietly amputating the parts of reality that refuse to fit'.")]),
  ],
};

export const MORE_LISTENINGS6 = {
  A1: [
    L("Hi! I am Tom. I have a little dog. His name is Spot. He is black and white. We play in the garden every day.",
      [q("What is the dog's name?", ["Tom", "Spot", "Max", "Rex"], 1, "'His name is Spot'."), q("Where do they play?", ["In the park", "In the garden", "At school", "On the street"], 1, "'We play in the garden every day'.")]),
    L("Good morning, class. Today is Monday. Please open your books to page ten. We will read a short story together.",
      [q("What day is it?", ["Sunday", "Monday", "Friday", "Tuesday"], 1, "'Today is Monday'."), q("What page should they open?", ["Page two", "Page ten", "Page twenty", "Page five"], 1, "'open your books to page ten'.")]),
    L("Here is your ice cream. We have three flavours: chocolate, banana and lemon. Which one would you like today?",
      [q("How many flavours are there?", ["Two", "Three", "Four", "Five"], 1, "'We have three flavours'."), q("Which flavour is NOT listed?", ["Chocolate", "Banana", "Lemon", "Apple"], 3, "The flavours are chocolate, banana and lemon.")]),
    L("It is time for bed. Brush your teeth and put on your pyjamas. I will read you one story, and then we sleep.",
      [q("What should the child do first?", ["Sleep", "Brush teeth and put on pyjamas", "Eat", "Play"], 1, "'Brush your teeth and put on your pyjamas'."), q("How many stories will be read?", ["One", "Two", "Three", "None"], 0, "'I will read you one story'.")]),
    L("Welcome to the park! The gate closes at six o'clock. Please do not feed the birds. Have a nice day!",
      [q("When does the gate close?", ["At five", "At six", "At seven", "At eight"], 1, "'The gate closes at six o'clock'."), q("What should visitors NOT do?", ["Walk", "Feed the birds", "Sit", "Talk"], 1, "'do not feed the birds'.")]),
  ],
  A2: [
    L("Attention shoppers: the supermarket will close in fifteen minutes. Please bring your items to the checkout now. Thank you for shopping with us.",
      [q("When will the shop close?", ["In five minutes", "In fifteen minutes", "In an hour", "Now"], 1, "'close in fifteen minutes'."), q("What should shoppers do?", ["Leave", "Bring items to the checkout", "Wait", "Call staff"], 1, "'bring your items to the checkout now'.")]),
    L("Hello, this is Dr Levi's office. Your appointment is on Thursday at three o'clock. Please arrive ten minutes early to fill in a form.",
      [q("When is the appointment?", ["Thursday at three", "Friday at two", "Monday at one", "Thursday at one"], 0, "'Thursday at three o'clock'."), q("Why arrive early?", ["To pay", "To fill in a form", "To wait", "To park"], 1, "'arrive ten minutes early to fill in a form'.")]),
    L("Welcome aboard the train to the city centre. The next stop is Market Street. Mind the gap when you leave the train.",
      [q("Where is the train going?", ["The airport", "The city centre", "The beach", "The hills"], 1, "'the train to the city centre'."), q("What is the next stop?", ["Main Road", "Market Street", "Park Lane", "City Hall"], 1, "'The next stop is Market Street'.")]),
    L("Thanks for calling the cinema. Tonight's film starts at eight. Tickets are ten dollars, but students pay only six with a card.",
      [q("When does the film start?", ["At six", "At eight", "At ten", "At nine"], 1, "'starts at eight'."), q("How much do students pay?", ["Ten dollars", "Six dollars", "Eight dollars", "Free"], 1, "'students pay only six with a card'.")]),
    L("Good afternoon. Because of the storm, today's outdoor concert has been moved inside to the main hall. Your tickets are still valid.",
      [q("Why was the concert moved?", ["Too many people", "Because of the storm", "A holiday", "No reason"], 1, "'Because of the storm'."), q("Where is it now?", ["Cancelled", "Inside, in the main hall", "Another city", "Online"], 1, "'moved inside to the main hall'.")]),
  ],
  B1: [
    L("Thank you all for coming to the volunteer meeting. This Saturday we are cleaning the river path. Please wear old clothes and bring gloves. We start at nine and finish by noon.",
      [q("What is the task this Saturday?", ["Planting trees", "Cleaning the river path", "Painting", "Building"], 1, "'we are cleaning the river path'."), q("What should volunteers bring?", ["Food", "Gloves", "Money", "Tools"], 1, "'bring gloves'.")]),
    L("This is a reminder that the library now offers free online courses. You can learn a language or a new skill from home. Just sign in with your library card.",
      [q("What does the library now offer?", ["Free books only", "Free online courses", "A café", "Printing"], 1, "'free online courses'."), q("What do you need to sign in?", ["An email", "Your library card", "A password only", "Money"], 1, "'sign in with your library card'.")]),
    L("Welcome to the museum tour. Photography is allowed, but please do not use flash. The tour lasts about an hour and ends in the gift shop.",
      [q("What is not allowed?", ["Photos", "Flash", "Talking", "Walking"], 1, "'please do not use flash'."), q("Where does the tour end?", ["The entrance", "The gift shop", "The café", "Outside"], 1, "'ends in the gift shop'.")]),
    L("Good evening. Due to maintenance, the lifts will be out of service tomorrow morning. We apologise for the inconvenience and recommend using the stairs.",
      [q("Why will the lifts be out of service?", ["A power cut", "Maintenance", "An accident", "A holiday"], 1, "'Due to maintenance'."), q("What is recommended?", ["Stay home", "Using the stairs", "Waiting", "Calling staff"], 1, "'recommend using the stairs'.")]),
    L("Hi, this is the bike shop. Your repair is ready to collect. The bill comes to forty dollars. We are open until six today and closed on Sunday.",
      [q("What is ready?", ["A new bike", "The repair", "A part", "An order"], 1, "'Your repair is ready to collect'."), q("When is the shop closed?", ["Saturday", "Sunday", "Monday", "Never"], 1, "'closed on Sunday'.")]),
  ],
  B2: [
    L("In today's segment we look at 'planned obsolescence' — the practice of designing products to fail or feel outdated quickly. Critics argue it wastes resources, while companies claim it funds innovation. The truth, as usual, sits somewhere in between.",
      [q("What is 'planned obsolescence'?", ["A repair method", "Designing products to fail or feel outdated quickly", "A sales tax", "A warranty"], 1, "'designing products to fail or feel outdated quickly'."), q("What do companies claim it does?", ["Saves the planet", "Funds innovation", "Lowers prices", "Nothing"], 1, "'companies claim it funds innovation'.")]),
    L("Researchers studying happiness keep returning to one finding: beyond a modest income, more money adds surprisingly little. What predicts wellbeing far better is the quality of our relationships and a sense of purpose.",
      [q("What adds little beyond a modest income?", ["Friends", "More money", "Health", "Time"], 1, "'beyond a modest income, more money adds surprisingly little'."), q("What predicts wellbeing better?", ["Wealth", "Relationships and a sense of purpose", "Fame", "Travel"], 1, "'the quality of our relationships and a sense of purpose'.")]),
    L("A quick note on feedback: vague praise feels nice but teaches nothing. Specific, timely comments — what worked, what to change, and why — are far more useful, even when they are harder to hear.",
      [q("What is the problem with vague praise?", ["It is rude", "It teaches nothing", "It is rare", "It is slow"], 1, "'vague praise feels nice but teaches nothing'."), q("What kind of feedback is more useful?", ["General", "Specific and timely", "Delayed", "Positive only"], 1, "'Specific, timely comments... are far more useful'.")]),
  ],
  C1: [
    L("Economists speak of 'opportunity cost' — the value of the road not taken. Every yes is also a no to everything else you might have done with that time or money. Seen this way, the real price of a choice is rarely the one on the label.",
      [q("What is 'opportunity cost'?", ["A tax", "The value of the road not taken", "A discount", "A fee"], 1, "'the value of the road not taken'."), q("What is the 'real price' of a choice?", ["The label price", "Rarely the one on the label", "Always zero", "Fixed"], 1, "'the real price of a choice is rarely the one on the label'.")]),
    L("There's a cognitive trap called survivorship bias. We study the companies that thrived, the bombers that returned, and draw lessons — forgetting that the failures, the planes that never came back, can no longer tell their side of the story.",
      [q("What does survivorship bias make us study?", ["Failures", "Only those that thrived or returned", "Everything", "Random cases"], 1, "'the companies that thrived, the bombers that returned'."), q("What is forgotten?", ["The winners", "The failures that can't tell their side", "The data", "The method"], 1, "'the failures... can no longer tell their side of the story'.")]),
    L("Consider the 'curse of knowledge': once we understand something deeply, it becomes almost impossible to imagine not knowing it. This is why experts often make poor teachers — they have forgotten what confusion felt like.",
      [q("What is the 'curse of knowledge'?", ["Forgetting facts", "Being unable to imagine not knowing something", "Knowing too little", "Lying"], 1, "'impossible to imagine not knowing it'."), q("Why can experts make poor teachers?", ["They are lazy", "They forgot what confusion felt like", "They are busy", "They dislike students"], 1, "'they have forgotten what confusion felt like'.")]),
  ],
  C2: [
    L("Philosophers distinguish between the map and the territory. Our models, however elegant, are not the reality they describe; trouble begins when we grow so attached to the map that we start correcting the landscape to match it.",
      [q("What is the distinction drawn?", ["Right and wrong", "The map and the territory", "Past and future", "Cause and effect"], 1, "'between the map and the territory'."), q("When does trouble begin?", ["When maps are accurate", "When we correct the landscape to match the map", "When we lose the map", "Never"], 1, "'correcting the landscape to match it'.")]),
    L("There is a paradox in tolerance: a society that tolerates everything, including the intolerant who would dismantle tolerance itself, may not survive to remain tolerant. Some boundaries, it seems, are the price of openness rather than its betrayal.",
      [q("What is the 'paradox of tolerance'?", ["Tolerance is easy", "Tolerating the intolerant may end tolerance", "Tolerance is rare", "Tolerance is fake"], 1, "'tolerates everything, including the intolerant... may not survive'."), q("How are some boundaries described?", ["A betrayal of openness", "The price of openness", "Useless", "Cruel"], 1, "'the price of openness rather than its betrayal'.")]),
    L("Note the difference between precision and accuracy. A clock that is exactly seven minutes fast is precise yet inaccurate; it tells the wrong time with admirable consistency. Much confident analysis fails in just this way — rigorous, repeatable, and reliably aimed at the wrong target.",
      [q("How is the seven-minutes-fast clock described?", ["Accurate but imprecise", "Precise yet inaccurate", "Both", "Neither"], 1, "'precise yet inaccurate'."), q("How does much confident analysis fail?", ["It is random", "Rigorous yet aimed at the wrong target", "It is slow", "It is honest"], 1, "'reliably aimed at the wrong target'.")]),
  ],
};

export const MORE_SPEAKING6 = {
  A1: [
    { text: "I have a little brother.", translation: "יש לי אח קטן." },
    { text: "Where is the bathroom, please?", translation: "איפה השירותים, בבקשה?" },
    { text: "I like cheese and bread.", translation: "אני אוהב גבינה ולחם." },
  ],
  A2: [
    { text: "I lost my keys this morning.", translation: "איבדתי את המפתחות שלי הבוקר." },
    { text: "How much does this cost?", translation: "כמה זה עולה?" },
    { text: "Could you help me carry this?", translation: "תוכל לעזור לי לסחוב את זה?" },
  ],
  B1: [
    { text: "I've been trying to read more lately.", translation: "אני מנסה לקרוא יותר לאחרונה." },
    { text: "Would it be possible to change the date?", translation: "האם יהיה אפשר לשנות את התאריך?" },
    { text: "I think we should hear everyone's opinion first.", translation: "אני חושב שכדאי לשמוע קודם את דעת כולם." },
  ],
  B2: [
    { text: "I take your point, but I'd weigh the costs differently.", translation: "אני מקבל את הטענה שלך, אבל הייתי שוקל את העלויות אחרת." },
    { text: "Let's separate what we know from what we're assuming.", translation: "בוא נפריד בין מה שאנחנו יודעים לבין מה שאנחנו מניחים." },
    { text: "Could we revisit this once we have the figures?", translation: "נוכל לחזור לזה ברגע שיהיו לנו הנתונים?" },
  ],
  C1: [
    { text: "I'd frame the trade-off slightly differently.", translation: "הייתי מנסח את ההתלבטות מעט אחרת." },
    { text: "That holds in theory, but the practice is messier.", translation: "זה נכון בתיאוריה, אבל בפועל זה מורכב יותר." },
    { text: "Let's not optimise for the easily measured.", translation: "בוא לא נמטב את מה שקל למדוד." },
  ],
  C2: [
    { text: "I'd hesitate to treat correlation as if it settled the matter.", translation: "הייתי נמנע מלהתייחס למתאם כאילו הוא מכריע את העניין." },
    { text: "We may be answering a sharper version of the wrong question.", translation: "ייתכן שאנחנו עונים על גרסה חדה יותר של השאלה הלא נכונה." },
    { text: "The elegance of the argument is doing a lot of quiet work here.", translation: "האלגנטיות של הטיעון עושה כאן לא מעט עבודה שקטה." },
  ],
};
