// Round 10 — additional content words, none of which appear in rounds 1–9 or
// the base banks. Every entry carries its own Hebrew example sentence
// (`exampleHe`), so the generator needs no lookup in example-he.mjs.

export const MORE_WORDS10 = {
  A1: [
    { word: "breakfast", partOfSpeech: "noun", definition: "הארוחה הראשונה של היום", example: "I eat breakfast at seven.", exampleHe: "אני אוכל ארוחת בוקר בשבע.", translation: "ארוחת בוקר" },
    { word: "lunch", partOfSpeech: "noun", definition: "הארוחה של אמצע היום", example: "We eat lunch at school.", exampleHe: "אנחנו אוכלים ארוחת צהריים בבית הספר.", translation: "ארוחת צהריים" },
    { word: "dinner", partOfSpeech: "noun", definition: "הארוחה של הערב", example: "My family eats dinner together.", exampleHe: "המשפחה שלי אוכלת ארוחת ערב ביחד.", translation: "ארוחת ערב" },
    { word: "umbrella", partOfSpeech: "noun", definition: "מה שפותחים כשיורד גשם", example: "Take an umbrella today.", exampleHe: "קח מטרייה היום.", translation: "מטרייה" },
    { word: "market", partOfSpeech: "noun", definition: "מקום פתוח שבו קונים אוכל", example: "We buy fruit at the market.", exampleHe: "אנחנו קונים פירות בשוק.", translation: "שוק" },
    { word: "taxi", partOfSpeech: "noun", definition: "מכונית ששוכרים לנסיעה", example: "I take a taxi to the airport.", exampleHe: "אני לוקח מונית לשדה התעופה.", translation: "מונית" },
    { word: "ship", partOfSpeech: "noun", definition: "כלי גדול שנוסע בים", example: "The ship is very big.", exampleHe: "הספינה מאוד גדולה.", translation: "ספינה" },
    { word: "island", partOfSpeech: "noun", definition: "יבשה קטנה שמוקפת במים", example: "We go to a small island.", exampleHe: "אנחנו נוסעים לאי קטן.", translation: "אי" },
    { word: "guitar", partOfSpeech: "noun", definition: "כלי נגינה עם מיתרים", example: "My brother plays the guitar.", exampleHe: "אחי מנגן בגיטרה.", translation: "גיטרה" },
    { word: "paper", partOfSpeech: "noun", definition: "החומר שכותבים עליו", example: "I write on white paper.", exampleHe: "אני כותב על נייר לבן.", translation: "נייר" },
    { word: "office", partOfSpeech: "noun", definition: "מקום שבו אנשים עובדים", example: "My mother works in an office.", exampleHe: "אמא שלי עובדת במשרד.", translation: "משרד" },
    { word: "nurse", partOfSpeech: "noun", definition: "מי שמטפל בחולים בבית חולים", example: "The nurse is very kind.", exampleHe: "האחות מאוד נחמדה.", translation: "אח/אחות" },
    { word: "dark", partOfSpeech: "adjective", definition: "בלי אור", example: "The room is dark at night.", exampleHe: "החדר חשוך בלילה.", translation: "חשוך" },
    { word: "easy", partOfSpeech: "adjective", definition: "לא קשה", example: "This game is easy.", exampleHe: "המשחק הזה קל.", translation: "קל" },
    { word: "heart", partOfSpeech: "noun", definition: "האיבר שמזיז את הדם בגוף", example: "My heart is strong.", exampleHe: "הלב שלי חזק.", translation: "לב" },
    { word: "seat", partOfSpeech: "noun", definition: "מקום לשבת בו", example: "This seat is free.", exampleHe: "המושב הזה פנוי.", translation: "מושב" },
    { word: "wet", partOfSpeech: "adjective", definition: "מלא מים", example: "My shoes are wet.", exampleHe: "הנעליים שלי רטובות.", translation: "רטוב" },
    { word: "dry", partOfSpeech: "adjective", definition: "בלי מים", example: "The towel is dry.", exampleHe: "המגבת יבשה.", translation: "יבש" },
    { word: "thin", partOfSpeech: "adjective", definition: "לא עבה", example: "This book is thin.", exampleHe: "הספר הזה דק.", translation: "דק" },
    { word: "world", partOfSpeech: "noun", definition: "כל כדור הארץ", example: "The world is big.", exampleHe: "העולם גדול.", translation: "עולם" },
    { word: "wood", partOfSpeech: "noun", definition: "החומר שמגיע מעצים", example: "The table is made of wood.", exampleHe: "השולחן עשוי מעץ.", translation: "עץ (חומר)" },
    { word: "storm", partOfSpeech: "noun", definition: "מזג אוויר עם רוח וגשם חזקים", example: "A storm is coming.", exampleHe: "סערה מגיעה.", translation: "סערה" },
    { word: "wheel", partOfSpeech: "noun", definition: "החלק העגול שמסובב מכונית", example: "The car has four wheels.", exampleHe: "למכונית יש ארבעה גלגלים.", translation: "גלגל" },
    { word: "clothes", partOfSpeech: "noun", definition: "מה שלובשים על הגוף", example: "I wash my clothes.", exampleHe: "אני מכבס את הבגדים שלי.", translation: "בגדים" },
    { word: "coffee", partOfSpeech: "noun", definition: "משקה חם שחור", example: "She drinks coffee in the morning.", exampleHe: "היא שותה קפה בבוקר.", translation: "קפה" },
  ],
  A2: [
    { word: "adventure", partOfSpeech: "noun", definition: "חוויה מרגשת ולא רגילה", example: "The trip was a real adventure.", exampleHe: "הטיול היה הרפתקה אמיתית.", translation: "הרפתקה" },
    { word: "allergy", partOfSpeech: "noun", definition: "תגובה של הגוף למשהו מסוים", example: "I have an allergy to nuts.", exampleHe: "יש לי אלרגיה לאגוזים.", translation: "אלרגיה" },
    { word: "ambulance", partOfSpeech: "noun", definition: "רכב שמסיע חולים לבית חולים", example: "The ambulance arrived quickly.", exampleHe: "האמבולנס הגיע מהר.", translation: "אמבולנס" },
    { word: "apartment", partOfSpeech: "noun", definition: "דירה בתוך בניין", example: "They rent a small apartment.", exampleHe: "הם שוכרים דירה קטנה.", translation: "דירה" },
    { word: "battery", partOfSpeech: "noun", definition: "מה שנותן חשמל למכשיר", example: "My phone battery is empty.", exampleHe: "הסוללה של הטלפון שלי ריקה.", translation: "סוללה" },
    { word: "bench", partOfSpeech: "noun", definition: "ספסל לישיבה בחוץ", example: "We sat on a bench in the park.", exampleHe: "ישבנו על ספסל בפארק.", translation: "ספסל" },
    { word: "breathe", partOfSpeech: "verb", definition: "להכניס ולהוציא אוויר", example: "Breathe slowly and relax.", exampleHe: "תנשום לאט ותירגע.", translation: "לנשום" },
    { word: "cash", partOfSpeech: "noun", definition: "כסף מזומן, לא כרטיס", example: "I paid in cash.", exampleHe: "שילמתי במזומן.", translation: "מזומן" },
    { word: "chance", partOfSpeech: "noun", definition: "הזדמנות או סיכוי", example: "Give me one more chance.", exampleHe: "תן לי עוד הזדמנות אחת.", translation: "הזדמנות" },
    { word: "chef", partOfSpeech: "noun", definition: "טבח מקצועי במסעדה", example: "The chef cooked a great meal.", exampleHe: "השף בישל ארוחה מצוינת.", translation: "שף" },
    { word: "chore", partOfSpeech: "noun", definition: "מטלה קבועה בבית", example: "Washing dishes is my chore.", exampleHe: "שטיפת כלים היא המטלה שלי.", translation: "מטלת בית" },
    { word: "coast", partOfSpeech: "noun", definition: "האזור שבו היבשה פוגשת את הים", example: "We drove along the coast.", exampleHe: "נסענו לאורך החוף.", translation: "חוף" },
    { word: "colleague", partOfSpeech: "noun", definition: "מישהו שעובד איתך", example: "My colleague helped me today.", exampleHe: "העמית שלי לעבודה עזר לי היום.", translation: "עמית לעבודה" },
    { word: "comfort", partOfSpeech: "noun", definition: "תחושה נעימה ורגועה", example: "I like the comfort of home.", exampleHe: "אני אוהב את הנוחות של הבית.", translation: "נוחות" },
    { word: "concert", partOfSpeech: "noun", definition: "הופעה של מוזיקה", example: "We went to a concert last night.", exampleHe: "הלכנו להופעה אתמול בערב.", translation: "הופעה" },
    { word: "confuse", partOfSpeech: "verb", definition: "לגרום למישהו לא להבין", example: "These rules confuse me.", exampleHe: "הכללים האלה מבלבלים אותי.", translation: "לבלבל" },
    { word: "cough", partOfSpeech: "verb", definition: "להוציא אוויר בכוח מהגרון", example: "I cough when I am sick.", exampleHe: "אני משתעל כשאני חולה.", translation: "להשתעל" },
    { word: "courage", partOfSpeech: "noun", definition: "היכולת לעשות משהו למרות הפחד", example: "It takes courage to speak up.", exampleHe: "צריך אומץ כדי לדבר בגלוי.", translation: "אומץ" },
    { word: "cupboard", partOfSpeech: "noun", definition: "ארון שמאחסנים בו כלים או אוכל", example: "The plates are in the cupboard.", exampleHe: "הצלחות בארון המטבח.", translation: "ארון מטבח" },
    { word: "curtain", partOfSpeech: "noun", definition: "בד שמכסה חלון", example: "Please close the curtain.", exampleHe: "בבקשה תסגור את הווילון.", translation: "וילון" },
    { word: "damage", partOfSpeech: "noun", definition: "נזק שנגרם למשהו", example: "The storm caused a lot of damage.", exampleHe: "הסערה גרמה להרבה נזק.", translation: "נזק" },
    { word: "deadline", partOfSpeech: "noun", definition: "המועד האחרון להגיש משהו", example: "The deadline is on Friday.", exampleHe: "המועד האחרון הוא ביום שישי.", translation: "מועד אחרון" },
    { word: "dentist", partOfSpeech: "noun", definition: "רופא שמטפל בשיניים", example: "I visit the dentist twice a year.", exampleHe: "אני מבקר אצל רופא השיניים פעמיים בשנה.", translation: "רופא שיניים" },
    { word: "dessert", partOfSpeech: "noun", definition: "מנה מתוקה בסוף הארוחה", example: "We had ice cream for dessert.", exampleHe: "אכלנו גלידה לקינוח.", translation: "קינוח" },
    { word: "diary", partOfSpeech: "noun", definition: "מחברת שכותבים בה מה קרה כל יום", example: "She writes in her diary every night.", exampleHe: "היא כותבת ביומן שלה כל לילה.", translation: "יומן" },
  ],
  B1: [
    { word: "accurate", partOfSpeech: "adjective", definition: "מדויק, בלי טעויות", example: "His report was accurate.", exampleHe: "הדוח שלו היה מדויק.", translation: "מדויק" },
    { word: "alternative", partOfSpeech: "noun", definition: "אפשרות אחרת לבחירה", example: "We need an alternative to this plan.", exampleHe: "אנחנו צריכים חלופה לתוכנית הזאת.", translation: "חלופה" },
    { word: "ambition", partOfSpeech: "noun", definition: "שאיפה חזקה להשיג משהו", example: "Her ambition is to be a doctor.", exampleHe: "השאיפה שלה היא להיות רופאה.", translation: "שאיפה" },
    { word: "appearance", partOfSpeech: "noun", definition: "איך משהו או מישהו נראה", example: "Do not judge by appearance.", exampleHe: "אל תשפוט לפי המראה החיצוני.", translation: "מראה חיצוני" },
    { word: "bargain", partOfSpeech: "noun", definition: "קנייה זולה במיוחד", example: "This coat was a real bargain.", exampleHe: "המעיל הזה היה מציאה אמיתית.", translation: "מציאה" },
    { word: "category", partOfSpeech: "noun", definition: "קבוצה של דברים דומים", example: "This book belongs in another category.", exampleHe: "הספר הזה שייך לקטגוריה אחרת.", translation: "קטגוריה" },
    { word: "commitment", partOfSpeech: "noun", definition: "התחייבות רצינית למשהו", example: "Marriage is a big commitment.", exampleHe: "נישואים הם מחויבות גדולה.", translation: "מחויבות" },
    { word: "community", partOfSpeech: "noun", definition: "קבוצת אנשים שחיים או פועלים יחד", example: "The whole community helped.", exampleHe: "כל הקהילה עזרה.", translation: "קהילה" },
    { word: "compromise", partOfSpeech: "noun", definition: "הסכמה שבה כל צד מוותר קצת", example: "We reached a compromise.", exampleHe: "הגענו לפשרה.", translation: "פשרה" },
    { word: "concentrate", partOfSpeech: "verb", definition: "לרכז את כל תשומת הלב", example: "I cannot concentrate with music.", exampleHe: "אני לא מצליח להתרכז עם מוזיקה.", translation: "להתרכז" },
    { word: "consumer", partOfSpeech: "noun", definition: "מי שקונה מוצרים ושירותים", example: "The consumer has rights.", exampleHe: "לצרכן יש זכויות.", translation: "צרכן" },
    { word: "contract", partOfSpeech: "noun", definition: "הסכם כתוב ומחייב", example: "Read the contract before you sign.", exampleHe: "קרא את החוזה לפני שאתה חותם.", translation: "חוזה" },
    { word: "contrast", partOfSpeech: "noun", definition: "הבדל בולט בין שני דברים", example: "There is a sharp contrast between them.", exampleHe: "יש ניגוד חד ביניהם.", translation: "ניגוד" },
    { word: "convenient", partOfSpeech: "adjective", definition: "נוח ומתאים למצב", example: "Is this time convenient for you?", exampleHe: "השעה הזאת נוחה לך?", translation: "נוח" },
    { word: "cooperate", partOfSpeech: "verb", definition: "לעבוד יחד עם אחרים", example: "The teams cooperate well.", exampleHe: "הצוותים משתפים פעולה היטב.", translation: "לשתף פעולה" },
    { word: "criticize", partOfSpeech: "verb", definition: "לומר מה לא טוב במשהו", example: "Do not criticize without helping.", exampleHe: "אל תבקר בלי לעזור.", translation: "לבקר" },
    { word: "destination", partOfSpeech: "noun", definition: "המקום שאליו נוסעים", example: "Our destination is Rome.", exampleHe: "היעד שלנו הוא רומא.", translation: "יעד" },
    { word: "discipline", partOfSpeech: "noun", definition: "יכולת לפעול לפי כללים בעקביות", example: "Learning a language needs discipline.", exampleHe: "לימוד שפה דורש משמעת.", translation: "משמעת" },
    { word: "distinguish", partOfSpeech: "verb", definition: "להבחין בין דברים דומים", example: "I cannot distinguish the two sounds.", exampleHe: "אני לא מצליח להבחין בין שני הצלילים.", translation: "להבחין" },
    { word: "efficiency", partOfSpeech: "noun", definition: "עשייה טובה בפחות זמן ומשאבים", example: "The new system improved efficiency.", exampleHe: "המערכת החדשה שיפרה את היעילות.", translation: "יעילות" },
    { word: "eliminate", partOfSpeech: "verb", definition: "להוציא או לסלק לגמרי", example: "We must eliminate the errors.", exampleHe: "עלינו לסלק את הטעויות.", translation: "לסלק" },
    { word: "enthusiasm", partOfSpeech: "noun", definition: "התרגשות ורצון גדול לעשות משהו", example: "She spoke with enthusiasm.", exampleHe: "היא דיברה בהתלהבות.", translation: "התלהבות" },
    { word: "equipment", partOfSpeech: "noun", definition: "הכלים הדרושים לפעילות", example: "The equipment is in the car.", exampleHe: "הציוד נמצא במכונית.", translation: "ציוד" },
    { word: "eventually", partOfSpeech: "adverb", definition: "בסוף, אחרי זמן מה", example: "He eventually agreed.", exampleHe: "בסופו של דבר הוא הסכים.", translation: "בסופו של דבר" },
    { word: "exhausted", partOfSpeech: "adjective", definition: "עייף מאוד, בלי כוח", example: "I was exhausted after the trip.", exampleHe: "הייתי מותש אחרי הטיול.", translation: "מותש" },
  ],
  B2: [
    { word: "aspiration", partOfSpeech: "noun", definition: "שאיפה ארוכת טווח", example: "Her aspiration is to lead the team.", exampleHe: "השאיפה שלה היא להוביל את הצוות.", translation: "שאיפה" },
    { word: "benchmark", partOfSpeech: "noun", definition: "אמת מידה להשוואה", example: "This result is the new benchmark.", exampleHe: "התוצאה הזאת היא אמת המידה החדשה.", translation: "אמת מידה" },
    { word: "breach", partOfSpeech: "noun", definition: "הפרה של כלל או הסכם", example: "That is a breach of contract.", exampleHe: "זו הפרה של החוזה.", translation: "הפרה" },
    { word: "catalyst", partOfSpeech: "noun", definition: "גורם שמאיץ שינוי", example: "The report was a catalyst for change.", exampleHe: "הדוח היה זרז לשינוי.", translation: "זרז" },
    { word: "collaborate", partOfSpeech: "verb", definition: "לעבוד יחד על מטרה משותפת", example: "The two labs collaborate closely.", exampleHe: "שתי המעבדות משתפות פעולה באופן הדוק.", translation: "לשתף פעולה" },
    { word: "commence", partOfSpeech: "verb", definition: "להתחיל (במשלב רשמי)", example: "The trial will commence in May.", exampleHe: "המשפט יתחיל במאי.", translation: "להתחיל" },
    { word: "conceal", partOfSpeech: "verb", definition: "להסתיר מעיני אחרים", example: "He tried to conceal his surprise.", exampleHe: "הוא ניסה להסתיר את הפתעתו.", translation: "להסתיר" },
    { word: "conclusive", partOfSpeech: "adjective", definition: "מכריע, שאין עליו עוררין", example: "The evidence is not conclusive.", exampleHe: "הראיות אינן חד-משמעיות.", translation: "חד-משמעי" },
    { word: "condense", partOfSpeech: "verb", definition: "לקצר ולתמצת", example: "Condense the report to one page.", exampleHe: "תמצת את הדוח לעמוד אחד.", translation: "לתמצת" },
    { word: "counterpart", partOfSpeech: "noun", definition: "מי שממלא תפקיד מקביל", example: "She met her French counterpart.", exampleHe: "היא נפגשה עם עמיתה הצרפתי.", translation: "מקביל בתפקיד" },
    { word: "cultivate", partOfSpeech: "verb", definition: "לטפח ולפתח לאורך זמן", example: "You should cultivate good habits.", exampleHe: "כדאי לטפח הרגלים טובים.", translation: "לטפח" },
    { word: "curb", partOfSpeech: "verb", definition: "לרסן, להגביל", example: "The city wants to curb traffic.", exampleHe: "העירייה רוצה לרסן את התנועה.", translation: "לרסן" },
    { word: "deficiency", partOfSpeech: "noun", definition: "חוסר במשהו נדרש", example: "A vitamin deficiency causes fatigue.", exampleHe: "מחסור בוויטמין גורם לעייפות.", translation: "מחסור" },
    { word: "deploy", partOfSpeech: "verb", definition: "להפעיל או לפרוס משאבים", example: "They deploy the new system next week.", exampleHe: "הם מפעילים את המערכת החדשה בשבוע הבא.", translation: "לפרוס/להפעיל" },
    { word: "derive", partOfSpeech: "verb", definition: "להפיק או לגזור ממקור אחר", example: "We derive the rule from the data.", exampleHe: "אנחנו גוזרים את הכלל מהנתונים.", translation: "לגזור/להפיק" },
    { word: "disrupt", partOfSpeech: "verb", definition: "לשבש מהלך תקין", example: "The strike will disrupt the service.", exampleHe: "השביתה תשבש את השירות.", translation: "לשבש" },
    { word: "embed", partOfSpeech: "verb", definition: "להטמיע בתוך משהו אחר", example: "You can embed the video in the page.", exampleHe: "אפשר להטמיע את הסרטון בעמוד.", translation: "להטמיע" },
    { word: "envisage", partOfSpeech: "verb", definition: "לראות בעיני רוחו מצב עתידי", example: "I envisage a longer process.", exampleHe: "אני צופה תהליך ארוך יותר.", translation: "לחזות/לדמיין" },
    { word: "equate", partOfSpeech: "verb", definition: "להשוות בין שני דברים כשווים", example: "Do not equate price with quality.", exampleHe: "אל תשווה בין מחיר לאיכות.", translation: "להשוות" },
    { word: "exhaustive", partOfSpeech: "adjective", definition: "מקיף ומלא, בלי החמצות", example: "The list is not exhaustive.", exampleHe: "הרשימה אינה ממצה.", translation: "ממצה" },
    { word: "fragment", partOfSpeech: "noun", definition: "חלק קטן ששבר משלם", example: "Only a fragment of the text survived.", exampleHe: "רק שריד מהטקסט שרד.", translation: "שבר/רסיס" },
    { word: "immerse", partOfSpeech: "verb", definition: "לשקוע לגמרי בתוך משהו", example: "Immerse yourself in the language.", exampleHe: "תשקע לגמרי בתוך השפה.", translation: "לשקוע/להטביע" },
    { word: "impartial", partOfSpeech: "adjective", definition: "ניטרלי, בלי העדפה לצד", example: "A judge must be impartial.", exampleHe: "שופט חייב להיות חסר פניות.", translation: "חסר פניות" },
    { word: "inception", partOfSpeech: "noun", definition: "נקודת ההתחלה של משהו", example: "The plan was flawed from its inception.", exampleHe: "התוכנית הייתה פגומה מראשיתה.", translation: "ראשית" },
    { word: "iterate", partOfSpeech: "verb", definition: "לחזור על תהליך ולשפר בכל סבב", example: "We iterate until the design works.", exampleHe: "אנחנו חוזרים על התהליך עד שהעיצוב עובד.", translation: "לחזור ולשפר" },
  ],
  C1: [
    { word: "accolade", partOfSpeech: "noun", definition: "שבח או פרס על הישג", example: "The film received every accolade.", exampleHe: "הסרט זכה בכל שבח אפשרי.", translation: "שבח/עיטור" },
    { word: "amass", partOfSpeech: "verb", definition: "לצבור בכמות גדולה", example: "He managed to amass a fortune.", exampleHe: "הוא הצליח לצבור הון.", translation: "לצבור" },
    { word: "anecdote", partOfSpeech: "noun", definition: "סיפור קצר מהחיים", example: "She opened with a short anecdote.", exampleHe: "היא פתחה באנקדוטה קצרה.", translation: "אנקדוטה" },
    { word: "apex", partOfSpeech: "noun", definition: "הנקודה הגבוהה ביותר", example: "He was at the apex of his career.", exampleHe: "הוא היה בשיא הקריירה שלו.", translation: "שיא/פסגה" },
    { word: "arduous", partOfSpeech: "adjective", definition: "קשה ומתיש מאוד", example: "It was an arduous journey.", exampleHe: "זה היה מסע מפרך.", translation: "מפרך" },
    { word: "avert", partOfSpeech: "verb", definition: "למנוע מראש אסון או בעיה", example: "Quick action averted a disaster.", exampleHe: "פעולה מהירה מנעה אסון.", translation: "למנוע" },
    { word: "backlash", partOfSpeech: "noun", definition: "תגובת נגד חריפה", example: "The decision caused a public backlash.", exampleHe: "ההחלטה גררה תגובת נגד ציבורית.", translation: "תגובת נגד" },
    { word: "belie", partOfSpeech: "verb", definition: "לסתור את הרושם הראשוני", example: "Appearances often belie the truth.", exampleHe: "מראית עין לעיתים קרובות סותרת את האמת.", translation: "לסתור" },
    { word: "benevolent", partOfSpeech: "adjective", definition: "נדיב ומיטיב עם אחרים", example: "A benevolent donor paid for it.", exampleHe: "תורם נדיב מימן את זה.", translation: "נדיב/מיטיב" },
    { word: "bestow", partOfSpeech: "verb", definition: "להעניק במחווה רשמית", example: "The king will bestow the title on her.", exampleHe: "המלך יעניק לה את התואר.", translation: "להעניק" },
    { word: "blatant", partOfSpeech: "adjective", definition: "בולט וגלוי בלי בושה", example: "That is a blatant lie.", exampleHe: "זה שקר בוטה.", translation: "בוטה/גלוי" },
    { word: "caustic", partOfSpeech: "adjective", definition: "עוקצני ופוגעני בלשונו", example: "He made a caustic remark.", exampleHe: "הוא העיר הערה עוקצנית.", translation: "עוקצני" },
    { word: "censure", partOfSpeech: "noun", definition: "גינוי רשמי וחריף", example: "The report drew heavy censure.", exampleHe: "הדוח ספג גינוי חריף.", translation: "גינוי" },
    { word: "chronic", partOfSpeech: "adjective", definition: "נמשך זמן רב וחוזר", example: "She suffers from chronic pain.", exampleHe: "היא סובלת מכאב כרוני.", translation: "כרוני" },
    { word: "coerce", partOfSpeech: "verb", definition: "לכפות על מישהו בכוח או באיום", example: "Nobody can coerce you into signing.", exampleHe: "אף אחד לא יכול לכפות עליך לחתום.", translation: "לכפות" },
    { word: "cognitive", partOfSpeech: "adjective", definition: "הקשור לחשיבה ולתפיסה", example: "Sleep affects cognitive performance.", exampleHe: "שינה משפיעה על ביצועים קוגניטיביים.", translation: "קוגניטיבי" },
    { word: "colloquial", partOfSpeech: "adjective", definition: "לשון דיבור יומיומית", example: "That phrase is very colloquial.", exampleHe: "הביטוי הזה מאוד דיבורי.", translation: "דיבורי" },
    { word: "compound", partOfSpeech: "verb", definition: "להחמיר מצב קיים", example: "Delays compound the problem.", exampleHe: "עיכובים מחמירים את הבעיה.", translation: "להחמיר" },
    { word: "condone", partOfSpeech: "verb", definition: "לקבל בשתיקה התנהגות פסולה", example: "We cannot condone such behaviour.", exampleHe: "איננו יכולים להשלים עם התנהגות כזאת.", translation: "להשלים עם" },
    { word: "constrain", partOfSpeech: "verb", definition: "להגביל את מרחב הפעולה", example: "Budgets constrain our choices.", exampleHe: "התקציב מגביל את הבחירות שלנו.", translation: "להגביל" },
    { word: "contingency", partOfSpeech: "noun", definition: "מצב אפשרי שמתכוננים אליו", example: "We need a contingency plan.", exampleHe: "אנחנו צריכים תוכנית מגירה.", translation: "מקרה חירום" },
    { word: "converge", partOfSpeech: "verb", definition: "להתכנס לנקודה או לדעה אחת", example: "The two theories converge here.", exampleHe: "שתי התיאוריות מתכנסות כאן.", translation: "להתכנס" },
    { word: "corollary", partOfSpeech: "noun", definition: "מסקנה שנובעת ישירות", example: "Higher costs are a corollary of growth.", exampleHe: "עלויות גבוהות הן תוצאה נלווית של צמיחה.", translation: "תוצאה נלווית" },
    { word: "covet", partOfSpeech: "verb", definition: "לחשוק במה שיש לאחר", example: "Many covet that position.", exampleHe: "רבים חומדים את התפקיד הזה.", translation: "לחמוד" },
    { word: "decry", partOfSpeech: "verb", definition: "לגנות בפומבי", example: "Critics decry the new law.", exampleHe: "מבקרים מגנים את החוק החדש.", translation: "לגנות" },
  ],
  C2: [
    { word: "aphorism", partOfSpeech: "noun", definition: "אמרה קצרה שמביעה אמת", example: "He ended with a sharp aphorism.", exampleHe: "הוא סיים באמרה חדה.", translation: "אמרת כנף" },
    { word: "apotheosis", partOfSpeech: "noun", definition: "שיא ההתגלמות של משהו", example: "The novel is the apotheosis of the genre.", exampleHe: "הרומן הוא שיא הז'אנר.", translation: "שיא/האדרה" },
    { word: "assail", partOfSpeech: "verb", definition: "לתקוף בעוצמה, גם במילים", example: "Reporters assail him with questions.", exampleHe: "כתבים תוקפים אותו בשאלות.", translation: "לתקוף" },
    { word: "austerity", partOfSpeech: "noun", definition: "מדיניות של צמצום וצנע", example: "Years of austerity followed.", exampleHe: "שנים של צנע באו לאחר מכן.", translation: "צנע" },
    { word: "beguile", partOfSpeech: "verb", definition: "לקסום ולהטעות בו זמנית", example: "The story beguiles the reader.", exampleHe: "הסיפור מקסים ומטעה את הקורא.", translation: "להקסים/להטעות" },
    { word: "bereft", partOfSpeech: "adjective", definition: "נטול לחלוטין ממשהו", example: "The speech was bereft of substance.", exampleHe: "הנאום היה נטול תוכן.", translation: "נטול" },
    { word: "bulwark", partOfSpeech: "noun", definition: "חומת מגן מפני איום", example: "The press is a bulwark of democracy.", exampleHe: "העיתונות היא חומת מגן של הדמוקרטיה.", translation: "חומת מגן" },
    { word: "catharsis", partOfSpeech: "noun", definition: "שחרור רגשי מטהר", example: "Writing gave her a real catharsis.", exampleHe: "הכתיבה העניקה לה קתרזיס אמיתי.", translation: "קתרזיס" },
    { word: "chagrin", partOfSpeech: "noun", definition: "מפח נפש מהול במבוכה", example: "To his chagrin, nobody came.", exampleHe: "לאכזבתו, איש לא הגיע.", translation: "מפח נפש" },
    { word: "charlatan", partOfSpeech: "noun", definition: "מתחזה שמוכר ידע מדומה", example: "The doctor turned out to be a charlatan.", exampleHe: "התברר שהרופא היה שרלטן.", translation: "שרלטן" },
    { word: "conflate", partOfSpeech: "verb", definition: "לערבב שני דברים שונים לאחד", example: "Do not conflate the two issues.", exampleHe: "אל תערבב בין שתי הסוגיות.", translation: "לערבב" },
    { word: "conundrum", partOfSpeech: "noun", definition: "חידה או דילמה סבוכה", example: "This is a real ethical conundrum.", exampleHe: "זו חידה אתית אמיתית.", translation: "חידה סבוכה" },
    { word: "convivial", partOfSpeech: "adjective", definition: "עליז וחברותי באווירה", example: "The dinner was convivial.", exampleHe: "ארוחת הערב הייתה עליזה וחברותית.", translation: "עליז/חברותי" },
    { word: "countenance", partOfSpeech: "verb", definition: "להסכים או לאפשר משהו", example: "The board will not countenance delay.", exampleHe: "הדירקטוריון לא יסכים לעיכוב.", translation: "להסכים" },
    { word: "deleterious", partOfSpeech: "adjective", definition: "מזיק בהדרגה", example: "Stress has deleterious effects.", exampleHe: "ללחץ יש השפעות מזיקות.", translation: "מזיק" },
    { word: "demur", partOfSpeech: "verb", definition: "להביע הסתייגות מנומסת", example: "She began to demur at the plan.", exampleHe: "היא החלה להסתייג מהתוכנית.", translation: "להסתייג" },
    { word: "desultory", partOfSpeech: "adjective", definition: "מקוטע וחסר כיוון", example: "They had a desultory conversation.", exampleHe: "הם ניהלו שיחה מקוטעת.", translation: "מקוטע" },
    { word: "dissemble", partOfSpeech: "verb", definition: "להסתיר כוונות אמיתיות", example: "He continued to dissemble under pressure.", exampleHe: "הוא המשיך להעמיד פנים תחת לחץ.", translation: "להעמיד פנים" },
    { word: "dissonance", partOfSpeech: "noun", definition: "חוסר הרמוניה או התאמה", example: "There is dissonance between words and acts.", exampleHe: "יש דיסוננס בין מילים למעשים.", translation: "דיסוננס" },
    { word: "draconian", partOfSpeech: "adjective", definition: "נוקשה ואכזרי במיוחד", example: "They imposed draconian rules.", exampleHe: "הם הטילו כללים דרקוניים.", translation: "דרקוני" },
    { word: "endemic", partOfSpeech: "adjective", definition: "נפוץ ומושרש באזור מסוים", example: "Corruption was endemic there.", exampleHe: "השחיתות הייתה מושרשת שם.", translation: "מושרש/אנדמי" },
    { word: "evanescent", partOfSpeech: "adjective", definition: "חולף במהירות ונעלם", example: "Fame is evanescent.", exampleHe: "התהילה חולפת.", translation: "חולף" },
    { word: "germane", partOfSpeech: "adjective", definition: "רלוונטי ישירות לנושא", example: "That point is not germane here.", exampleHe: "הנקודה הזאת אינה רלוונטית כאן.", translation: "רלוונטי" },
    { word: "gravitas", partOfSpeech: "noun", definition: "כובד ראש ורצינות", example: "She spoke with real gravitas.", exampleHe: "היא דיברה בכובד ראש אמיתי.", translation: "כובד ראש" },
    { word: "hubris", partOfSpeech: "noun", definition: "יהירות שמובילה לנפילה", example: "His downfall came from hubris.", exampleHe: "נפילתו נבעה מיהירות.", translation: "יהירות" },
  ],
};
