// Additional CEFR-leveled vocabulary, merged into the base WORD_BANKS by the
// generator. Kept separate so the core banks stay stable and so we can keep
// adding rounds toward fuller CEFR coverage. The generator validates that no
// word duplicates another within the same level.
//
// Note: the rarest C1/C2 Hebrew translations are best-effort and worth a
// native-speaker review before relying on them in production.

export const MORE_WORDS = {
  A1: [
    { word: "mother", partOfSpeech: "noun", definition: "ההורה ממין נקבה", example: "My mother is a nurse.", translation: "אמא" },
    { word: "father", partOfSpeech: "noun", definition: "ההורה ממין זכר", example: "His father drives a bus.", translation: "אבא" },
    { word: "brother", partOfSpeech: "noun", definition: "אח — בן של אותם הורים", example: "I have one brother.", translation: "אח" },
    { word: "sister", partOfSpeech: "noun", definition: "אחות — בת של אותם הורים", example: "Her sister is tall.", translation: "אחות" },
    { word: "dog", partOfSpeech: "noun", definition: "חיית מחמד נפוצה שנובחת", example: "The dog is friendly.", translation: "כלב" },
    { word: "cat", partOfSpeech: "noun", definition: "חיית מחמד קטנה שמייללת", example: "The cat is sleeping.", translation: "חתול" },
    { word: "car", partOfSpeech: "noun", definition: "כלי רכב עם ארבעה גלגלים", example: "We have a red car.", translation: "מכונית" },
    { word: "tree", partOfSpeech: "noun", definition: "צמח גדול עם גזע וענפים", example: "The tree is very old.", translation: "עץ" },
    { word: "sun", partOfSpeech: "noun", definition: "הכוכב שמאיר ביום", example: "The sun is bright today.", translation: "שמש" },
    { word: "moon", partOfSpeech: "noun", definition: "הגוף שמאיר בשמיים בלילה", example: "Look at the moon!", translation: "ירח" },
    { word: "rain", partOfSpeech: "noun", definition: "מים שיורדים מהשמיים", example: "I don't like the rain.", translation: "גשם" },
    { word: "night", partOfSpeech: "noun", definition: "החלק החשוך של היממה", example: "Good night!", translation: "לילה" },
    { word: "week", partOfSpeech: "noun", definition: "שבעה ימים", example: "See you next week.", translation: "שבוע" },
    { word: "hand", partOfSpeech: "noun", definition: "חלק הגוף בקצה הזרוע", example: "Wash your hands.", translation: "יד" },
    { word: "eye", partOfSpeech: "noun", definition: "האיבר שבו רואים", example: "She has blue eyes.", translation: "עין" },
    { word: "head", partOfSpeech: "noun", definition: "החלק העליון של הגוף", example: "My head hurts.", translation: "ראש" },
    { word: "door", partOfSpeech: "noun", definition: "פתח שנכנסים דרכו", example: "Close the door, please.", translation: "דלת" },
    { word: "window", partOfSpeech: "noun", definition: "פתח בקיר עם זכוכית", example: "Open the window.", translation: "חלון" },
    { word: "chair", partOfSpeech: "noun", definition: "רהיט לישיבה", example: "Sit on the chair.", translation: "כיסא" },
    { word: "table", partOfSpeech: "noun", definition: "רהיט עם משטח שטוח", example: "The food is on the table.", translation: "שולחן" },
    { word: "bed", partOfSpeech: "noun", definition: "רהיט שישנים עליו", example: "I go to bed at ten.", translation: "מיטה" },
    { word: "milk", partOfSpeech: "noun", definition: "משקה לבן מהפרה", example: "I drink milk every day.", translation: "חלב" },
    { word: "bread", partOfSpeech: "noun", definition: "מאכל בסיסי מקמח", example: "I like fresh bread.", translation: "לחם" },
    { word: "apple", partOfSpeech: "noun", definition: "פרי עגול ואדום או ירוק", example: "An apple a day.", translation: "תפוח" },
    { word: "egg", partOfSpeech: "noun", definition: "מאכל שמגיע מתרנגולת", example: "I eat an egg for breakfast.", translation: "ביצה" },
    { word: "fish", partOfSpeech: "noun", definition: "בעל חיים שחי במים", example: "We ate fish for dinner.", translation: "דג" },
    { word: "bird", partOfSpeech: "noun", definition: "בעל חיים עם כנפיים", example: "A bird is singing.", translation: "ציפור" },
    { word: "red", partOfSpeech: "adjective", definition: "צבע הדם והעגבנייה", example: "She wore a red dress.", translation: "אדום" },
    { word: "blue", partOfSpeech: "adjective", definition: "צבע השמיים", example: "The sky is blue.", translation: "כחול" },
    { word: "green", partOfSpeech: "adjective", definition: "צבע העשב", example: "I have green eyes.", translation: "ירוק" },
    { word: "white", partOfSpeech: "adjective", definition: "צבע השלג", example: "A white shirt.", translation: "לבן" },
    { word: "black", partOfSpeech: "adjective", definition: "הצבע הכהה ביותר", example: "He has a black cat.", translation: "שחור" },
    { word: "sad", partOfSpeech: "adjective", definition: "לא שמח; עצוב", example: "Why are you sad?", translation: "עצוב" },
    { word: "tired", partOfSpeech: "adjective", definition: "זקוק למנוחה או לשינה", example: "I am very tired.", translation: "עייף" },
    { word: "boy", partOfSpeech: "noun", definition: "ילד ממין זכר", example: "The boy is playing.", translation: "ילד/נער" },
    { word: "girl", partOfSpeech: "noun", definition: "ילדה ממין נקבה", example: "The girl is reading.", translation: "ילדה" },
  ],
  A2: [
    { word: "arrive", partOfSpeech: "verb", definition: "להגיע ליעד", example: "We arrived at noon.", translation: "להגיע" },
    { word: "menu", partOfSpeech: "noun", definition: "רשימת המאכלים במסעדה", example: "Can I see the menu?", translation: "תפריט" },
    { word: "order", partOfSpeech: "verb", definition: "לבקש אוכל או מוצר", example: "I'd like to order a pizza.", translation: "להזמין" },
    { word: "bill", partOfSpeech: "noun", definition: "החשבון לתשלום", example: "Can we have the bill?", translation: "חשבון" },
    { word: "suitcase", partOfSpeech: "noun", definition: "מזוודה לבגדים בנסיעה", example: "My suitcase is heavy.", translation: "מזוודה" },
    { word: "passport", partOfSpeech: "noun", definition: "מסמך לנסיעה בין מדינות", example: "Show me your passport.", translation: "דרכון" },
    { word: "tourist", partOfSpeech: "noun", definition: "אדם שמטייל במקום זר", example: "Many tourists visit Rome.", translation: "תייר" },
    { word: "mountain", partOfSpeech: "noun", definition: "הר גבוה", example: "They climbed the mountain.", translation: "הר" },
    { word: "forest", partOfSpeech: "noun", definition: "שטח גדול מלא עצים", example: "We walked in the forest.", translation: "יער" },
    { word: "hobby", partOfSpeech: "noun", definition: "פעילות שעושים להנאה", example: "My hobby is painting.", translation: "תחביב" },
    { word: "dangerous", partOfSpeech: "adjective", definition: "מסוכן; עלול לגרום נזק", example: "Fast driving is dangerous.", translation: "מסוכן" },
    { word: "safe", partOfSpeech: "adjective", definition: "בטוח; ללא סכנה", example: "The children are safe.", translation: "בטוח" },
    { word: "careful", partOfSpeech: "adjective", definition: "זהיר; שם לב לסכנות", example: "Be careful on the stairs.", translation: "זהיר" },
    { word: "polite", partOfSpeech: "adjective", definition: "מנומס; מתנהג יפה", example: "She is always polite.", translation: "מנומס" },
    { word: "friendly", partOfSpeech: "adjective", definition: "ידידותי; נחמד לאחרים", example: "The staff is very friendly.", translation: "ידידותי" },
    { word: "boring", partOfSpeech: "adjective", definition: "משעמם; לא מעניין", example: "The film was boring.", translation: "משעמם" },
    { word: "exciting", partOfSpeech: "adjective", definition: "מרגש; גורם להתרגשות", example: "It was an exciting game.", translation: "מרגש" },
    { word: "invite", partOfSpeech: "verb", definition: "להזמין מישהו לאירוע", example: "They invited us to dinner.", translation: "להזמין (אורח)" },
    { word: "introduce", partOfSpeech: "verb", definition: "להכיר בין אנשים", example: "Let me introduce my friend.", translation: "להציג/להכיר" },
    { word: "describe", partOfSpeech: "verb", definition: "לתאר במילים", example: "Describe your house.", translation: "לתאר" },
    { word: "repair", partOfSpeech: "verb", definition: "לתקן משהו שבור", example: "He repaired the roof.", translation: "לתקן" },
    { word: "lend", partOfSpeech: "verb", definition: "לתת משהו לזמן מה", example: "Can you lend me a pen?", translation: "להשאיל" },
    { word: "save", partOfSpeech: "verb", definition: "לשמור כסף לעתיד", example: "I save money every month.", translation: "לחסוך" },
    { word: "cost", partOfSpeech: "verb", definition: "להיות בעל מחיר מסוים", example: "How much does it cost?", translation: "לעלות (מחיר)" },
    { word: "neighbour", partOfSpeech: "noun", definition: "אדם שגר לידך", example: "My neighbour is kind.", translation: "שכן" },
    { word: "weekend", partOfSpeech: "noun", definition: "שבת וראשון; ימי המנוחה", example: "Have a great weekend.", translation: "סוף שבוע" },
    { word: "exercise", partOfSpeech: "noun", definition: "פעילות גופנית", example: "Exercise keeps you fit.", translation: "התעמלות/תרגיל" },
  ],
  B1: [
    { word: "benefit", partOfSpeech: "noun", definition: "תועלת — יתרון או רווח", example: "Exercise has many benefits.", translation: "תועלת" },
    { word: "method", partOfSpeech: "noun", definition: "שיטה — דרך מסודרת לעשות משהו", example: "We used a new method.", translation: "שיטה" },
    { word: "reason", partOfSpeech: "noun", definition: "סיבה — הסבר מדוע", example: "What is the reason?", translation: "סיבה" },
    { word: "goal", partOfSpeech: "noun", definition: "מטרה שרוצים להשיג", example: "My goal is to speak fluently.", translation: "מטרה/יעד" },
    { word: "skill", partOfSpeech: "noun", definition: "מיומנות — יכולת שנרכשה", example: "Writing is a useful skill.", translation: "מיומנות" },
    { word: "knowledge", partOfSpeech: "noun", definition: "ידע — מה שאדם יודע", example: "She has deep knowledge.", translation: "ידע" },
    { word: "success", partOfSpeech: "noun", definition: "הצלחה — השגת מטרה", example: "The project was a success.", translation: "הצלחה" },
    { word: "failure", partOfSpeech: "noun", definition: "כישלון — אי-הצלחה", example: "Failure is part of learning.", translation: "כישלון" },
    { word: "decision", partOfSpeech: "noun", definition: "החלטה — בחירה שנעשתה", example: "It was a hard decision.", translation: "החלטה" },
    { word: "solution", partOfSpeech: "noun", definition: "פתרון לבעיה", example: "We found a solution.", translation: "פתרון" },
    { word: "opinion", partOfSpeech: "noun", definition: "דעה — מה שאדם חושב", example: "In my opinion, it's wrong.", translation: "דעה" },
    { word: "advice", partOfSpeech: "noun", definition: "עצה — הצעה כיצד לפעול", example: "Thanks for the advice.", translation: "עצה" },
    { word: "progress", partOfSpeech: "noun", definition: "התקדמות — שיפור עם הזמן", example: "You're making good progress.", translation: "התקדמות" },
    { word: "effort", partOfSpeech: "noun", definition: "מאמץ — השקעת כוח", example: "It took a lot of effort.", translation: "מאמץ" },
    { word: "confidence", partOfSpeech: "noun", definition: "ביטחון עצמי", example: "Speak with confidence.", translation: "ביטחון עצמי" },
    { word: "pressure", partOfSpeech: "noun", definition: "לחץ — מתח או דרישה כבדה", example: "He works under pressure.", translation: "לחץ" },
    { word: "relationship", partOfSpeech: "noun", definition: "מערכת יחסים בין אנשים", example: "They have a close relationship.", translation: "מערכת יחסים" },
    { word: "communication", partOfSpeech: "noun", definition: "תקשורת — העברת מסרים", example: "Good communication is key.", translation: "תקשורת" },
    { word: "culture", partOfSpeech: "noun", definition: "תרבות — מנהגים ואמנות של חברה", example: "I love Italian culture.", translation: "תרבות" },
    { word: "tradition", partOfSpeech: "noun", definition: "מסורת — מנהג שעובר מדור לדור", example: "It's a family tradition.", translation: "מסורת" },
    { word: "generation", partOfSpeech: "noun", definition: "דור — קבוצת בני אותו גיל", example: "The younger generation.", translation: "דור" },
    { word: "career", partOfSpeech: "noun", definition: "קריירה — מסלול מקצועי", example: "She has a great career.", translation: "קריירה" },
    { word: "salary", partOfSpeech: "noun", definition: "משכורת — תשלום על עבודה", example: "He earns a good salary.", translation: "משכורת" },
    { word: "customer", partOfSpeech: "noun", definition: "לקוח — מי שקונה מוצר או שירות", example: "The customer is waiting.", translation: "לקוח" },
    { word: "product", partOfSpeech: "noun", definition: "מוצר — דבר שמיוצר למכירה", example: "It's a popular product.", translation: "מוצר" },
    { word: "service", partOfSpeech: "noun", definition: "שירות — עזרה או פעולה עבור לקוח", example: "The service was excellent.", translation: "שירות" },
    { word: "quality", partOfSpeech: "noun", definition: "איכות — רמת הטיב של משהו", example: "High quality, low price.", translation: "איכות" },
    { word: "decrease", partOfSpeech: "verb", definition: "להקטין או לרדת בכמות", example: "Sales decreased this year.", translation: "לרדת/להפחית" },
    { word: "encourage", partOfSpeech: "verb", definition: "לעודד — לתת ביטחון לפעולה", example: "Teachers encourage students.", translation: "לעודד" },
    { word: "avoid", partOfSpeech: "verb", definition: "להימנע מ-", example: "Avoid junk food.", translation: "להימנע" },
    { word: "allow", partOfSpeech: "verb", definition: "לאפשר; לתת רשות", example: "Smoking is not allowed.", translation: "לאפשר/להרשות" },
    { word: "prevent", partOfSpeech: "verb", definition: "למנוע — לעצור שמשהו יקרה", example: "Wash hands to prevent illness.", translation: "למנוע" },
    { word: "achievement", partOfSpeech: "noun", definition: "הישג — משהו שהושג במאמץ", example: "Graduating was a big achievement.", translation: "הישג" },
    { word: "responsibility", partOfSpeech: "noun", definition: "אחריות — חובה לדאוג למשהו", example: "It's your responsibility.", translation: "אחריות" },
  ],
  B2: [
    { word: "analyse", partOfSpeech: "verb", definition: "לנתח — לבחון משהו בפירוט", example: "We analysed the results.", translation: "לנתח" },
    { word: "evaluate", partOfSpeech: "verb", definition: "להעריך — לשפוט ערך או איכות", example: "Evaluate the options carefully.", translation: "להעריך" },
    { word: "interpret", partOfSpeech: "verb", definition: "לפרש — להסביר משמעות", example: "How do you interpret this?", translation: "לפרש" },
    { word: "illustrate", partOfSpeech: "verb", definition: "להמחיש — להבהיר באמצעות דוגמה", example: "This example illustrates the point.", translation: "להמחיש" },
    { word: "highlight", partOfSpeech: "verb", definition: "להדגיש — להבליט משהו חשוב", example: "The report highlights key risks.", translation: "להדגיש/להבליט" },
    { word: "summarize", partOfSpeech: "verb", definition: "לסכם — לתמצת בקצרה", example: "Let me summarize the plan.", translation: "לסכם" },
    { word: "determine", partOfSpeech: "verb", definition: "לקבוע — להחליט או לברר בוודאות", example: "Tests will determine the cause.", translation: "לקבוע" },
    { word: "reveal", partOfSpeech: "verb", definition: "לחשוף — לגלות מידע נסתר", example: "The study revealed a trend.", translation: "לחשוף" },
    { word: "identify", partOfSpeech: "verb", definition: "לזהות — לקבוע מה או מי משהו", example: "Identify the main problem.", translation: "לזהות" },
    { word: "examine", partOfSpeech: "verb", definition: "לבחון — לבדוק בקפידה", example: "The doctor examined the patient.", translation: "לבחון" },
    { word: "investigate", partOfSpeech: "verb", definition: "לחקור — לברר עובדות", example: "Police investigated the case.", translation: "לחקור" },
    { word: "contribute", partOfSpeech: "verb", definition: "לתרום — להוסיף חלק לתוצאה", example: "Everyone contributed ideas.", translation: "לתרום" },
    { word: "participate", partOfSpeech: "verb", definition: "להשתתף — לקחת חלק", example: "She participated in the debate.", translation: "להשתתף" },
    { word: "generate", partOfSpeech: "verb", definition: "לייצר — ליצור או להפיק", example: "The plant generates power.", translation: "לייצר/להפיק" },
    { word: "enhance", partOfSpeech: "verb", definition: "לשפר — להעלות איכות או ערך", example: "Music enhances the mood.", translation: "לשפר/לשדרג" },
    { word: "expand", partOfSpeech: "verb", definition: "להרחיב — להגדיל בהיקף", example: "They expanded the business.", translation: "להרחיב" },
    { word: "decline", partOfSpeech: "verb", definition: "לרדת או לסרב בנימוס", example: "Sales declined sharply.", translation: "לרדת/לסרב" },
    { word: "emerge", partOfSpeech: "verb", definition: "לצוץ — להופיע או להתגלות", example: "A new trend emerged.", translation: "לצוץ/להופיע" },
    { word: "persist", partOfSpeech: "verb", definition: "להתמיד או להימשך לאורך זמן", example: "The problem persists.", translation: "להתמיד/להימשך" },
    { word: "allocate", partOfSpeech: "verb", definition: "להקצות — לחלק משאבים למטרה", example: "Funds were allocated to schools.", translation: "להקצות" },
    { word: "undergo", partOfSpeech: "verb", definition: "לעבור — להתנסות בתהליך", example: "He underwent surgery.", translation: "לעבור (תהליך)" },
    { word: "hypothesis", partOfSpeech: "noun", definition: "השערה — רעיון לבדיקה במחקר", example: "The data supports the hypothesis.", translation: "השערה" },
    { word: "phenomenon", partOfSpeech: "noun", definition: "תופעה — דבר שניתן לצפות בו", example: "A natural phenomenon.", translation: "תופעה" },
    { word: "variable", partOfSpeech: "noun", definition: "משתנה — גורם שיכול להשתנות", example: "Price is one variable.", translation: "משתנה" },
    { word: "component", partOfSpeech: "noun", definition: "רכיב — חלק ממכלול", example: "A key component of the engine.", translation: "רכיב" },
    { word: "procedure", partOfSpeech: "noun", definition: "הליך — סדרת צעדים קבועה", example: "Follow the safety procedure.", translation: "נוהל/הליך" },
    { word: "outcome", partOfSpeech: "noun", definition: "תוצאה — מה שמתקבל בסוף", example: "The outcome was positive.", translation: "תוצאה" },
    { word: "trend", partOfSpeech: "noun", definition: "מגמה — כיוון התפתחות", example: "A growing trend.", translation: "מגמה" },
    { word: "aspect", partOfSpeech: "noun", definition: "היבט — צד מסוים של נושא", example: "Consider every aspect.", translation: "היבט/פן" },
    { word: "context", partOfSpeech: "noun", definition: "הקשר — הנסיבות סביב משהו", example: "Read the word in context.", translation: "הקשר" },
    { word: "notion", partOfSpeech: "noun", definition: "מושג או רעיון", example: "An interesting notion.", translation: "מושג/רעיון" },
    { word: "domain", partOfSpeech: "noun", definition: "תחום — שטח ידע או פעילות", example: "Outside my domain of expertise.", translation: "תחום" },
    { word: "notably", partOfSpeech: "adverb", definition: "במיוחד; באופן בולט", example: "Several cities, notably Paris.", translation: "במיוחד/בייחוד" },
    { word: "comprise", partOfSpeech: "verb", definition: "לכלול — להיות מורכב מ-", example: "The team comprises five members.", translation: "לכלול/להיות מורכב מ" },
    { word: "accumulate", partOfSpeech: "verb", definition: "לצבור — לאסוף בהדרגה", example: "Dust accumulates over time.", translation: "לצבור" },
    { word: "diverse", partOfSpeech: "adjective", definition: "מגוון — מסוגים שונים", example: "A diverse population.", translation: "מגוון" },
  ],
  C1: [
    { word: "arbitrary", partOfSpeech: "adjective", definition: "שרירותי — נקבע ללא היגיון ברור", example: "An arbitrary decision.", translation: "שרירותי" },
    { word: "candid", partOfSpeech: "adjective", definition: "כן וגלוי, ללא הסתרה", example: "A candid conversation.", translation: "כן/גלוי לב" },
    { word: "cumbersome", partOfSpeech: "adjective", definition: "מסורבל — קשה לשימוש או לנשיאה", example: "A cumbersome process.", translation: "מסורבל" },
    { word: "detrimental", partOfSpeech: "adjective", definition: "מזיק — גורם נזק", example: "Smoking is detrimental to health.", translation: "מזיק" },
    { word: "feasible", partOfSpeech: "adjective", definition: "בר-ביצוע — אפשרי מעשית", example: "Is the plan feasible?", translation: "בר-ביצוע" },
    { word: "formidable", partOfSpeech: "adjective", definition: "אדיר ומעורר יראה או חשש", example: "A formidable opponent.", translation: "אדיר/מאיים" },
    { word: "futile", partOfSpeech: "adjective", definition: "חסר תוחלת — לא יביא תוצאה", example: "A futile attempt.", translation: "חסר תוחלת/עקר" },
    { word: "impede", partOfSpeech: "verb", definition: "לעכב — להפריע להתקדמות", example: "Snow impeded traffic.", translation: "לעכב/להפריע" },
    { word: "incentive", partOfSpeech: "noun", definition: "תמריץ — דבר שמעודד לפעול", example: "Bonuses are an incentive.", translation: "תמריץ" },
    { word: "indispensable", partOfSpeech: "adjective", definition: "הכרחי — שאי אפשר בלעדיו", example: "She is indispensable to the team.", translation: "הכרחי/חיוני" },
    { word: "inevitable", partOfSpeech: "adjective", definition: "בלתי-נמנע — חייב לקרות", example: "Change is inevitable.", translation: "בלתי-נמנע" },
    { word: "lucrative", partOfSpeech: "adjective", definition: "רווחי — מכניס הרבה כסף", example: "A lucrative business.", translation: "רווחי" },
    { word: "mundane", partOfSpeech: "adjective", definition: "שגרתי ויומיומי, חסר עניין", example: "Mundane tasks.", translation: "שגרתי/יומיומי" },
    { word: "obsolete", partOfSpeech: "adjective", definition: "מיושן — יצא משימוש", example: "The technology is obsolete.", translation: "מיושן" },
    { word: "pertinent", partOfSpeech: "adjective", definition: "רלוונטי — נוגע ישירות לעניין", example: "A pertinent question.", translation: "רלוונטי/ענייני" },
    { word: "predicament", partOfSpeech: "noun", definition: "מצוקה — מצב קשה ומביך", example: "We're in a real predicament.", translation: "מצוקה/מצב קשה" },
    { word: "proponent", partOfSpeech: "noun", definition: "תומך — מי שדוגל ברעיון", example: "A proponent of reform.", translation: "תומך/דוגל" },
    { word: "redundant", partOfSpeech: "adjective", definition: "מיותר — עודף ולא נחוץ", example: "The phrase is redundant.", translation: "מיותר/עודף" },
    { word: "resilient", partOfSpeech: "adjective", definition: "חסון — מתאושש מקושי", example: "Children are very resilient.", translation: "חסון/עמיד" },
    { word: "scrutinize", partOfSpeech: "verb", definition: "לבחון בקפדנות ובדקדוק", example: "Auditors scrutinize the accounts.", translation: "לבחון בקפדנות" },
    { word: "stark", partOfSpeech: "adjective", definition: "חד ובולט; בוטה", example: "A stark contrast.", translation: "חד/בוטה" },
    { word: "subtle", partOfSpeech: "adjective", definition: "עדין ודק, לא ברור מיד", example: "A subtle difference.", translation: "עדין/דק" },
    { word: "tangible", partOfSpeech: "adjective", definition: "מוחשי — ניתן למישוש או למדידה", example: "Tangible results.", translation: "מוחשי" },
    { word: "threshold", partOfSpeech: "noun", definition: "סף — נקודת מעבר או התחלה", example: "The pain threshold.", translation: "סף" },
    { word: "trivial", partOfSpeech: "adjective", definition: "זניח — חסר חשיבות", example: "A trivial matter.", translation: "זניח/של מה בכך" },
    { word: "unprecedented", partOfSpeech: "adjective", definition: "חסר תקדים — לא קרה מעולם", example: "An unprecedented crisis.", translation: "חסר תקדים" },
    { word: "versatile", partOfSpeech: "adjective", definition: "רב-תכליתי — מתאים לשימושים רבים", example: "A versatile tool.", translation: "רב-תכליתי" },
    { word: "ambivalent", partOfSpeech: "adjective", definition: "דו-ערכי — בעל רגשות מעורבים", example: "She felt ambivalent about it.", translation: "דו-ערכי/מסויג" },
    { word: "conducive", partOfSpeech: "adjective", definition: "מסייע — תורם לתוצאה רצויה", example: "An environment conducive to study.", translation: "מסייע/תורם" },
    { word: "discreet", partOfSpeech: "adjective", definition: "דיסקרטי — זהיר ושומר על סוד", example: "Please be discreet.", translation: "דיסקרטי/צנוע" },
    { word: "eloquent", partOfSpeech: "adjective", definition: "רהוט — מיטיב לבטא רעיונות", example: "An eloquent speech.", translation: "רהוט" },
    { word: "exemplify", partOfSpeech: "verb", definition: "לשמש דוגמה טיפוסית למשהו", example: "This case exemplifies the trend.", translation: "לשמש דוגמה ל-" },
    { word: "nonetheless", partOfSpeech: "adverb", definition: "ובכל זאת — מילת ניגוד פורמלית", example: "It's risky; nonetheless, we'll try.", translation: "ובכל זאת" },
    { word: "prerequisite", partOfSpeech: "noun", definition: "תנאי מוקדם — דרישה הכרחית", example: "Math is a prerequisite for the course.", translation: "תנאי מוקדם" },
    { word: "nuanced", partOfSpeech: "adjective", definition: "מעודן — מבחין בהבדלים דקים", example: "A nuanced argument.", translation: "מעודן/מדויק בגוונים" },
    { word: "scrupulous", partOfSpeech: "adjective", definition: "קפדן וישר עד הפרט הקטן", example: "Scrupulous attention to detail.", translation: "קפדן/ישר" },
  ],
  C2: [
    { word: "acerbic", partOfSpeech: "adjective", definition: "חריף ועוקצני בלשונו", example: "An acerbic critic.", translation: "חריף/עוקצני" },
    { word: "acumen", partOfSpeech: "noun", definition: "חדות שכל ושיפוט מהיר", example: "Business acumen.", translation: "חדות שכל/חוש" },
    { word: "antipathy", partOfSpeech: "noun", definition: "סלידה — רגש שלילי עמוק", example: "A deep antipathy to change.", translation: "סלידה/רתיעה" },
    { word: "cacophony", partOfSpeech: "noun", definition: "צרימה — תערובת קולות צורמת", example: "A cacophony of horns.", translation: "צרימה/רעש מבולגן" },
    { word: "camaraderie", partOfSpeech: "noun", definition: "רעות — תחושת חברות וקרבה", example: "Team camaraderie.", translation: "רעות/אחוות חברים" },
    { word: "capricious", partOfSpeech: "adjective", definition: "הפכפך — משנה דעתו ללא היגיון", example: "Capricious weather.", translation: "הפכפך/קפריזי" },
    { word: "clandestine", partOfSpeech: "adjective", definition: "חשאי — נעשה בסתר", example: "A clandestine meeting.", translation: "חשאי" },
    { word: "connoisseur", partOfSpeech: "noun", definition: "מבין גדול ואנין טעם בתחום", example: "A wine connoisseur.", translation: "מבין/אנין טעם" },
    { word: "denigrate", partOfSpeech: "verb", definition: "להשמיץ — להמעיט בערך", example: "He denigrated their work.", translation: "להשמיץ/לבזות" },
    { word: "disparate", partOfSpeech: "adjective", definition: "שונים מאוד זה מזה", example: "Disparate ideas.", translation: "שונים בתכלית" },
    { word: "ebullient", partOfSpeech: "adjective", definition: "תוסס ומלא התלהבות", example: "An ebullient host.", translation: "תוסס/נלהב" },
    { word: "egregious", partOfSpeech: "adjective", definition: "בוטה ונורא במיוחד (שלילי)", example: "An egregious error.", translation: "נורא/בוטה" },
    { word: "enigma", partOfSpeech: "noun", definition: "חידה — דבר מסתורי וקשה להבנה", example: "He remained an enigma.", translation: "חידה/תעלומה" },
    { word: "erudite", partOfSpeech: "adjective", definition: "מלומד — בעל ידע רחב ועמוק", example: "An erudite scholar.", translation: "מלומד" },
    { word: "fastidious", partOfSpeech: "adjective", definition: "קפדן ובררן עד הפרט הקטן", example: "Fastidious about cleanliness.", translation: "קפדן/בררן" },
    { word: "garrulous", partOfSpeech: "adjective", definition: "פטפטן — מדבר יותר מדי", example: "A garrulous neighbour.", translation: "פטפטן" },
    { word: "hegemony", partOfSpeech: "noun", definition: "הגמוניה — שליטה של גורם אחד", example: "Cultural hegemony.", translation: "הגמוניה/שליטה" },
    { word: "iconoclast", partOfSpeech: "noun", definition: "מי שמנפץ מוסכמות ואמונות", example: "He was an iconoclast.", translation: "מנפץ מוסכמות" },
    { word: "impetuous", partOfSpeech: "adjective", definition: "נמהר — פועל בלי לחשוב", example: "An impetuous decision.", translation: "נמהר/פזיז" },
    { word: "ineffable", partOfSpeech: "adjective", definition: "שלא ניתן לבטא במילים", example: "Ineffable beauty.", translation: "בל יתואר" },
    { word: "magnanimous", partOfSpeech: "adjective", definition: "רחב לב ונדיב, גם כלפי יריב", example: "A magnanimous gesture.", translation: "רחב לב/אציל נפש" },
    { word: "nadir", partOfSpeech: "noun", definition: "נקודת השפל — המצב הנמוך ביותר", example: "The nadir of his career.", translation: "שפל/נקודת השפל" },
    { word: "panacea", partOfSpeech: "noun", definition: "תרופת פלא לכל בעיה", example: "No single policy is a panacea.", translation: "תרופת פלא" },
    { word: "pejorative", partOfSpeech: "adjective", definition: "של גנאי — בעל קונוטציה שלילית", example: "A pejorative term.", translation: "של גנאי" },
    { word: "pithy", partOfSpeech: "adjective", definition: "תמציתי וקולע", example: "A pithy remark.", translation: "תמציתי/קולע" },
    { word: "recalcitrant", partOfSpeech: "adjective", definition: "סרבן ועיקש, מתנגד לסמכות", example: "A recalcitrant student.", translation: "סרבן/עיקש" },
    { word: "sycophant", partOfSpeech: "noun", definition: "חנפן — מחמיא כדי להתחבב", example: "Surrounded by sycophants.", translation: "חנפן" },
    { word: "taciturn", partOfSpeech: "adjective", definition: "שתקן — ממעט בדיבור", example: "A taciturn man.", translation: "שתקן" },
    { word: "vociferous", partOfSpeech: "adjective", definition: "קולני — מביע דעה בתקיפות", example: "Vociferous protests.", translation: "קולני/רעשני" },
    { word: "abstruse", partOfSpeech: "adjective", definition: "סתום — קשה מאוד להבנה", example: "An abstruse theory.", translation: "סתום/עמום" },
    { word: "ennui", partOfSpeech: "noun", definition: "שעמום ודכדוך מתמשך", example: "A sense of ennui.", translation: "שעמום/דכדוך" },
    { word: "inchoate", partOfSpeech: "adjective", definition: "ראשוני ולא מגובש", example: "Inchoate ideas.", translation: "ראשוני/לא מגובש" },
    { word: "obstreperous", partOfSpeech: "adjective", definition: "סורר ורעשני, קשה לשליטה", example: "Obstreperous children.", translation: "סורר/רעשני" },
    { word: "recondite", partOfSpeech: "adjective", definition: "נסתר ועמום, מובן למעטים", example: "A recondite subject.", translation: "נסתר/עמום" },
    { word: "vitriolic", partOfSpeech: "adjective", definition: "ארסי וחריף ביותר (ביקורת)", example: "A vitriolic attack.", translation: "ארסי/נוטף ארס" },
  ],
};
