// Round 5 of additional CEFR-leveled vocabulary, merged into WORD_BANKS by the
// generator. Combined set validated for duplicates/missing fields.
// Rarest C1/C2 Hebrew translations are best-effort pending native review.

export const MORE_WORDS5 = {
  A1: [
    { word: "today", partOfSpeech: "adverb", definition: "היום הזה", example: "Today is Monday.", translation: "היום" },
    { word: "tomorrow", partOfSpeech: "adverb", definition: "היום שאחרי היום", example: "See you tomorrow.", translation: "מחר" },
    { word: "yesterday", partOfSpeech: "adverb", definition: "היום שלפני היום", example: "I saw it yesterday.", translation: "אתמול" },
    { word: "year", partOfSpeech: "noun", definition: "תקופה של 12 חודשים", example: "Last year was hard.", translation: "שנה" },
    { word: "minute", partOfSpeech: "noun", definition: "יחידת זמן של 60 שניות", example: "Wait a minute.", translation: "דקה" },
    { word: "summer", partOfSpeech: "noun", definition: "העונה החמה", example: "We swim in summer.", translation: "קיץ" },
    { word: "spring", partOfSpeech: "noun", definition: "העונה שאחרי החורף", example: "Flowers grow in spring.", translation: "אביב" },
    { word: "autumn", partOfSpeech: "noun", definition: "העונה שלפני החורף", example: "Leaves fall in autumn.", translation: "סתיו" },
    { word: "first", partOfSpeech: "adjective", definition: "מספר אחת בסדר", example: "The first day.", translation: "ראשון" },
    { word: "last", partOfSpeech: "adjective", definition: "האחרון בסדר", example: "The last bus.", translation: "אחרון" },
    { word: "next", partOfSpeech: "adjective", definition: "הבא בתור", example: "The next train.", translation: "הבא" },
    { word: "here", partOfSpeech: "adverb", definition: "במקום הזה", example: "Come here.", translation: "כאן" },
    { word: "there", partOfSpeech: "adverb", definition: "במקום ההוא", example: "Put it there.", translation: "שם" },
    { word: "now", partOfSpeech: "adverb", definition: "ברגע זה", example: "Do it now.", translation: "עכשיו" },
    { word: "again", partOfSpeech: "adverb", definition: "עוד פעם", example: "Try again.", translation: "שוב" },
    { word: "very", partOfSpeech: "adverb", definition: "במידה רבה", example: "It's very hot.", translation: "מאוד" },
    { word: "also", partOfSpeech: "adverb", definition: "בנוסף, גם", example: "I also like tea.", translation: "גם" },
    { word: "please", partOfSpeech: "adverb", definition: "מילת נימוס לבקשה", example: "Sit down, please.", translation: "בבקשה" },
    { word: "maybe", partOfSpeech: "adverb", definition: "אולי, ייתכן", example: "Maybe later.", translation: "אולי" },
    { word: "hello", partOfSpeech: "exclamation", definition: "ברכת שלום", example: "Hello, how are you?", translation: "שלום/היי" },
    { word: "goodbye", partOfSpeech: "exclamation", definition: "ברכת פרידה", example: "Goodbye, see you!", translation: "להתראות" },
    { word: "sorry", partOfSpeech: "adjective", definition: "מילה להתנצלות", example: "Sorry, I'm late.", translation: "מצטער/סליחה" },
    { word: "slow", partOfSpeech: "adjective", definition: "איטי, לא מהיר", example: "A slow train.", translation: "איטי" },
    { word: "welcome", partOfSpeech: "exclamation", definition: "ברכת קבלת פנים", example: "Welcome home!", translation: "ברוך הבא" },
  ],
  A2: [
    { word: "agree", partOfSpeech: "verb", definition: "להסכים", example: "I agree with you.", translation: "להסכים" },
    { word: "believe", partOfSpeech: "verb", definition: "להאמין", example: "I believe you.", translation: "להאמין" },
    { word: "close", partOfSpeech: "verb", definition: "לסגור", example: "Close the window.", translation: "לסגור" },
    { word: "cross", partOfSpeech: "verb", definition: "לחצות", example: "Cross the road carefully.", translation: "לחצות" },
    { word: "dance", partOfSpeech: "verb", definition: "לרקוד", example: "They danced all night.", translation: "לרקוד" },
    { word: "dream", partOfSpeech: "verb", definition: "לחלום", example: "I dream of travelling.", translation: "לחלום" },
    { word: "drive", partOfSpeech: "verb", definition: "לנהוג", example: "She drives to work.", translation: "לנהוג" },
    { word: "enter", partOfSpeech: "verb", definition: "להיכנס", example: "Enter the room quietly.", translation: "להיכנס" },
    { word: "fall", partOfSpeech: "verb", definition: "ליפול", example: "Be careful not to fall.", translation: "ליפול" },
    { word: "fill", partOfSpeech: "verb", definition: "למלא", example: "Fill the glass.", translation: "למלא" },
    { word: "follow", partOfSpeech: "verb", definition: "לעקוב או לבוא אחרי", example: "Follow me.", translation: "לעקוב/לבוא אחרי" },
    { word: "grow", partOfSpeech: "verb", definition: "לגדול", example: "Plants grow in the sun.", translation: "לגדול" },
    { word: "hate", partOfSpeech: "verb", definition: "לשנוא", example: "I hate waiting.", translation: "לשנוא" },
    { word: "join", partOfSpeech: "verb", definition: "להצטרף", example: "Join our team.", translation: "להצטרף" },
    { word: "jump", partOfSpeech: "verb", definition: "לקפוץ", example: "The cat jumped up.", translation: "לקפוץ" },
    { word: "listen", partOfSpeech: "verb", definition: "להקשיב", example: "Listen carefully.", translation: "להקשיב" },
    { word: "marry", partOfSpeech: "verb", definition: "להתחתן", example: "They will marry in June.", translation: "להתחתן" },
    { word: "move", partOfSpeech: "verb", definition: "לזוז, או לעבור דירה", example: "We moved to a new city.", translation: "לזוז/לעבור" },
    { word: "pick", partOfSpeech: "verb", definition: "לבחור, או לקטוף", example: "Pick a card.", translation: "לבחור/לקטוף" },
    { word: "ride", partOfSpeech: "verb", definition: "לרכוב", example: "I ride my bike to school.", translation: "לרכוב" },
    { word: "sell", partOfSpeech: "verb", definition: "למכור", example: "They sell fresh bread.", translation: "למכור" },
    { word: "shout", partOfSpeech: "verb", definition: "לצעוק", example: "Don't shout, please.", translation: "לצעוק" },
  ],
  B1: [
    { word: "accompany", partOfSpeech: "verb", definition: "ללוות, ללכת עם", example: "I'll accompany you home.", translation: "ללוות" },
    { word: "adapt", partOfSpeech: "verb", definition: "להסתגל לשינוי", example: "Animals adapt to the cold.", translation: "להסתגל" },
    { word: "adopt", partOfSpeech: "verb", definition: "לאמץ (ילד או רעיון)", example: "They adopted a new method.", translation: "לאמץ" },
    { word: "advance", partOfSpeech: "verb", definition: "להתקדם", example: "The army advanced slowly.", translation: "להתקדם/קידום" },
    { word: "afford", partOfSpeech: "verb", definition: "להרשות לעצמו (כלכלית)", example: "I can't afford a new car.", translation: "להרשות לעצמו" },
    { word: "aim", partOfSpeech: "verb", definition: "לכוון למטרה", example: "We aim to finish today.", translation: "לכוון/מטרה" },
    { word: "appreciate", partOfSpeech: "verb", definition: "להעריך, להוקיר", example: "I appreciate your help.", translation: "להעריך/להוקיר" },
    { word: "attach", partOfSpeech: "verb", definition: "לצרף, לחבר", example: "Attach the file.", translation: "לצרף/לחבר" },
    { word: "attempt", partOfSpeech: "verb", definition: "לנסות", example: "He attempted the climb.", translation: "לנסות/ניסיון" },
    { word: "aware", partOfSpeech: "adjective", definition: "מודע ל-", example: "Are you aware of the risk?", translation: "מודע" },
    { word: "balance", partOfSpeech: "verb", definition: "לאזן", example: "Balance work and rest.", translation: "לאזן/איזון" },
    { word: "bother", partOfSpeech: "verb", definition: "להטריד, או לטרוח", example: "Don't bother him now.", translation: "להטריד/לטרוח" },
    { word: "commit", partOfSpeech: "verb", definition: "להתחייב, או לבצע", example: "Commit to the plan.", translation: "להתחייב/לבצע" },
    { word: "confirm", partOfSpeech: "verb", definition: "לאשר", example: "Please confirm your booking.", translation: "לאשר" },
    { word: "confront", partOfSpeech: "verb", definition: "להתעמת, להתמודד מול", example: "She confronted her fear.", translation: "להתעמת" },
    { word: "consume", partOfSpeech: "verb", definition: "לצרוך", example: "We consume too much sugar.", translation: "לצרוך" },
    { word: "contact", partOfSpeech: "verb", definition: "ליצור קשר", example: "Contact us for details.", translation: "ליצור קשר" },
    { word: "cope", partOfSpeech: "verb", definition: "להתמודד עם קושי", example: "How do you cope with stress?", translation: "להתמודד" },
    { word: "debate", partOfSpeech: "verb", definition: "להתווכח, לדון", example: "They debated for hours.", translation: "להתווכח/דיון" },
    { word: "delay", partOfSpeech: "verb", definition: "לעכב", example: "The flight was delayed.", translation: "לעכב/עיכוב" },
    { word: "demand", partOfSpeech: "verb", definition: "לדרוש", example: "Workers demand higher pay.", translation: "לדרוש/דרישה" },
    { word: "devote", partOfSpeech: "verb", definition: "להקדיש", example: "She devotes time to study.", translation: "להקדיש" },
    { word: "embrace", partOfSpeech: "verb", definition: "לאמץ בחום, או לחבק", example: "Embrace the change.", translation: "לאמץ/לחבק" },
    { word: "estimate", partOfSpeech: "verb", definition: "להעריך כמות בקירוב", example: "Estimate the cost.", translation: "להעריך/אומדן" },
  ],
  B2: [
    { word: "abstract", partOfSpeech: "adjective", definition: "מופשט, לא מוחשי", example: "An abstract concept.", translation: "מופשט" },
    { word: "acute", partOfSpeech: "adjective", definition: "חריף, חד", example: "An acute shortage.", translation: "חריף/חד" },
    { word: "adverse", partOfSpeech: "adjective", definition: "שלילי, מנוגד", example: "Adverse effects.", translation: "שלילי/מנוגד" },
    { word: "affirm", partOfSpeech: "verb", definition: "לאשש, לטעון בתוקף", example: "She affirmed her support.", translation: "לאשש/לטעון" },
    { word: "align", partOfSpeech: "verb", definition: "ליישר, להתאים בקו אחד", example: "Align the goals.", translation: "ליישר/להתאים" },
    { word: "allege", partOfSpeech: "verb", definition: "לטעון ללא הוכחה", example: "They allege fraud.", translation: "לטעון/לייחס" },
    { word: "amplify", partOfSpeech: "verb", definition: "להגביר, להעצים", example: "Social media amplifies rumours.", translation: "להגביר/להעצים" },
    { word: "analogous", partOfSpeech: "adjective", definition: "אנלוגי, מקביל בדמיון", example: "An analogous situation.", translation: "אנלוגי/מקביל" },
    { word: "apt", partOfSpeech: "adjective", definition: "הולם, או נוטה ל-", example: "An apt description.", translation: "הולם/נוטה" },
    { word: "aspire", partOfSpeech: "verb", definition: "לשאוף", example: "She aspires to lead.", translation: "לשאוף" },
    { word: "attain", partOfSpeech: "verb", definition: "להשיג, להגיע ל-", example: "Attain your goals.", translation: "להשיג" },
    { word: "autonomy", partOfSpeech: "noun", definition: "אוטונומיה, עצמאות", example: "Workers want autonomy.", translation: "אוטונומיה/עצמאות" },
    { word: "bolster", partOfSpeech: "verb", definition: "לחזק, לתמוך", example: "Evidence bolsters the claim.", translation: "לחזק/לתמוך" },
    { word: "brisk", partOfSpeech: "adjective", definition: "נמרץ, מהיר", example: "A brisk walk.", translation: "נמרץ/מהיר" },
    { word: "concur", partOfSpeech: "verb", definition: "להסכים, לחבור לדעה", example: "I concur with the report.", translation: "להסכים" },
    { word: "consecutive", partOfSpeech: "adjective", definition: "רצוף, ברצף", example: "Three consecutive wins.", translation: "רצוף" },
    { word: "conform", partOfSpeech: "verb", definition: "להתאים, לציית לנורמה", example: "Conform to the rules.", translation: "להתאים/לציית" },
    { word: "constraint", partOfSpeech: "noun", definition: "אילוץ, מגבלה", example: "Budget constraints.", translation: "אילוץ/מגבלה" },
    { word: "contingent", partOfSpeech: "adjective", definition: "תלוי ב-, מותנה", example: "Contingent on approval.", translation: "מותנה/תלוי ב-" },
    { word: "conversely", partOfSpeech: "adverb", definition: "לעומת זאת, להפך", example: "Conversely, costs fell.", translation: "לעומת זאת" },
    { word: "deficit", partOfSpeech: "noun", definition: "גירעון, חוסר", example: "A budget deficit.", translation: "גירעון/חוסר" },
    { word: "deviate", partOfSpeech: "verb", definition: "לסטות מהדרך הרגילה", example: "Don't deviate from the plan.", translation: "לסטות" },
    { word: "discrete", partOfSpeech: "adjective", definition: "נפרד, בדיד", example: "Three discrete stages.", translation: "נפרד/בדיד" },
    { word: "prevail", partOfSpeech: "verb", definition: "לגבור, או לשרור", example: "Common sense prevailed.", translation: "לגבור/לשרור" },
  ],
  C1: [
    { word: "abate", partOfSpeech: "verb", definition: "לשכוך, לדעוך בעוצמה", example: "The storm abated.", translation: "לשכוך/לדעוך" },
    { word: "aberration", partOfSpeech: "noun", definition: "חריגה מהרגיל", example: "A statistical aberration.", translation: "חריגה/סטייה" },
    { word: "abstain", partOfSpeech: "verb", definition: "להימנע במכוון", example: "He abstained from voting.", translation: "להימנע" },
    { word: "acquiesce", partOfSpeech: "verb", definition: "להסכים בשתיקה, להיכנע", example: "She acquiesced to the demand.", translation: "להסכים בשתיקה" },
    { word: "affable", partOfSpeech: "adjective", definition: "נעים הליכות וחביב", example: "An affable host.", translation: "נעים הליכות" },
    { word: "affinity", partOfSpeech: "noun", definition: "זיקה, חיבה טבעית", example: "An affinity for music.", translation: "זיקה/חיבה" },
    { word: "allude", partOfSpeech: "verb", definition: "לרמוז, להזכיר בעקיפין", example: "She alluded to the problem.", translation: "לרמוז/להזכיר" },
    { word: "ambivalence", partOfSpeech: "noun", definition: "רגשות מעורבים, דו-ערכיות", example: "Ambivalence about the move.", translation: "אמביוולנטיות" },
    { word: "amiable", partOfSpeech: "adjective", definition: "נעים וידידותי", example: "An amiable colleague.", translation: "נעים/ידידותי" },
    { word: "antecedent", partOfSpeech: "noun", definition: "מה שקדם; תקדים", example: "Historical antecedents.", translation: "קודם/תקדים" },
    { word: "apathy", partOfSpeech: "noun", definition: "אדישות, חוסר עניין", example: "Voter apathy.", translation: "אדישות" },
    { word: "appease", partOfSpeech: "verb", definition: "לפייס, להרגיע", example: "They tried to appease critics.", translation: "לפייס" },
    { word: "apprehensive", partOfSpeech: "adjective", definition: "חושש, מודאג מהעתיד", example: "Apprehensive about the test.", translation: "חושש/מודאג" },
    { word: "arbiter", partOfSpeech: "noun", definition: "בורר, פוסק מכריע", example: "An arbiter of taste.", translation: "בורר/פוסק" },
    { word: "articulate", partOfSpeech: "verb", definition: "לבטא בבהירות", example: "Articulate your concerns.", translation: "לבטא בבהירות" },
    { word: "assuage", partOfSpeech: "verb", definition: "להפיג, להקל (חשש/כאב)", example: "To assuage their fears.", translation: "להפיג/להקל" },
    { word: "attune", partOfSpeech: "verb", definition: "לכוונן, להתאים לרגישות", example: "Attuned to others' moods.", translation: "לכוונן/להתאים" },
    { word: "brevity", partOfSpeech: "noun", definition: "תמציתיות, קיצור", example: "Praised for its brevity.", translation: "תמציתיות/קיצור" },
    { word: "cordial", partOfSpeech: "adjective", definition: "לבבי, ידידותי ומנומס", example: "A cordial welcome.", translation: "לבבי" },
    { word: "discord", partOfSpeech: "noun", definition: "חוסר הרמוניה, מחלוקת", example: "Discord within the team.", translation: "מחלוקת/חוסר הרמוניה" },
  ],
  C2: [
    { word: "abscond", partOfSpeech: "verb", definition: "להימלט בחשאי (לרוב עם כסף)", example: "He absconded with the funds.", translation: "להימלט/להסתלק" },
    { word: "acclaim", partOfSpeech: "noun", definition: "תשבחות והוקרה פומבית", example: "Critical acclaim.", translation: "תשבחות/הוקרה" },
    { word: "adroit", partOfSpeech: "adjective", definition: "זריז ומיומן", example: "An adroit negotiator.", translation: "זריז/מיומן" },
    { word: "affluent", partOfSpeech: "adjective", definition: "אמיד, עשיר", example: "An affluent suburb.", translation: "אמיד/עשיר" },
    { word: "aggrieved", partOfSpeech: "adjective", definition: "נפגע, חש מקופח", example: "The aggrieved party.", translation: "נפגע/מקופח" },
    { word: "ascetic", partOfSpeech: "adjective", definition: "סגפני, מסתפק במועט", example: "An ascetic lifestyle.", translation: "סגפני" },
    { word: "aspersion", partOfSpeech: "noun", definition: "השמצה, הטלת דופי", example: "To cast aspersions.", translation: "השמצה/הטלת דופי" },
    { word: "avarice", partOfSpeech: "noun", definition: "חמדנות, בצע כסף", example: "Driven by avarice.", translation: "חמדנות/בצע" },
    { word: "bane", partOfSpeech: "noun", definition: "מקור צרה מתמשך", example: "The bane of my life.", translation: "מקור צרה/קללה" },
    { word: "beleaguered", partOfSpeech: "adjective", definition: "נצור, נתון בלחץ מתמשך", example: "A beleaguered minister.", translation: "נצור/מוטרד" },
    { word: "bequeath", partOfSpeech: "verb", definition: "להוריש בצוואה", example: "She bequeathed her estate.", translation: "להוריש" },
    { word: "blithe", partOfSpeech: "adjective", definition: "עליז וחסר דאגה (לעיתים שלילי)", example: "Blithe indifference.", translation: "עליז/חסר דאגה" },
    { word: "callow", partOfSpeech: "adjective", definition: "בוסר, צעיר וחסר ניסיון", example: "A callow youth.", translation: "בוסר/חסר ניסיון" },
    { word: "cessation", partOfSpeech: "noun", definition: "הפסקה, חדילה", example: "A cessation of hostilities.", translation: "הפסקה/חדילה" },
    { word: "connive", partOfSpeech: "verb", definition: "לקשור קשר, או לעצום עין מרשע", example: "They connived to deceive him.", translation: "לקשור קשר/לעצום עין" },
    { word: "decorous", partOfSpeech: "adjective", definition: "הולם, מנומס ומכובד", example: "Decorous behaviour.", translation: "הולם/מנומס" },
  ],
};
