// Round 4 of additional CEFR-leveled vocabulary, merged into WORD_BANKS by the
// generator. Combined set validated for duplicates/missing fields.
// Rarest C1/C2 Hebrew translations are best-effort pending native review.

export const MORE_WORDS4 = {
  A1: [
    { word: "spoon", partOfSpeech: "noun", definition: "כלי לאכילת מרק", example: "Eat with a spoon.", translation: "כף" },
    { word: "fork", partOfSpeech: "noun", definition: "כלי אוכל עם שיניים", example: "Use a fork.", translation: "מזלג" },
    { word: "cup", partOfSpeech: "noun", definition: "כלי לשתייה", example: "A cup of tea.", translation: "ספל/כוס" },
    { word: "plate", partOfSpeech: "noun", definition: "כלי שטוח לאוכל", example: "Put it on the plate.", translation: "צלחת" },
    { word: "bowl", partOfSpeech: "noun", definition: "כלי עמוק לאוכל", example: "A bowl of soup.", translation: "קערה" },
    { word: "banana", partOfSpeech: "noun", definition: "פרי צהוב וארוך", example: "I eat a banana.", translation: "בננה" },
    { word: "tomato", partOfSpeech: "noun", definition: "ירק אדום ועסיסי", example: "A red tomato.", translation: "עגבנייה" },
    { word: "potato", partOfSpeech: "noun", definition: "ירק שגדל באדמה", example: "Boiled potatoes.", translation: "תפוח אדמה" },
    { word: "chicken", partOfSpeech: "noun", definition: "עוף, גם כמאכל", example: "We ate chicken.", translation: "עוף" },
    { word: "meat", partOfSpeech: "noun", definition: "בשר של בעלי חיים", example: "I don't eat meat.", translation: "בשר" },
    { word: "juice", partOfSpeech: "noun", definition: "משקה מפירות", example: "Orange juice.", translation: "מיץ" },
    { word: "sugar", partOfSpeech: "noun", definition: "חומר מתוק לבן", example: "No sugar, please.", translation: "סוכר" },
    { word: "salt", partOfSpeech: "noun", definition: "תבלין לבן ומלוח", example: "Add some salt.", translation: "מלח" },
    { word: "dress", partOfSpeech: "noun", definition: "בגד לנשים", example: "A blue dress.", translation: "שמלה" },
    { word: "coat", partOfSpeech: "noun", definition: "בגד חם לחורף", example: "Wear your coat.", translation: "מעיל" },
    { word: "sock", partOfSpeech: "noun", definition: "מה שלובשים על כף הרגל מתחת לנעל", example: "A pair of socks.", translation: "גרב" },
    { word: "star", partOfSpeech: "noun", definition: "נקודת אור בשמי הלילה", example: "Look at the stars.", translation: "כוכב" },
    { word: "cloud", partOfSpeech: "noun", definition: "גוף לבן או אפור בשמיים", example: "A grey cloud.", translation: "ענן" },
    { word: "wind", partOfSpeech: "noun", definition: "אוויר שנע בחוץ", example: "A cold wind.", translation: "רוח" },
    { word: "snow", partOfSpeech: "noun", definition: "פתיתים לבנים שיורדים בחורף", example: "The snow is white.", translation: "שלג" },
    { word: "home", partOfSpeech: "noun", definition: "המקום שבו גרים", example: "I'm going home.", translation: "בית" },
    { word: "boat", partOfSpeech: "noun", definition: "כלי שט קטן", example: "A small boat.", translation: "סירה" },
    { word: "lake", partOfSpeech: "noun", definition: "גוף מים מתוקים מוקף יבשה", example: "We swam in the lake.", translation: "אגם" },
    { word: "hill", partOfSpeech: "noun", definition: "הר קטן", example: "A green hill.", translation: "גבעה" },
  ],
  A2: [
    { word: "clever", partOfSpeech: "adjective", definition: "פיקח, חכם", example: "A clever idea.", translation: "פיקח/חכם" },
    { word: "tidy", partOfSpeech: "adjective", definition: "מסודר ונקי", example: "Keep your room tidy.", translation: "מסודר" },
    { word: "messy", partOfSpeech: "adjective", definition: "מבולגן", example: "A messy desk.", translation: "מבולגן" },
    { word: "gentle", partOfSpeech: "adjective", definition: "עדין, רך", example: "A gentle voice.", translation: "עדין" },
    { word: "brave", partOfSpeech: "adjective", definition: "אמיץ", example: "A brave firefighter.", translation: "אמיץ" },
    { word: "shy", partOfSpeech: "adjective", definition: "ביישן", example: "She is too shy to speak.", translation: "ביישן" },
    { word: "kind", partOfSpeech: "adjective", definition: "אדיב, טוב לב", example: "A kind person.", translation: "אדיב/טוב לב" },
    { word: "rude", partOfSpeech: "adjective", definition: "גס רוח, לא מנומס", example: "Don't be rude.", translation: "גס רוח" },
    { word: "honest", partOfSpeech: "adjective", definition: "ישר, אומר אמת", example: "An honest answer.", translation: "ישר/כן" },
    { word: "serious", partOfSpeech: "adjective", definition: "רציני", example: "A serious problem.", translation: "רציני" },
    { word: "funny", partOfSpeech: "adjective", definition: "מצחיק", example: "A funny joke.", translation: "מצחיק" },
    { word: "terrible", partOfSpeech: "adjective", definition: "נורא, גרוע מאוד", example: "Terrible weather.", translation: "נורא" },
    { word: "wonderful", partOfSpeech: "adjective", definition: "נפלא, מצוין", example: "A wonderful trip.", translation: "נפלא" },
    { word: "perfect", partOfSpeech: "adjective", definition: "מושלם", example: "A perfect day.", translation: "מושלם" },
    { word: "special", partOfSpeech: "adjective", definition: "מיוחד", example: "A special gift.", translation: "מיוחד" },
    { word: "normal", partOfSpeech: "adjective", definition: "רגיל, נורמלי", example: "A normal day.", translation: "רגיל" },
    { word: "main", partOfSpeech: "adjective", definition: "עיקרי, ראשי", example: "The main road.", translation: "עיקרי/ראשי" },
    { word: "several", partOfSpeech: "determiner", definition: "כמה, מספר לא קטן", example: "Several people came.", translation: "כמה/אחדים" },
    { word: "various", partOfSpeech: "adjective", definition: "שונים ומגוונים", example: "Various colours.", translation: "שונים/מגוונים" },
    { word: "certain", partOfSpeech: "adjective", definition: "בטוח, או מסוים", example: "I'm certain it's true.", translation: "בטוח/מסוים" },
    { word: "proud", partOfSpeech: "adjective", definition: "גאה", example: "I'm proud of you.", translation: "גאה" },
    { word: "asleep", partOfSpeech: "adjective", definition: "ישן, במצב שינה", example: "The baby is asleep.", translation: "ישן/נרדם" },
    { word: "alone", partOfSpeech: "adjective", definition: "לבד, ללא אחרים", example: "She lives alone.", translation: "לבד" },
    { word: "calm", partOfSpeech: "adjective", definition: "רגוע, שקט ולא לחוץ", example: "Stay calm and breathe.", translation: "רגוע" },
  ],
  B1: [
    { word: "admire", partOfSpeech: "verb", definition: "להעריץ, להוקיר", example: "I admire her courage.", translation: "להעריץ" },
    { word: "announce", partOfSpeech: "verb", definition: "להכריז בפומבי", example: "They announced the winner.", translation: "להכריז" },
    { word: "apply", partOfSpeech: "verb", definition: "להגיש מועמדות, או ליישם", example: "I applied for the job.", translation: "להגיש מועמדות/ליישם" },
    { word: "approve", partOfSpeech: "verb", definition: "לאשר, להסכים", example: "The boss approved the plan.", translation: "לאשר" },
    { word: "argue", partOfSpeech: "verb", definition: "להתווכח, או לטעון", example: "They argue about money.", translation: "להתווכח/לטעון" },
    { word: "assist", partOfSpeech: "verb", definition: "לסייע, לעזור", example: "How can I assist you?", translation: "לסייע" },
    { word: "belong", partOfSpeech: "verb", definition: "להשתייך, להיות שייך ל-", example: "This book belongs to me.", translation: "להשתייך" },
    { word: "cause", partOfSpeech: "verb", definition: "לגרום למשהו", example: "Smoking causes disease.", translation: "לגרום" },
    { word: "celebrate", partOfSpeech: "verb", definition: "לחגוג", example: "We celebrated her birthday.", translation: "לחגוג" },
    { word: "combine", partOfSpeech: "verb", definition: "לשלב, לחבר יחד", example: "Combine the ingredients.", translation: "לשלב/לשלב יחד" },
    { word: "compete", partOfSpeech: "verb", definition: "להתחרות", example: "They compete for the prize.", translation: "להתחרות" },
    { word: "deserve", partOfSpeech: "verb", definition: "להגיע ל-, להיות ראוי", example: "You deserve a break.", translation: "להגיע ל-/ראוי" },
    { word: "earn", partOfSpeech: "verb", definition: "להרוויח כסף או הערכה", example: "She earns a good wage.", translation: "להרוויח" },
    { word: "enable", partOfSpeech: "verb", definition: "לאפשר, לתת יכולת", example: "The app enables sharing.", translation: "לאפשר" },
    { word: "expect", partOfSpeech: "verb", definition: "לצפות שמשהו יקרה", example: "We expect rain.", translation: "לצפות" },
    { word: "gather", partOfSpeech: "verb", definition: "לאסוף, או להתאסף", example: "A crowd gathered.", translation: "לאסוף/להתאסף" },
    { word: "guarantee", partOfSpeech: "verb", definition: "להבטיח, לערוב", example: "We guarantee quality.", translation: "להבטיח/לערוב" },
    { word: "insist", partOfSpeech: "verb", definition: "לעמוד על דעתו בתוקף", example: "He insisted on paying.", translation: "לעמוד על/להתעקש" },
    { word: "inspire", partOfSpeech: "verb", definition: "להשרות השראה", example: "Her story inspires me.", translation: "להשרות השראה" },
    { word: "intend", partOfSpeech: "verb", definition: "להתכוון לעשות משהו", example: "I intend to study law.", translation: "להתכוון" },
    { word: "limit", partOfSpeech: "verb", definition: "להגביל", example: "Limit your screen time.", translation: "להגביל/גבול" },
    { word: "organize", partOfSpeech: "verb", definition: "לארגן, לסדר", example: "She organized the event.", translation: "לארגן" },
    { word: "persuade", partOfSpeech: "verb", definition: "לשכנע מישהו", example: "He persuaded me to come.", translation: "לשכנע" },
    { word: "pretend", partOfSpeech: "verb", definition: "להעמיד פנים", example: "Don't pretend you don't know.", translation: "להעמיד פנים" },
  ],
  B2: [
    { word: "accommodate", partOfSpeech: "verb", definition: "להכיל, או להתאים לצורך", example: "The hall accommodates 200.", translation: "להכיל/להתאים" },
    { word: "adjacent", partOfSpeech: "adjective", definition: "סמוך, צמוד", example: "The adjacent room.", translation: "סמוך/צמוד" },
    { word: "amend", partOfSpeech: "verb", definition: "לתקן או לשנות מסמך/חוק", example: "They amended the contract.", translation: "לתקן/לשנות" },
    { word: "ascertain", partOfSpeech: "verb", definition: "לברר ולוודא עובדה", example: "We must ascertain the facts.", translation: "לברר/לוודא" },
    { word: "assert", partOfSpeech: "verb", definition: "לטעון בתוקף", example: "He asserted his innocence.", translation: "לטעון בתוקף" },
    { word: "augment", partOfSpeech: "verb", definition: "להגדיל, לתגבר", example: "Augment the team.", translation: "להגדיל/לתגבר" },
    { word: "categorize", partOfSpeech: "verb", definition: "לסווג לקבוצות", example: "Categorize the files.", translation: "לסווג" },
    { word: "cease", partOfSpeech: "verb", definition: "לחדול, להפסיק", example: "The rain ceased.", translation: "לחדול/לפסוק" },
    { word: "confer", partOfSpeech: "verb", definition: "להתייעץ, או להעניק", example: "They conferred for an hour.", translation: "להתייעץ/להעניק" },
    { word: "consolidate", partOfSpeech: "verb", definition: "לאחד ולחזק", example: "Consolidate the debts.", translation: "לאחד/לבסס" },
    { word: "correlate", partOfSpeech: "verb", definition: "להראות קשר או מתאם", example: "The two factors correlate.", translation: "להראות מתאם" },
    { word: "counteract", partOfSpeech: "verb", definition: "לפעול נגד, לנטרל", example: "Steps to counteract the effect.", translation: "לפעול נגד/לנטרל" },
    { word: "deem", partOfSpeech: "verb", definition: "לראות כ-, להחשיב", example: "It was deemed unsafe.", translation: "להחשיב/לראות כ-" },
    { word: "depict", partOfSpeech: "verb", definition: "לתאר או להציג בתמונה/מילים", example: "The film depicts war.", translation: "לתאר/להציג" },
    { word: "devise", partOfSpeech: "verb", definition: "להמציא, לתכנן", example: "They devised a plan.", translation: "להמציא/לתכנן" },
    { word: "differentiate", partOfSpeech: "verb", definition: "להבחין, להבדיל בין", example: "Differentiate fact from opinion.", translation: "להבחין/להבדיל" },
    { word: "disregard", partOfSpeech: "verb", definition: "להתעלם, לא להתחשב ב-", example: "Disregard the previous email.", translation: "להתעלם מ-" },
    { word: "dominate", partOfSpeech: "verb", definition: "לשלוט, להיות הגורם הבולט", example: "One team dominated the game.", translation: "לשלוט" },
    { word: "foresee", partOfSpeech: "verb", definition: "לחזות מראש", example: "No one foresaw the crisis.", translation: "לחזות מראש" },
    { word: "incur", partOfSpeech: "verb", definition: "לשאת בעלות או בתוצאה", example: "You may incur extra fees.", translation: "לשאת ב-/לספוג" },
    { word: "integral", partOfSpeech: "adjective", definition: "חיוני, בלתי נפרד", example: "An integral part of the plan.", translation: "חיוני/בלתי נפרד" },
    { word: "interval", partOfSpeech: "noun", definition: "מרווח של זמן או מרחב", example: "At regular intervals.", translation: "מרווח" },
    { word: "emphasis", partOfSpeech: "noun", definition: "דגש, חשיבות מיוחדת", example: "Emphasis on quality.", translation: "דגש" },
    { word: "outset", partOfSpeech: "noun", definition: "ההתחלה ממש", example: "From the outset.", translation: "ההתחלה" },
  ],
  C1: [
    { word: "abound", partOfSpeech: "verb", definition: "להימצא בשפע", example: "Rumours abound.", translation: "לשפוע/להימצא בשפע" },
    { word: "aloof", partOfSpeech: "adjective", definition: "מסויג ומרוחק", example: "He stayed aloof.", translation: "מסויג/מרוחק" },
    { word: "amenable", partOfSpeech: "adjective", definition: "נוח לשכנוע, נכון לשתף", example: "Amenable to change.", translation: "נכון/נוח לשכנוע" },
    { word: "austere", partOfSpeech: "adjective", definition: "צנוע ונוקשה, ללא קישוט", example: "An austere room.", translation: "צנוע/נוקשה" },
    { word: "belated", partOfSpeech: "adjective", definition: "מאוחר, באיחור", example: "A belated apology.", translation: "מאוחר/באיחור" },
    { word: "circumvent", partOfSpeech: "verb", definition: "לעקוף מכשול או חוק", example: "They circumvented the rules.", translation: "לעקוף" },
    { word: "commensurate", partOfSpeech: "adjective", definition: "תואם, יחסי בהיקפו", example: "Pay commensurate with skill.", translation: "תואם/יחסי" },
    { word: "concede", partOfSpeech: "verb", definition: "להודות, או לוותר", example: "He conceded the point.", translation: "להודות/לוותר" },
    { word: "conjecture", partOfSpeech: "noun", definition: "השערה ללא הוכחה", example: "Pure conjecture.", translation: "השערה/ניחוש" },
    { word: "connote", partOfSpeech: "verb", definition: "לרמז על משמעות נוספת", example: "The word connotes wealth.", translation: "לרמז על/להשתמע" },
    { word: "contend", partOfSpeech: "verb", definition: "לטעון, או להתמודד", example: "Critics contend otherwise.", translation: "לטעון/להתמודד" },
    { word: "covert", partOfSpeech: "adjective", definition: "נסתר, חשאי", example: "A covert operation.", translation: "נסתר/חשאי" },
    { word: "culpable", partOfSpeech: "adjective", definition: "אשם, נושא באחריות", example: "Held culpable for the loss.", translation: "אשם/נושא באחריות" },
    { word: "debunk", partOfSpeech: "verb", definition: "להפריך, לנפץ מיתוס", example: "The study debunks the myth.", translation: "להפריך" },
    { word: "decisive", partOfSpeech: "adjective", definition: "מכריע, או נחוש", example: "A decisive victory.", translation: "מכריע/נחוש" },
    { word: "deplete", partOfSpeech: "verb", definition: "לדלדל, לרוקן בהדרגה", example: "Stocks were depleted.", translation: "לדלדל/לרוקן" },
    { word: "deride", partOfSpeech: "verb", definition: "ללעוג, לבוז", example: "Critics derided the idea.", translation: "ללעוג" },
    { word: "despondent", partOfSpeech: "adjective", definition: "מיואש, שרוי בדכדוך", example: "He felt despondent.", translation: "מיואש" },
    { word: "diffuse", partOfSpeech: "verb", definition: "לפזר, להפיץ", example: "Light diffuses through it.", translation: "לפזר/להפיץ" },
    { word: "divulge", partOfSpeech: "verb", definition: "לחשוף מידע סודי", example: "He refused to divulge names.", translation: "לחשוף/לגלות" },
    { word: "elicit", partOfSpeech: "verb", definition: "לחלץ, לעורר תגובה", example: "The question elicited laughter.", translation: "לחלץ/לעורר" },
    { word: "emulate", partOfSpeech: "verb", definition: "לחקות מתוך הערכה", example: "Students emulate their mentors.", translation: "לחקות/לשאוף לדמות" },
    { word: "enduring", partOfSpeech: "adjective", definition: "מתמשך, בר-קיימא", example: "An enduring friendship.", translation: "מתמשך/בר-קיימא" },
    { word: "equitable", partOfSpeech: "adjective", definition: "הוגן ושוויוני", example: "An equitable solution.", translation: "הוגן/שוויוני" },
  ],
  C2: [
    { word: "acrimony", partOfSpeech: "noun", definition: "מרירות ועוינות בחילופי דברים", example: "The debate ended in acrimony.", translation: "מרירות/עוינות" },
    { word: "alacrity", partOfSpeech: "noun", definition: "זריזות ונכונות שמחה", example: "He agreed with alacrity.", translation: "זריזות/נכונות" },
    { word: "amorphous", partOfSpeech: "adjective", definition: "חסר צורה ברורה", example: "An amorphous mass.", translation: "חסר צורה/אמורפי" },
    { word: "anathema", partOfSpeech: "noun", definition: "דבר שנוא ומתועב", example: "Censorship is anathema to her.", translation: "דבר שנוא/חרם" },
    { word: "antithesis", partOfSpeech: "noun", definition: "ההיפוך הגמור של דבר", example: "The very antithesis of art.", translation: "היפוך גמור" },
    { word: "assiduous", partOfSpeech: "adjective", definition: "חרוץ ושקדן", example: "Assiduous research.", translation: "חרוץ/שקדן" },
    { word: "bourgeois", partOfSpeech: "adjective", definition: "בורגני, של מעמד הביניים", example: "Bourgeois values.", translation: "בורגני" },
    { word: "bucolic", partOfSpeech: "adjective", definition: "כפרי, פסטורלי ושלֵו", example: "A bucolic landscape.", translation: "כפרי/פסטורלי" },
    { word: "cantankerous", partOfSpeech: "adjective", definition: "רגזן ונרגן", example: "A cantankerous old man.", translation: "רגזן/נרגן" },
    { word: "cognizant", partOfSpeech: "adjective", definition: "מודע ל-, ער ל-", example: "Cognizant of the risks.", translation: "מודע ל-" },
    { word: "conflagration", partOfSpeech: "noun", definition: "תבערה גדולה; שריפה רחבת היקף", example: "A vast conflagration.", translation: "תבערה גדולה" },
    { word: "consternation", partOfSpeech: "noun", definition: "תדהמה מהולה בחרדה", example: "To my consternation.", translation: "תדהמה/חרדה" },
    { word: "denouement", partOfSpeech: "noun", definition: "סיומת — התרת העלילה", example: "A surprising denouement.", translation: "סיומת/התרה" },
    { word: "dilettante", partOfSpeech: "noun", definition: "חובבן שעוסק בשטחיות", example: "A mere dilettante.", translation: "חובבן" },
    { word: "disabuse", partOfSpeech: "verb", definition: "להוציא מטעות או מאשליה", example: "Let me disabuse you of that.", translation: "להוציא מטעות" },
    { word: "effusive", partOfSpeech: "adjective", definition: "נלהב וגודש רגשות", example: "Effusive praise.", translation: "נלהב/גודש רגשות" },
    { word: "egalitarian", partOfSpeech: "adjective", definition: "שוויוני, דוגל בשוויון", example: "An egalitarian society.", translation: "שוויוני" },
    { word: "enervate", partOfSpeech: "verb", definition: "להתיש, לרוקן מכוח", example: "The heat enervated us.", translation: "להתיש" },
    { word: "equivocate", partOfSpeech: "verb", definition: "להתחמק בדיבור דו-משמעי", example: "Stop equivocating.", translation: "להתחמק/לדבר דו-משמעית" },
    { word: "extol", partOfSpeech: "verb", definition: "להלל, לשבח מאוד", example: "They extolled his virtues.", translation: "להלל/לשבח" },
    { word: "facetious", partOfSpeech: "adjective", definition: "מתלוצץ שלא במקום", example: "A facetious comment.", translation: "התלוצצות/לא רציני" },
    { word: "fortuitous", partOfSpeech: "adjective", definition: "מקרי, ולרוב בר-מזל", example: "A fortuitous meeting.", translation: "מקרי/בר-מזל" },
    { word: "grandiloquent", partOfSpeech: "adjective", definition: "מליצי ומנופח בלשונו", example: "A grandiloquent speech.", translation: "מליצי/נמלץ" },
    { word: "idiosyncrasy", partOfSpeech: "noun", definition: "מוזרות או תכונה ייחודית לאדם", example: "One of his idiosyncrasies.", translation: "מוזרות/תכונה ייחודית" },
  ],
};
