// Round 9 — unique content words not in earlier rounds.

export const MORE_WORDS9 = {
  A1: [
    { word: "full", partOfSpeech: "adjective", definition: "מלא, אין מקום", example: "The bus is full.", translation: "מלא" },
    { word: "wake up", partOfSpeech: "verb", definition: "להתעורר משינה", example: "I wake up at seven.", translation: "להתעורר" },
    { word: "near", partOfSpeech: "preposition", definition: "קרוב ל-", example: "She lives near my house.", translation: "ליד" },
    { word: "together", partOfSpeech: "adverb", definition: "ביחד", example: "We go together.", translation: "ביחד" },
    { word: "homework", partOfSpeech: "noun", definition: "שיעורי בית", example: "I do my homework.", translation: "שיעורי בית" },
    { word: "eggs", partOfSpeech: "noun", definition: "ביצים", example: "I buy eggs.", translation: "ביצים" },
    { word: "apples", partOfSpeech: "noun", definition: "תפוחים", example: "I like apples.", translation: "תפוחים" },
    { word: "cook", partOfSpeech: "verb", definition: "לבשל", example: "We cook lunch.", translation: "לבשל" },
    { word: "park", partOfSpeech: "noun", definition: "פארק", example: "We play in the park.", translation: "פארק" },
    { word: "football", partOfSpeech: "noun", definition: "כדורגל", example: "I play football.", translation: "כדורגל" },
    { word: "heavy", partOfSpeech: "adjective", definition: "כבד", example: "The bag is heavy.", translation: "כבד" },
    { word: "carry", partOfSpeech: "verb", definition: "לשאת", example: "I carry the bag.", translation: "לשאת" },
    { word: "raining", partOfSpeech: "verb", definition: "יורד גשם", example: "It is raining.", translation: "יורד גשם" },
    { word: "outside", partOfSpeech: "adverb", definition: "בחוץ", example: "Play outside.", translation: "בחוץ" },
    { word: "draw", partOfSpeech: "verb", definition: "לצייר", example: "I draw pictures.", translation: "לצייר" },
    { word: "birthday", partOfSpeech: "noun", definition: "יום הולדת", example: "Today is my birthday.", translation: "יום הולדת" },
    { word: "favourite", partOfSpeech: "adjective", definition: "אהוב", example: "My favourite food.", translation: "אהוב" },
    { word: "zoo", partOfSpeech: "noun", definition: "גן חיות", example: "We go to the zoo.", translation: "גן חיות" },
    { word: "funny", partOfSpeech: "adjective", definition: "מצחיק", example: "He is funny.", translation: "מצחיק" },
    { word: "doctor", partOfSpeech: "noun", definition: "רופא", example: "See a doctor.", translation: "רופא" },
    { word: "hurt", partOfSpeech: "verb", definition: "לכאוב", example: "My head hurts.", translation: "לכאוב" },
    { word: "rest", partOfSpeech: "verb", definition: "לנוח", example: "You must rest.", translation: "לנוח" },
    { word: "quiet", partOfSpeech: "adjective", definition: "שקט", example: "A quiet room.", translation: "שקט" },
    { word: "pot", partOfSpeech: "noun", definition: "סיר", example: "A big pot.", translation: "סיר" },
    { word: "smell", partOfSpeech: "verb", definition: "להריח", example: "It smells good.", translation: "להריח" },
    { word: "winter", partOfSpeech: "noun", definition: "חורף", example: "Cold winter.", translation: "חורף" },
    { word: "warm", partOfSpeech: "adjective", definition: "חמים", example: "A warm coat.", translation: "חמים" },
    { word: "snowman", partOfSpeech: "noun", definition: "איש שלג", example: "Make a snowman.", translation: "איש שלג" },
    { word: "shoes", partOfSpeech: "noun", definition: "נעליים", example: "New shoes.", translation: "נעליים" },
    { word: "lace", partOfSpeech: "noun", definition: "שרוך", example: "White laces.", translation: "שרוך" },
    { word: "feed", partOfSpeech: "verb", definition: "להאכיל", example: "I feed the cat.", translation: "להאכיל" },
    { word: "beach", partOfSpeech: "noun", definition: "חוף ים", example: "Go to the beach.", translation: "חוף ים" },
    { word: "sand", partOfSpeech: "noun", definition: "חול", example: "Sand on the beach.", translation: "חול" },
    { word: "swim", partOfSpeech: "verb", definition: "לשחות", example: "We swim.", translation: "לשחות" },
    { word: "grandpa", partOfSpeech: "noun", definition: "סבא", example: "My grandpa.", translation: "סבא" },
    { word: "sweet", partOfSpeech: "adjective", definition: "מתוק", example: "Sweet tomatoes.", translation: "מתוק" },
    { word: "candle", partOfSpeech: "noun", definition: "נר", example: "Seven candles.", translation: "נר" },
    { word: "blow out", partOfSpeech: "phrase", definition: "לכבות בנשיפה", example: "Blow out the candles.", translation: "לכבות" },
    { word: "teddy bear", partOfSpeech: "noun", definition: "דובון", example: "A teddy bear.", translation: "דובון" },
    { word: "hug", partOfSpeech: "verb", definition: "לחבק", example: "I hug him.", translation: "לחבק" },
    { word: "farm", partOfSpeech: "noun", definition: "חווה", example: "On the farm.", translation: "חווה" },
    { word: "corn", partOfSpeech: "noun", definition: "תירס", example: "Corn for chickens.", translation: "תירס" },
    { word: "share", partOfSpeech: "verb", definition: "לחלוק", example: "We share snacks.", translation: "לחלוק" },
    { word: "laugh", partOfSpeech: "verb", definition: "לצחוק", example: "He makes me laugh.", translation: "לצחוק" },
    { word: "bike", partOfSpeech: "noun", definition: "אופניים", example: "Ride a bike.", translation: "אופניים" },
    { word: "brush", partOfSpeech: "verb", definition: "לצחצח", example: "Brush your teeth.", translation: "לצחצח" },
    { word: "healthy", partOfSpeech: "adjective", definition: "בריא", example: "Healthy food.", translation: "בריא" },
    { word: "throw", partOfSpeech: "verb", definition: "לזרוק", example: "Throw the ball.", translation: "לזרוק" },
    { word: "sunday", partOfSpeech: "noun", definition: "יום ראשון", example: "On Sunday.", translation: "יום ראשון" },
    { word: "saturday", partOfSpeech: "noun", definition: "שבת", example: "On Saturday.", translation: "שבת" },
    { word: "friday", partOfSpeech: "noun", definition: "יום שישי", example: "On Friday.", translation: "יום שישי" },
    { word: "monday", partOfSpeech: "noun", definition: "יום שני", example: "On Monday.", translation: "יום שני" },
    { word: "delicious", partOfSpeech: "adjective", definition: "טעים מאוד", example: "It is delicious!", translation: "טעים" },
    { word: "story", partOfSpeech: "noun", definition: "סיפור", example: "A funny story.", translation: "סיפור" },
    { word: "farmer", partOfSpeech: "noun", definition: "חקלאי", example: "The farmer.", translation: "חקלאי" },
    { word: "great", partOfSpeech: "adjective", definition: "נהדר", example: "A great day.", translation: "נהדר" },
    { word: "little", partOfSpeech: "adjective", definition: "קטן / מעט", example: "A little brother.", translation: "קטן" },
    { word: "best", partOfSpeech: "adjective", definition: "הכי טוב", example: "My best friend.", translation: "הכי טוב" },
    { word: "snack", partOfSpeech: "noun", definition: "חטיף", example: "Share snacks.", translation: "חטיף" },
    { word: "often", partOfSpeech: "adverb", definition: "לעיתים קרובות", example: "I often walk.", translation: "לעיתים קרובות" },
    { word: "always", partOfSpeech: "adverb", definition: "תמיד", example: "She always smiles.", translation: "תמיד" },
    { word: "sometimes", partOfSpeech: "adverb", definition: "לפעמים", example: "I sometimes read.", translation: "לפעמים" },
    { word: "never", partOfSpeech: "adverb", definition: "לעולם לא", example: "I never run.", translation: "לעולם לא" },
    { word: "half", partOfSpeech: "noun", definition: "חצי", example: "Half past eight.", translation: "חצי" },
    { word: "drop", partOfSpeech: "noun", definition: "טיפה", example: "Rain drops.", translation: "טיפה" },
    { word: "river", partOfSpeech: "noun", definition: "נהר", example: "Near the river.", translation: "נהר" },
    { word: "town", partOfSpeech: "noun", definition: "עיירה", example: "A small town.", translation: "עיירה" },
    { word: "village", partOfSpeech: "noun", definition: "כפר", example: "A quiet village.", translation: "כפר" },
    { word: "road", partOfSpeech: "noun", definition: "כביש", example: "On the road.", translation: "כביש" },
    { word: "film", partOfSpeech: "noun", definition: "סרט", example: "Watch a film.", translation: "סרט" },
    { word: "photo", partOfSpeech: "noun", definition: "תמונה", example: "Take a photo.", translation: "תמונה" },
    { word: "newspaper", partOfSpeech: "noun", definition: "עיתון", example: "Read the newspaper.", translation: "עיתון" },
    { word: "magazine", partOfSpeech: "noun", definition: "מגזין", example: "A fashion magazine.", translation: "מגזין" },
    { word: "job", partOfSpeech: "noun", definition: "עבודה", example: "A good job.", translation: "עבודה" },
    { word: "money", partOfSpeech: "noun", definition: "כסף", example: "I need money.", translation: "כסף" },
    { word: "price", partOfSpeech: "noun", definition: "מחיר", example: "The price is low.", translation: "מחיר" },
    { word: "cheap", partOfSpeech: "adjective", definition: "זול", example: "It is cheap.", translation: "זול" },
    { word: "free", partOfSpeech: "adjective", definition: "חינם", example: "It is free.", translation: "חינם" },
    { word: "ticket", partOfSpeech: "noun", definition: "כרטיס", example: "Buy a ticket.", translation: "כרטיס" },
    { word: "holiday", partOfSpeech: "noun", definition: "חופשה", example: "A summer holiday.", translation: "חופשה" },
    { word: "trip", partOfSpeech: "noun", definition: "טיול", example: "A school trip.", translation: "טיול" },
    { word: "station", partOfSpeech: "noun", definition: "תחנה", example: "At the station.", translation: "תחנה" },
    { word: "airport", partOfSpeech: "noun", definition: "שדה תעופה", example: "At the airport.", translation: "שדה תעופה" },
    { word: "hotel", partOfSpeech: "noun", definition: "מלון", example: "A small hotel.", translation: "מלון" },
    { word: "restaurant", partOfSpeech: "noun", definition: "מסעדה", example: "At a restaurant.", translation: "מסעדה" },
    { word: "cafe", partOfSpeech: "noun", definition: "בית קפה", example: "Meet at the cafe.", translation: "בית קפה" },
    { word: "hospital", partOfSpeech: "noun", definition: "בית חולים", example: "Go to hospital.", translation: "בית חולים" },
    { word: "library", partOfSpeech: "noun", definition: "ספרייה", example: "At the library.", translation: "ספרייה" },
    { word: "museum", partOfSpeech: "noun", definition: "מוזיאון", example: "Visit the museum.", translation: "מוזיאון" },
    { word: "cinema", partOfSpeech: "noun", definition: "קולנוע", example: "Go to the cinema.", translation: "קולנוע" },
    { word: "sport", partOfSpeech: "noun", definition: "ספורט", example: "I like sport.", translation: "ספורט" },
    { word: "team", partOfSpeech: "noun", definition: "קבוצה", example: "Our team won.", translation: "קבוצה" },
    { word: "match", partOfSpeech: "noun", definition: "משחק", example: "A football match.", translation: "משחק" },
    { word: "win", partOfSpeech: "verb", definition: "לנצח", example: "We win!", translation: "לנצח" },
    { word: "lose", partOfSpeech: "verb", definition: "להפסיד", example: "We lose.", translation: "להפסיד" },
    { word: "strong", partOfSpeech: "adjective", definition: "חזק", example: "Strong teeth.", translation: "חזק" },
    { word: "hungry", partOfSpeech: "adjective", definition: "רעב", example: "I am hungry.", translation: "רעב" },
    { word: "thirsty", partOfSpeech: "adjective", definition: "צמא", example: "I am thirsty.", translation: "צמא" },
    { word: "sick", partOfSpeech: "adjective", definition: "חולה", example: "I feel sick.", translation: "חולה" },
    { word: "well", partOfSpeech: "adjective", definition: "בסדר / בריא", example: "I feel well.", translation: "בסדר" },
    { word: "afraid", partOfSpeech: "adjective", definition: "מפחד", example: "I am afraid.", translation: "מפחד" },
    { word: "angry", partOfSpeech: "adjective", definition: "כועס", example: "He is angry.", translation: "כועס" },
    { word: "excited", partOfSpeech: "adjective", definition: "נרגש", example: "I am excited.", translation: "נרגש" },
    { word: "bored", partOfSpeech: "adjective", definition: "משועמם", example: "I am bored.", translation: "משועמם" },
    { word: "surprised", partOfSpeech: "adjective", definition: "מופתע", example: "I am surprised.", translation: "מופתע" },
    { word: "worried", partOfSpeech: "adjective", definition: "דואג", example: "Don't be worried.", translation: "דואג" },
    { word: "proud", partOfSpeech: "adjective", definition: "גאה", example: "I am proud.", translation: "גאה" },
  ],
  A2: [
    { word: "decorate", partOfSpeech: "verb", definition: "לקשט", example: "Decorate the room.", translation: "לקשט" },
    { word: "celebrate", partOfSpeech: "verb", definition: "לחגוג", example: "We celebrate today.", translation: "לחגוג" },
    { word: "explain", partOfSpeech: "verb", definition: "להסביר", example: "Please explain.", translation: "להסביר" },
    { word: "compare", partOfSpeech: "verb", definition: "להשוות", example: "Compare the prices.", translation: "להשוות" },
    { word: "improve", partOfSpeech: "verb", definition: "לשפר", example: "Improve your English.", translation: "לשפר" },
    { word: "achieve", partOfSpeech: "verb", definition: "להשיג", example: "Achieve your goals.", translation: "להשיג" },
    { word: "succeed", partOfSpeech: "verb", definition: "להצליח", example: "You will succeed.", translation: "להצליח" },
    { word: "fail", partOfSpeech: "verb", definition: "להיכשל", example: "Don't fail the test.", translation: "להיכשל" },
    { word: "notice", partOfSpeech: "verb", definition: "לשים לב", example: "Did you notice?", translation: "לשים לב" },
    { word: "realize", partOfSpeech: "verb", definition: "להבין / לקלוט", example: "I realize now.", translation: "להבין" },
    { word: "suggest", partOfSpeech: "verb", definition: "להציע", example: "I suggest pizza.", translation: "להציע" },
    { word: "recommend", partOfSpeech: "verb", definition: "להמליץ", example: "I recommend this book.", translation: "להמליץ" },
    { word: "complain", partOfSpeech: "verb", definition: "להתלונן", example: "Don't complain.", translation: "להתלונן" },
    { word: "apologize", partOfSpeech: "verb", definition: "להתנצל", example: "I apologize.", translation: "להתנצל" },
  ],
  B1: [
    { word: "consequence", partOfSpeech: "noun", definition: "תוצאה", example: "Think of the consequence.", translation: "תוצאה" },
    { word: "evidence", partOfSpeech: "noun", definition: "ראיה", example: "There is evidence.", translation: "ראיה" },
    { word: "pollution", partOfSpeech: "noun", definition: "זיהום", example: "Air pollution.", translation: "זיהום" },
    { word: "resource", partOfSpeech: "noun", definition: "משאב", example: "Natural resources.", translation: "משאב" },
    { word: "economy", partOfSpeech: "noun", definition: "כלכלה", example: "The economy grows.", translation: "כלכלה" },
  ],
  B2: [
  ],
  C1: [
  ],
  C2: [
  ],
};
