// Round 2 of additional CEFR-leveled vocabulary, merged into WORD_BANKS by the
// generator alongside wordbank-extra.mjs. Same conventions; the generator
// validates the combined set for duplicates and missing fields.
//
// Caveat: the rarest C1/C2 Hebrew translations are best-effort and worth a
// native-speaker review before production use.

export const MORE_WORDS2 = {
  A1: [
    { word: "teacher", partOfSpeech: "noun", definition: "אדם שמלמד תלמידים", example: "Our teacher is kind.", translation: "מורה" },
    { word: "student", partOfSpeech: "noun", definition: "אדם שלומד", example: "She is a good student.", translation: "תלמיד/סטודנט" },
    { word: "pen", partOfSpeech: "noun", definition: "כלי כתיבה עם דיו", example: "Can I borrow a pen?", translation: "עט" },
    { word: "pencil", partOfSpeech: "noun", definition: "כלי כתיבה מעץ וגרפיט", example: "Write with a pencil.", translation: "עיפרון" },
    { word: "bag", partOfSpeech: "noun", definition: "כלי לנשיאת חפצים", example: "My bag is heavy.", translation: "תיק" },
    { word: "shoe", partOfSpeech: "noun", definition: "מה שנועלים על כף הרגל", example: "These shoes are new.", translation: "נעל" },
    { word: "shirt", partOfSpeech: "noun", definition: "פריט לבוש לפלג הגוף העליון", example: "He wore a white shirt.", translation: "חולצה" },
    { word: "hat", partOfSpeech: "noun", definition: "כיסוי לראש", example: "Put on your hat.", translation: "כובע" },
    { word: "ball", partOfSpeech: "noun", definition: "כדור עגול למשחק", example: "Throw the ball.", translation: "כדור" },
    { word: "game", partOfSpeech: "noun", definition: "משחק עם חוקים", example: "Let's play a game.", translation: "משחק" },
    { word: "music", partOfSpeech: "noun", definition: "צלילים שמנגנים או שרים", example: "I love this music.", translation: "מוזיקה" },
    { word: "song", partOfSpeech: "noun", definition: "יצירה ששרים", example: "Sing me a song.", translation: "שיר" },
    { word: "color", partOfSpeech: "noun", definition: "גוון כמו אדום או כחול", example: "What's your favourite color?", translation: "צבע" },
    { word: "animal", partOfSpeech: "noun", definition: "יצור חי שאינו צמח", example: "A lion is a big animal.", translation: "חיה" },
    { word: "horse", partOfSpeech: "noun", definition: "חיה גדולה שרוכבים עליה", example: "The horse is fast.", translation: "סוס" },
    { word: "cow", partOfSpeech: "noun", definition: "חיה שנותנת חלב", example: "The cow eats grass.", translation: "פרה" },
    { word: "flower", partOfSpeech: "noun", definition: "החלק היפה והצבעוני של צמח", example: "She picked a flower.", translation: "פרח" },
    { word: "garden", partOfSpeech: "noun", definition: "שטח עם צמחים ליד הבית", example: "We sat in the garden.", translation: "גינה" },
    { word: "kitchen", partOfSpeech: "noun", definition: "החדר שבו מבשלים", example: "Mum is in the kitchen.", translation: "מטבח" },
    { word: "street", partOfSpeech: "noun", definition: "דרך בעיר עם בתים", example: "Cross the street carefully.", translation: "רחוב" },
    { word: "shop", partOfSpeech: "noun", definition: "מקום שבו קונים דברים", example: "The shop is open.", translation: "חנות" },
    { word: "bus", partOfSpeech: "noun", definition: "כלי תחבורה ציבורי גדול", example: "I take the bus to work.", translation: "אוטובוס" },
    { word: "train", partOfSpeech: "noun", definition: "כלי תחבורה על מסילה", example: "The train is fast.", translation: "רכבת" },
    { word: "sky", partOfSpeech: "noun", definition: "החלל מעל הארץ", example: "The sky is clear.", translation: "שמיים" },
  ],
  A2: [
    { word: "ready", partOfSpeech: "adjective", definition: "מוכן לעשות משהו", example: "Are you ready to go?", translation: "מוכן" },
    { word: "able", partOfSpeech: "adjective", definition: "מסוגל לעשות משהו", example: "She is able to drive.", translation: "מסוגל" },
    { word: "sure", partOfSpeech: "adjective", definition: "בטוח במשהו", example: "I'm sure it's correct.", translation: "בטוח" },
    { word: "real", partOfSpeech: "adjective", definition: "אמיתי, לא מזויף", example: "Is this gold real?", translation: "אמיתי" },
    { word: "true", partOfSpeech: "adjective", definition: "נכון, מתאים למציאות", example: "The story is true.", translation: "נכון/אמת" },
    { word: "possible", partOfSpeech: "adjective", definition: "אפשרי, יכול לקרות", example: "Is it possible to change?", translation: "אפשרי" },
    { word: "impossible", partOfSpeech: "adjective", definition: "בלתי אפשרי", example: "It's impossible to finish today.", translation: "בלתי אפשרי" },
    { word: "free", partOfSpeech: "adjective", definition: "חופשי, או ללא תשלום", example: "Entry is free.", translation: "חופשי/חינם" },
    { word: "full", partOfSpeech: "adjective", definition: "מלא, אין מקום פנוי", example: "The glass is full.", translation: "מלא" },
    { word: "empty", partOfSpeech: "adjective", definition: "ריק, ללא תוכן", example: "The room was empty.", translation: "ריק" },
    { word: "heavy", partOfSpeech: "adjective", definition: "כבד, קשה להרים", example: "This box is heavy.", translation: "כבד" },
    { word: "light", partOfSpeech: "adjective", definition: "קל; או בהיר", example: "The bag is light.", translation: "קל/בהיר" },
    { word: "clean", partOfSpeech: "adjective", definition: "נקי, ללא לכלוך", example: "The kitchen is clean.", translation: "נקי" },
    { word: "dirty", partOfSpeech: "adjective", definition: "מלוכלך", example: "My shoes are dirty.", translation: "מלוכלך" },
    { word: "loud", partOfSpeech: "adjective", definition: "רועש, בקול חזק", example: "The music is too loud.", translation: "רועש" },
    { word: "strong", partOfSpeech: "adjective", definition: "חזק, בעל כוח", example: "He is very strong.", translation: "חזק" },
    { word: "weak", partOfSpeech: "adjective", definition: "חלש, חסר כוח", example: "I feel weak today.", translation: "חלש" },
    { word: "rich", partOfSpeech: "adjective", definition: "עשיר, בעל הרבה כסף", example: "A rich businessman.", translation: "עשיר" },
    { word: "poor", partOfSpeech: "adjective", definition: "עני, בעל מעט כסף", example: "They were very poor.", translation: "עני" },
    { word: "foreign", partOfSpeech: "adjective", definition: "זר, ממדינה אחרת", example: "I speak two foreign languages.", translation: "זר" },
    { word: "local", partOfSpeech: "adjective", definition: "מקומי, מהאזור", example: "We ate at a local restaurant.", translation: "מקומי" },
    { word: "modern", partOfSpeech: "adjective", definition: "מודרני, חדיש", example: "A modern building.", translation: "מודרני" },
    { word: "ago", partOfSpeech: "adverb", definition: "לפני (זמן שחלף)", example: "I saw her two days ago.", translation: "לפני (זמן)" },
    { word: "together", partOfSpeech: "adverb", definition: "ביחד, יחדיו", example: "We work together.", translation: "ביחד" },
  ],
  B1: [
    { word: "ability", partOfSpeech: "noun", definition: "יכולת לעשות משהו", example: "She has the ability to lead.", translation: "יכולת" },
    { word: "accept", partOfSpeech: "verb", definition: "לקבל הצעה או עובדה", example: "He accepted the offer.", translation: "לקבל" },
    { word: "admit", partOfSpeech: "verb", definition: "להודות במשהו", example: "She admitted her mistake.", translation: "להודות" },
    { word: "arrange", partOfSpeech: "verb", definition: "לארגן או לסדר מראש", example: "I arranged a meeting.", translation: "לארגן/לסדר" },
    { word: "attend", partOfSpeech: "verb", definition: "להשתתף או להיות נוכח", example: "Will you attend the class?", translation: "להשתתף/לנכוח" },
    { word: "attract", partOfSpeech: "verb", definition: "למשוך תשומת לב או עניין", example: "The show attracts tourists.", translation: "למשוך" },
    { word: "blame", partOfSpeech: "verb", definition: "להאשים מישהו בבעיה", example: "Don't blame me.", translation: "להאשים" },
    { word: "claim", partOfSpeech: "verb", definition: "לטעון שמשהו נכון", example: "He claims to be innocent.", translation: "לטעון" },
    { word: "compare", partOfSpeech: "verb", definition: "להשוות בין דברים", example: "Compare the two plans.", translation: "להשוות" },
    { word: "complete", partOfSpeech: "verb", definition: "להשלים, לסיים", example: "Complete the form.", translation: "להשלים" },
    { word: "concern", partOfSpeech: "noun", definition: "דאגה או עניין", example: "Safety is my main concern.", translation: "דאגה/עניין" },
    { word: "confident", partOfSpeech: "adjective", definition: "בטוח בעצמו", example: "She felt confident.", translation: "בטוח בעצמו" },
    { word: "connect", partOfSpeech: "verb", definition: "לחבר בין דברים", example: "Connect the cable here.", translation: "לחבר" },
    { word: "contain", partOfSpeech: "verb", definition: "להכיל בתוכו", example: "The box contains books.", translation: "להכיל" },
    { word: "continue", partOfSpeech: "verb", definition: "להמשיך", example: "Please continue reading.", translation: "להמשיך" },
    { word: "convince", partOfSpeech: "verb", definition: "לשכנע מישהו", example: "He convinced me to stay.", translation: "לשכנע" },
    { word: "create", partOfSpeech: "verb", definition: "ליצור משהו חדש", example: "She created a website.", translation: "ליצור" },
    { word: "deliver", partOfSpeech: "verb", definition: "למסור או לספק", example: "They deliver pizza fast.", translation: "לספק/למסור" },
    { word: "deny", partOfSpeech: "verb", definition: "להכחיש משהו", example: "He denied the accusation.", translation: "להכחיש" },
    { word: "discuss", partOfSpeech: "verb", definition: "לדון בנושא", example: "Let's discuss the plan.", translation: "לדון" },
    { word: "doubt", partOfSpeech: "noun", definition: "ספק, חוסר ודאות", example: "I have no doubt.", translation: "ספק" },
    { word: "employ", partOfSpeech: "verb", definition: "להעסיק עובד", example: "The firm employs 50 people.", translation: "להעסיק" },
    { word: "involve", partOfSpeech: "verb", definition: "לכלול או לערב", example: "The job involves travel.", translation: "לכלול/לערב" },
    { word: "purchase", partOfSpeech: "verb", definition: "לקנות (רשמי)", example: "You can purchase tickets online.", translation: "לרכוש" },
  ],
  B2: [
    { word: "acknowledge", partOfSpeech: "verb", definition: "להכיר בעובדה או להודות בה", example: "He acknowledged the error.", translation: "להכיר ב-/להודות" },
    { word: "adequate", partOfSpeech: "adjective", definition: "מספק, הולם את הצורך", example: "The food was adequate.", translation: "מספק/הולם" },
    { word: "alter", partOfSpeech: "verb", definition: "לשנות במידה מסוימת", example: "We altered the design.", translation: "לשנות" },
    { word: "apparent", partOfSpeech: "adjective", definition: "נראה לעין; לכאורה", example: "It became apparent quickly.", translation: "ניכר/לכאורה" },
    { word: "assume", partOfSpeech: "verb", definition: "להניח ללא ודאות", example: "I assumed you knew.", translation: "להניח" },
    { word: "attribute", partOfSpeech: "verb", definition: "לייחס למקור או לסיבה", example: "She attributes her success to luck.", translation: "לייחס" },
    { word: "bias", partOfSpeech: "noun", definition: "הטיה, נטייה לא הוגנת", example: "The report shows bias.", translation: "הטיה" },
    { word: "capacity", partOfSpeech: "noun", definition: "קיבולת או יכולת", example: "The hall has a large capacity.", translation: "קיבולת/יכולת" },
    { word: "commodity", partOfSpeech: "noun", definition: "מצרך או סחורה למסחר", example: "Oil is a valuable commodity.", translation: "מצרך/סחורה" },
    { word: "compatible", partOfSpeech: "adjective", definition: "תואם, מתאים יחד", example: "The app is compatible with my phone.", translation: "תואם" },
    { word: "confine", partOfSpeech: "verb", definition: "להגביל לתחום מסוים", example: "Keep the dog confined to the yard.", translation: "להגביל/לתחום" },
    { word: "consent", partOfSpeech: "noun", definition: "הסכמה רשמית", example: "We need your consent.", translation: "הסכמה" },
    { word: "considerable", partOfSpeech: "adjective", definition: "ניכר, גדול למדי", example: "A considerable amount of time.", translation: "ניכר" },
    { word: "consistent", partOfSpeech: "adjective", definition: "עקבי, אחיד לאורך זמן", example: "Be consistent in your effort.", translation: "עקבי" },
    { word: "contemporary", partOfSpeech: "adjective", definition: "בן זמננו, עכשווי", example: "Contemporary art.", translation: "בן זמננו/עכשווי" },
    { word: "controversial", partOfSpeech: "adjective", definition: "שנוי במחלוקת", example: "A controversial decision.", translation: "שנוי במחלוקת" },
    { word: "convey", partOfSpeech: "verb", definition: "להעביר מסר או רעיון", example: "Words can't convey my thanks.", translation: "להעביר/לבטא" },
    { word: "criteria", partOfSpeech: "noun", definition: "אמות מידה לשיפוט", example: "What are the criteria?", translation: "קריטריונים/אמות מידה" },
    { word: "deduce", partOfSpeech: "verb", definition: "להסיק מתוך עובדות", example: "We can deduce the cause.", translation: "להסיק" },
    { word: "diminish", partOfSpeech: "verb", definition: "להפחית או להתמעט", example: "Interest diminished over time.", translation: "להתמעט/להפחית" },
    { word: "exceed", partOfSpeech: "verb", definition: "לעבור את הגבול או הכמות", example: "Costs exceeded the budget.", translation: "לחרוג/לעבור" },
    { word: "facilitate", partOfSpeech: "verb", definition: "להקל ולסייע לתהליך", example: "Tools that facilitate learning.", translation: "להקל/לאפשר" },
    { word: "integrate", partOfSpeech: "verb", definition: "לשלב לכלל אחד", example: "Integrate the new staff.", translation: "לשלב/לשלוב" },
    { word: "transition", partOfSpeech: "noun", definition: "מעבר בין מצבים", example: "A smooth transition.", translation: "מעבר" },
  ],
  C1: [
    { word: "adamant", partOfSpeech: "adjective", definition: "נחרץ ועומד על דעתו", example: "She was adamant about leaving.", translation: "נחרץ/עיקש" },
    { word: "akin", partOfSpeech: "adjective", definition: "דומה ל-, קרוב במהותו", example: "It's akin to cheating.", translation: "דומה ל-" },
    { word: "ample", partOfSpeech: "adjective", definition: "רב ומספיק בשפע", example: "There is ample time.", translation: "רב/בשפע" },
    { word: "astute", partOfSpeech: "adjective", definition: "חריף ונבון בשיפוט", example: "An astute investor.", translation: "חריף/נבון" },
    { word: "benign", partOfSpeech: "adjective", definition: "שפיר; תמים ולא מזיק", example: "A benign tumour.", translation: "שפיר/תמים" },
    { word: "bleak", partOfSpeech: "adjective", definition: "קודר, חסר תקווה", example: "A bleak future.", translation: "קודר" },
    { word: "cohesive", partOfSpeech: "adjective", definition: "מלוכד, מחובר היטב", example: "A cohesive team.", translation: "מלוכד" },
    { word: "conspicuous", partOfSpeech: "adjective", definition: "בולט לעין, קל לזיהוי", example: "A conspicuous mistake.", translation: "בולט לעין" },
    { word: "contentious", partOfSpeech: "adjective", definition: "שנוי במחלוקת ומעורר ויכוח", example: "A contentious issue.", translation: "שנוי במחלוקת" },
    { word: "copious", partOfSpeech: "adjective", definition: "רב ושופע", example: "She took copious notes.", translation: "רב/שופע" },
    { word: "culminate", partOfSpeech: "verb", definition: "להגיע לשיא או לסיום", example: "It culminated in a festival.", translation: "להגיע לשיא" },
    { word: "curtail", partOfSpeech: "verb", definition: "לקצץ או לצמצם", example: "They curtailed spending.", translation: "לקצץ/לצמצם" },
    { word: "daunting", partOfSpeech: "adjective", definition: "מרתיע, מעורר חשש", example: "A daunting task.", translation: "מרתיע/מאיים" },
    { word: "deliberate", partOfSpeech: "adjective", definition: "מכוון, נעשה בכוונה", example: "A deliberate choice.", translation: "מכוון" },
    { word: "disparity", partOfSpeech: "noun", definition: "פער ואי-שוויון", example: "Income disparity.", translation: "פער/אי-שוויון" },
    { word: "elusive", partOfSpeech: "adjective", definition: "חמקמק, קשה לתפוס או להשיג", example: "An elusive goal.", translation: "חמקמק" },
    { word: "eminent", partOfSpeech: "adjective", definition: "נודע ודגול בתחומו", example: "An eminent scientist.", translation: "נודע/דגול" },
    { word: "exacerbate", partOfSpeech: "verb", definition: "להחמיר מצב רע", example: "Stress can exacerbate illness.", translation: "להחמיר" },
    { word: "imminent", partOfSpeech: "adjective", definition: "קרב ובא, עומד לקרות", example: "A storm is imminent.", translation: "קרב ובא" },
    { word: "intrinsic", partOfSpeech: "adjective", definition: "פנימי ומהותי לדבר עצמו", example: "Intrinsic value.", translation: "פנימי/מהותי" },
    { word: "lucid", partOfSpeech: "adjective", definition: "בהיר וברור להבנה", example: "A lucid explanation.", translation: "בהיר/צלול" },
    { word: "negligible", partOfSpeech: "adjective", definition: "זניח, קטן עד שאפשר להתעלם", example: "A negligible difference.", translation: "זניח" },
    { word: "ostensibly", partOfSpeech: "adverb", definition: "לכאורה, למראית עין", example: "He left, ostensibly to rest.", translation: "לכאורה" },
    { word: "pragmatic", partOfSpeech: "adjective", definition: "מעשי, מכוון תוצאות", example: "A pragmatic approach.", translation: "פרגמטי/מעשי" },
  ],
  C2: [
    { word: "aplomb", partOfSpeech: "noun", definition: "קור רוח וביטחון עצמי", example: "She handled it with aplomb.", translation: "קור רוח/ביטחון" },
    { word: "apocryphal", partOfSpeech: "adjective", definition: "בדוי, מסופק מבחינת אמיתותו", example: "An apocryphal story.", translation: "בדוי/מפוקפק" },
    { word: "arcane", partOfSpeech: "adjective", definition: "נסתר ומובן למעטים", example: "Arcane rules.", translation: "נסתר/חתום" },
    { word: "bellicose", partOfSpeech: "adjective", definition: "תוקפני ולוחמני", example: "Bellicose rhetoric.", translation: "תוקפני/לוחמני" },
    { word: "bombastic", partOfSpeech: "adjective", definition: "מנופח ומליצי ללא תוכן", example: "A bombastic speech.", translation: "מנופח/מליצי" },
    { word: "churlish", partOfSpeech: "adjective", definition: "גס רוח וחסר נימוס", example: "It seemed churlish to refuse.", translation: "גס רוח" },
    { word: "contrite", partOfSpeech: "adjective", definition: "מתחרט ומלא חרטה", example: "A contrite apology.", translation: "מתחרט" },
    { word: "effrontery", partOfSpeech: "noun", definition: "חוצפה ועזות מצח", example: "He had the effrontery to lie.", translation: "חוצפה/עזות מצח" },
    { word: "fatuous", partOfSpeech: "adjective", definition: "טיפשי וחסר ערך", example: "A fatuous remark.", translation: "טיפשי/חלול" },
    { word: "insidious", partOfSpeech: "adjective", definition: "ערמומי ומזיק בהדרגה ובסתר", example: "An insidious disease.", translation: "ערמומי/מתגנב" },
    { word: "intractable", partOfSpeech: "adjective", definition: "בלתי-פתיר או עיקש מאוד", example: "An intractable problem.", translation: "בלתי-פתיר/סרבן" },
    { word: "mendacious", partOfSpeech: "adjective", definition: "כוזב, נוטה לשקר", example: "A mendacious witness.", translation: "כוזב/שקרן" },
    { word: "obdurate", partOfSpeech: "adjective", definition: "קשה עורף ובלתי-מתרכך", example: "An obdurate refusal.", translation: "קשה עורף" },
    { word: "nebulous", partOfSpeech: "adjective", definition: "מעורפל וחסר צורה ברורה", example: "A nebulous concept.", translation: "מעורפל" },
    { word: "opaque", partOfSpeech: "adjective", definition: "אטום; לא שקוף או לא ברור", example: "The wording is opaque.", translation: "אטום/סתום" },
    { word: "ostentatious", partOfSpeech: "adjective", definition: "ראוותני, נועד להרשים", example: "An ostentatious display of wealth.", translation: "ראוותני" },
    { word: "pervasive", partOfSpeech: "adjective", definition: "חודר ונפוץ בכל מקום", example: "A pervasive influence.", translation: "חודר/נפוץ" },
    { word: "placate", partOfSpeech: "verb", definition: "לפייס ולהרגיע כעס", example: "He tried to placate the crowd.", translation: "לפייס/להרגיע" },
    { word: "precarious", partOfSpeech: "adjective", definition: "רעוע, לא יציב ומסוכן", example: "A precarious position.", translation: "רעוע/מסוכן" },
    { word: "proclivity", partOfSpeech: "noun", definition: "נטייה טבעית למשהו", example: "A proclivity for risk.", translation: "נטייה" },
    { word: "quagmire", partOfSpeech: "noun", definition: "סבך, מצב קשה שקשה לצאת ממנו", example: "A legal quagmire.", translation: "סבך/ביצה" },
    { word: "parsimonious", partOfSpeech: "adjective", definition: "קמצן וחסכן עד קמצנות", example: "Parsimonious with praise.", translation: "קמצן" },
    { word: "iniquity", partOfSpeech: "noun", definition: "עוול ורשע מוסרי", example: "The iniquity of slavery.", translation: "עוול/רשע" },
    { word: "lugubrious", partOfSpeech: "adjective", definition: "נוגה וקודר עד הגזמה", example: "A lugubrious expression.", translation: "נוגה/קודר" },
  ],
};
