// Round 8 of additional CEFR vocabulary — broadens every level, weighted toward
// B2/C1/C2 (which previously had the fewest distinct words, so days recycled
// sooner). Merged into WORD_BANKS by the generator, which validates that no
// word repeats within a level.

export const MORE_WORDS8 = {
  A1: [
    { word: "yellow", partOfSpeech: "adjective", definition: "צבע הלימון והשמש", example: "A yellow flower.", translation: "צהוב" },
    { word: "brown", partOfSpeech: "adjective", definition: "צבע האדמה והשוקולד", example: "Brown shoes.", translation: "חום" },
    { word: "pink", partOfSpeech: "adjective", definition: "צבע ורוד בהיר", example: "A pink dress.", translation: "ורוד" },
    { word: "purple", partOfSpeech: "adjective", definition: "צבע סגול", example: "Purple grapes.", translation: "סגול" },
    { word: "gray", partOfSpeech: "adjective", definition: "צבע בין שחור ללבן", example: "A gray cat.", translation: "אפור" },
    { word: "orange", partOfSpeech: "noun", definition: "פרי הדר כתום", example: "I eat an orange.", translation: "תפוז" },
    { word: "sheep", partOfSpeech: "noun", definition: "חיה שנותנת צמר", example: "White sheep.", translation: "כבשה" },
    { word: "pig", partOfSpeech: "noun", definition: "חיית משק ורודה", example: "A fat pig.", translation: "חזיר" },
    { word: "mouse", partOfSpeech: "noun", definition: "מכרסם קטן", example: "A small mouse.", translation: "עכבר" },
    { word: "elephant", partOfSpeech: "noun", definition: "חיה גדולה מאוד עם חדק", example: "The elephant is huge.", translation: "פיל" },
    { word: "tiger", partOfSpeech: "noun", definition: "חיית טרף מפוספסת", example: "The tiger runs fast.", translation: "נמר" },
    { word: "snake", partOfSpeech: "noun", definition: "זוחל ארוך ללא רגליים", example: "A green snake.", translation: "נחש" },
    { word: "frog", partOfSpeech: "noun", definition: "חיה קטנה שקופצת", example: "A frog jumps.", translation: "צפרדע" },
    { word: "bee", partOfSpeech: "noun", definition: "חרק שמייצר דבש", example: "A busy bee.", translation: "דבורה" },
    { word: "tooth", partOfSpeech: "noun", definition: "אחת מהשיניים בפה", example: "Brush every tooth.", translation: "שן" },
    { word: "lip", partOfSpeech: "noun", definition: "השפה סביב הפה", example: "A red lip.", translation: "שפה" },
    { word: "shoulder", partOfSpeech: "noun", definition: "החלק בין הצוואר ליד", example: "My shoulder hurts.", translation: "כתף" },
    { word: "lamp", partOfSpeech: "noun", definition: "מכשיר תאורה", example: "Turn on the lamp.", translation: "מנורה" },
    { word: "desk", partOfSpeech: "noun", definition: "שולחן כתיבה", example: "Books on the desk.", translation: "שולחן כתיבה" },
    { word: "sofa", partOfSpeech: "noun", definition: "ספה לישיבה", example: "Sit on the sofa.", translation: "ספה" },
    { word: "fridge", partOfSpeech: "noun", definition: "מקרר לשמירת מזון קר", example: "Milk is in the fridge.", translation: "מקרר" },
    { word: "knife", partOfSpeech: "noun", definition: "כלי חד לחיתוך", example: "Cut with a knife.", translation: "סכין" },
    { word: "sweater", partOfSpeech: "noun", definition: "בגד חם לגוף העליון", example: "A warm sweater.", translation: "סוודר" },
    { word: "belt", partOfSpeech: "noun", definition: "רצועה למותניים", example: "A leather belt.", translation: "חגורה" },
    { word: "shorts", partOfSpeech: "noun", definition: "מכנסיים קצרים", example: "Wear shorts in summer.", translation: "מכנסיים קצרים" },
    { word: "hour", partOfSpeech: "noun", definition: "יחידת זמן של 60 דקות", example: "In one hour.", translation: "שעה" },
    { word: "month", partOfSpeech: "noun", definition: "אחד מ-12 חלקי השנה", example: "Next month.", translation: "חודש" },
    { word: "evening", partOfSpeech: "noun", definition: "החלק של היום לפני הלילה", example: "Good evening.", translation: "ערב" },
    { word: "afternoon", partOfSpeech: "noun", definition: "החלק של היום אחרי הצהריים", example: "See you this afternoon.", translation: "אחר הצהריים" },
    { word: "run", partOfSpeech: "verb", definition: "לנוע מהר על הרגליים", example: "I run every day.", translation: "לרוץ" },
    { word: "sleep", partOfSpeech: "verb", definition: "לנוח בעיניים עצומות בלילה", example: "I sleep eight hours.", translation: "לישון" },
    { word: "play", partOfSpeech: "verb", definition: "לשחק או לנגן", example: "The kids play outside.", translation: "לשחק/לנגן" },
    { word: "buy", partOfSpeech: "verb", definition: "לקנות תמורת כסף", example: "I buy bread.", translation: "לקנות" },
    { word: "come", partOfSpeech: "verb", definition: "להגיע למקום", example: "Come here.", translation: "לבוא" },
    { word: "give", partOfSpeech: "verb", definition: "למסור משהו למישהו", example: "Give me the book.", translation: "לתת" },
    { word: "take", partOfSpeech: "verb", definition: "לקחת משהו", example: "Take an apple.", translation: "לקחת" },
    { word: "make", partOfSpeech: "verb", definition: "להכין או ליצור", example: "Make a cake.", translation: "לעשות/להכין" },
    { word: "put", partOfSpeech: "verb", definition: "להניח במקום", example: "Put it on the table.", translation: "לשים" },
    { word: "find", partOfSpeech: "verb", definition: "למצוא משהו", example: "I can't find my keys.", translation: "למצוא" },
    { word: "call", partOfSpeech: "verb", definition: "להתקשר או לקרוא בשם", example: "Call me tonight.", translation: "להתקשר/לקרוא" },
  ],
  A2: [
    { word: "ceiling", partOfSpeech: "noun", definition: "החלק העליון של החדר", example: "A light on the ceiling.", translation: "תקרה" },
    { word: "basement", partOfSpeech: "noun", definition: "קומה מתחת לקרקע", example: "The gym is in the basement.", translation: "מרתף" },
    { word: "balcony", partOfSpeech: "noun", definition: "מרפסת פתוחה", example: "Coffee on the balcony.", translation: "מרפסת" },
    { word: "furniture", partOfSpeech: "noun", definition: "רהיטים בבית", example: "New furniture.", translation: "רהיטים" },
    { word: "neighbourhood", partOfSpeech: "noun", definition: "אזור מגורים", example: "A quiet neighbourhood.", translation: "שכונה" },
    { word: "traffic", partOfSpeech: "noun", definition: "תנועת כלי רכב בכביש", example: "Heavy traffic today.", translation: "תנועה/פקק" },
    { word: "schedule", partOfSpeech: "noun", definition: "לוח זמנים", example: "A busy schedule.", translation: "לוח זמנים" },
    { word: "appointment", partOfSpeech: "noun", definition: "פגישה קבועה מראש", example: "A doctor's appointment.", translation: "תור/פגישה" },
    { word: "reservation", partOfSpeech: "noun", definition: "שמירת מקום מראש", example: "A table reservation.", translation: "הזמנת מקום" },
    { word: "receipt", partOfSpeech: "noun", definition: "אישור תשלום בכתב", example: "Keep the receipt.", translation: "קבלה" },
    { word: "discount", partOfSpeech: "noun", definition: "הפחתה במחיר", example: "A 20% discount.", translation: "הנחה" },
    { word: "refund", partOfSpeech: "noun", definition: "החזר של כסף ששולם", example: "I got a refund.", translation: "החזר כספי" },
    { word: "luggage", partOfSpeech: "noun", definition: "מזוודות וחפצים לנסיעה", example: "Heavy luggage.", translation: "כבודה/מטען" },
    { word: "souvenir", partOfSpeech: "noun", definition: "מזכרת מטיול", example: "A souvenir from Rome.", translation: "מזכרת" },
    { word: "fever", partOfSpeech: "noun", definition: "חום גבוה בגוף (מחלה)", example: "She has a fever.", translation: "חום (מחלה)" },
    { word: "headache", partOfSpeech: "noun", definition: "כאב בראש", example: "I have a headache.", translation: "כאב ראש" },
    { word: "medicine", partOfSpeech: "noun", definition: "תרופה", example: "Take your medicine.", translation: "תרופה" },
    { word: "bandage", partOfSpeech: "noun", definition: "תחבושת לפצע", example: "Put a bandage on it.", translation: "תחבושת" },
    { word: "comfortable", partOfSpeech: "adjective", definition: "נעים ונוח", example: "A comfortable chair.", translation: "נוח" },
    { word: "uncomfortable", partOfSpeech: "adjective", definition: "לא נוח", example: "An uncomfortable seat.", translation: "לא נוח" },
    { word: "crowded", partOfSpeech: "adjective", definition: "מלא באנשים", example: "A crowded bus.", translation: "צפוף" },
    { word: "delicious", partOfSpeech: "adjective", definition: "טעים מאוד", example: "A delicious meal.", translation: "טעים" },
    { word: "disgusting", partOfSpeech: "adjective", definition: "מגעיל ודוחה", example: "A disgusting smell.", translation: "מגעיל" },
    { word: "spicy", partOfSpeech: "adjective", definition: "חריף בטעם", example: "Spicy food.", translation: "חריף" },
    { word: "salty", partOfSpeech: "adjective", definition: "מלוח", example: "The soup is salty.", translation: "מלוח" },
    { word: "sour", partOfSpeech: "adjective", definition: "חמוץ בטעם", example: "A sour lemon.", translation: "חמוץ" },
    { word: "sweet", partOfSpeech: "adjective", definition: "מתוק בטעם", example: "Sweet cake.", translation: "מתוק" },
    { word: "fair", partOfSpeech: "adjective", definition: "הוגן וצודק", example: "A fair price.", translation: "הוגן" },
    { word: "unfair", partOfSpeech: "adjective", definition: "לא הוגן", example: "An unfair rule.", translation: "לא הוגן" },
    { word: "rent", partOfSpeech: "verb", definition: "לשכור תמורת תשלום", example: "Rent a car.", translation: "לשכור" },
    { word: "book", partOfSpeech: "verb", definition: "להזמין מקום מראש", example: "Book a hotel.", translation: "להזמין (מקום)" },
    { word: "reserve", partOfSpeech: "verb", definition: "לשמור מקום מראש", example: "Reserve a table.", translation: "להזמין מראש" },
    { word: "unpack", partOfSpeech: "verb", definition: "לפרוק מזוודה או ארגז", example: "Unpack your bag.", translation: "לפרוק (מזוודה)" },
    { word: "fry", partOfSpeech: "verb", definition: "לטגן בשמן", example: "Fry the eggs.", translation: "לטגן" },
    { word: "roast", partOfSpeech: "verb", definition: "לצלות בתנור", example: "Roast the chicken.", translation: "לצלות" },
    { word: "whisper", partOfSpeech: "verb", definition: "לדבר בקול נמוך מאוד", example: "She whispered a secret.", translation: "ללחוש" },
    { word: "record", partOfSpeech: "verb", definition: "להקליט קול או וידאו", example: "Record the show.", translation: "להקליט" },
    { word: "download", partOfSpeech: "verb", definition: "להוריד קובץ מהאינטרנט", example: "Download the app.", translation: "להוריד (קובץ)" },
    { word: "upload", partOfSpeech: "verb", definition: "להעלות קובץ לרשת", example: "Upload the photo.", translation: "להעלות (קובץ)" },
    { word: "charge", partOfSpeech: "verb", definition: "לטעון סוללה או לגבות תשלום", example: "Charge your phone.", translation: "לטעון/לחייב" },
  ],
  B1: [
    { word: "disadvantage", partOfSpeech: "noun", definition: "חיסרון", example: "The main disadvantage is the cost.", translation: "חיסרון" },
    { word: "apology", partOfSpeech: "noun", definition: "התנצלות", example: "He owes me an apology.", translation: "התנצלות" },
    { word: "argument", partOfSpeech: "noun", definition: "ויכוח או טיעון", example: "A strong argument.", translation: "ויכוח/טיעון" },
    { word: "arrangement", partOfSpeech: "noun", definition: "סידור או הסדר", example: "Travel arrangements.", translation: "סידור/הסדר" },
    { word: "assistance", partOfSpeech: "noun", definition: "עזרה", example: "I need your assistance.", translation: "סיוע" },
    { word: "atmosphere", partOfSpeech: "noun", definition: "אווירה", example: "A friendly atmosphere.", translation: "אווירה" },
    { word: "audience", partOfSpeech: "noun", definition: "קהל", example: "A large audience.", translation: "קהל" },
    { word: "authority", partOfSpeech: "noun", definition: "סמכות או רשות", example: "The local authority.", translation: "סמכות/רשות" },
    { word: "background", partOfSpeech: "noun", definition: "רקע", example: "Her academic background.", translation: "רקע" },
    { word: "barrier", partOfSpeech: "noun", definition: "מחסום", example: "A language barrier.", translation: "מחסום" },
    { word: "boundary", partOfSpeech: "noun", definition: "גבול", example: "Set clear boundaries.", translation: "גבול" },
    { word: "ceremony", partOfSpeech: "noun", definition: "טקס", example: "A wedding ceremony.", translation: "טקס" },
    { word: "circumstance", partOfSpeech: "noun", definition: "נסיבה", example: "Under these circumstances.", translation: "נסיבה" },
    { word: "committee", partOfSpeech: "noun", definition: "ועדה", example: "The planning committee.", translation: "ועדה" },
    { word: "competition", partOfSpeech: "noun", definition: "תחרות", example: "A tough competition.", translation: "תחרות" },
    { word: "conflict", partOfSpeech: "noun", definition: "סכסוך", example: "A conflict of interests.", translation: "סכסוך" },
    { word: "contribution", partOfSpeech: "noun", definition: "תרומה", example: "A generous contribution.", translation: "תרומה" },
    { word: "criticism", partOfSpeech: "noun", definition: "ביקורת", example: "Constructive criticism.", translation: "ביקורת" },
    { word: "curiosity", partOfSpeech: "noun", definition: "סקרנות", example: "Out of curiosity.", translation: "סקרנות" },
    { word: "definition", partOfSpeech: "noun", definition: "הגדרה", example: "The dictionary definition.", translation: "הגדרה" },
    { word: "adjust", partOfSpeech: "verb", definition: "לכוונן או להתאים", example: "Adjust the volume.", translation: "לכוונן/להתאים" },
    { word: "overcome", partOfSpeech: "verb", definition: "להתגבר על", example: "Overcome your fears.", translation: "להתגבר על" },
    { word: "interrupt", partOfSpeech: "verb", definition: "להפריע או לקטוע", example: "Don't interrupt me.", translation: "להפריע/לקטוע" },
    { word: "react", partOfSpeech: "verb", definition: "להגיב", example: "How did she react?", translation: "להגיב" },
    { word: "reject", partOfSpeech: "verb", definition: "לדחות", example: "They rejected the offer.", translation: "לדחות" },
    { word: "remove", partOfSpeech: "verb", definition: "להסיר", example: "Remove your shoes.", translation: "להסיר" },
    { word: "rescue", partOfSpeech: "verb", definition: "להציל", example: "They rescued the dog.", translation: "להציל" },
    { word: "struggle", partOfSpeech: "verb", definition: "להיאבק", example: "He struggles with math.", translation: "להיאבק" },
    { word: "suffer", partOfSpeech: "verb", definition: "לסבול", example: "She suffers from allergies.", translation: "לסבול" },
    { word: "support", partOfSpeech: "verb", definition: "לתמוך", example: "I support your idea.", translation: "לתמוך" },
    { word: "surround", partOfSpeech: "verb", definition: "להקיף", example: "Trees surround the house.", translation: "להקיף" },
    { word: "warn", partOfSpeech: "verb", definition: "להזהיר", example: "I warned you.", translation: "להזהיר" },
    { word: "wonder", partOfSpeech: "verb", definition: "לתהות", example: "I wonder why.", translation: "לתהות" },
    { word: "aggressive", partOfSpeech: "adjective", definition: "תוקפני", example: "Aggressive behaviour.", translation: "תוקפני" },
    { word: "ambitious", partOfSpeech: "adjective", definition: "שאפתן", example: "An ambitious plan.", translation: "שאפתן" },
    { word: "awful", partOfSpeech: "adjective", definition: "נורא", example: "An awful mistake.", translation: "נורא" },
    { word: "complicated", partOfSpeech: "adjective", definition: "מסובך", example: "A complicated problem.", translation: "מסובך" },
    { word: "desperate", partOfSpeech: "adjective", definition: "נואש", example: "A desperate situation.", translation: "נואש" },
    { word: "dramatic", partOfSpeech: "adjective", definition: "דרמטי", example: "A dramatic change.", translation: "דרמטי" },
    { word: "effective", partOfSpeech: "adjective", definition: "יעיל", example: "An effective method.", translation: "יעיל" },
    { word: "flexible", partOfSpeech: "adjective", definition: "גמיש", example: "Flexible hours.", translation: "גמיש" },
    { word: "frequent", partOfSpeech: "adjective", definition: "תכוף", example: "Frequent visits.", translation: "תכוף" },
    { word: "guilty", partOfSpeech: "adjective", definition: "אשם", example: "He felt guilty.", translation: "אשם" },
    { word: "impressive", partOfSpeech: "adjective", definition: "מרשים", example: "An impressive result.", translation: "מרשים" },
    { word: "independent", partOfSpeech: "adjective", definition: "עצמאי", example: "An independent country.", translation: "עצמאי" },
    { word: "massive", partOfSpeech: "adjective", definition: "עצום", example: "A massive building.", translation: "עצום" },
    { word: "mysterious", partOfSpeech: "adjective", definition: "מסתורי", example: "A mysterious sound.", translation: "מסתורי" },
    { word: "permanent", partOfSpeech: "adjective", definition: "קבוע", example: "A permanent job.", translation: "קבוע" },
    { word: "rapid", partOfSpeech: "adjective", definition: "מהיר", example: "Rapid growth.", translation: "מהיר" },
    { word: "reasonable", partOfSpeech: "adjective", definition: "סביר והגיוני", example: "A reasonable price.", translation: "סביר/הגיוני" },
    { word: "relevant", partOfSpeech: "adjective", definition: "רלוונטי, נוגע לעניין", example: "Relevant information.", translation: "רלוונטי" },
    { word: "reliable", partOfSpeech: "adjective", definition: "אמין", example: "A reliable car.", translation: "אמין" },
    { word: "sensitive", partOfSpeech: "adjective", definition: "רגיש", example: "A sensitive topic.", translation: "רגיש" },
    { word: "severe", partOfSpeech: "adjective", definition: "חמור", example: "A severe storm.", translation: "חמור" },
    { word: "typical", partOfSpeech: "adjective", definition: "טיפוסי", example: "A typical day.", translation: "טיפוסי" },
    { word: "urgent", partOfSpeech: "adjective", definition: "דחוף", example: "An urgent message.", translation: "דחוף" },
  ],
  B2: [
    { word: "undertake", partOfSpeech: "verb", definition: "לקחת על עצמו משימה", example: "They undertook the project.", translation: "לבצע/לקחת על עצמו" },
    { word: "oversee", partOfSpeech: "verb", definition: "לפקח על", example: "She oversees the team.", translation: "לפקח" },
    { word: "reinforce", partOfSpeech: "verb", definition: "לחזק או לתגבר", example: "Reinforce the message.", translation: "לחזק/לתגבר" },
    { word: "correspond", partOfSpeech: "verb", definition: "להתאים, או להתכתב", example: "The results correspond to the theory.", translation: "להתאים/להתכתב" },
    { word: "coincide", partOfSpeech: "verb", definition: "להתרחש בו-זמנית, לחפוף", example: "The dates coincide.", translation: "לחפוף/להתרחש יחד" },
    { word: "denote", partOfSpeech: "verb", definition: "לציין או לסמן משמעות", example: "Red denotes danger.", translation: "לציין/לסמן" },
    { word: "mediate", partOfSpeech: "verb", definition: "לתווך בין צדדים", example: "Mediate the dispute.", translation: "לתווך" },
    { word: "negate", partOfSpeech: "verb", definition: "לבטל או לשלול", example: "This negates the benefit.", translation: "לבטל/לשלול" },
    { word: "postulate", partOfSpeech: "verb", definition: "להניח הנחת יסוד", example: "He postulated a theory.", translation: "להניח (הנחת יסוד)" },
    { word: "refute", partOfSpeech: "verb", definition: "להפריך טענה", example: "Refute the claim.", translation: "להפריך" },
    { word: "stipulate", partOfSpeech: "verb", definition: "לקבוע במפורש בתנאי", example: "The contract stipulates a deadline.", translation: "לקבוע במפורש/להתנות" },
    { word: "supersede", partOfSpeech: "verb", definition: "להחליף ולדחוק מקום", example: "The new law supersedes the old one.", translation: "להחליף/לדחוק" },
    { word: "warrant", partOfSpeech: "verb", definition: "להצדיק, לחייב", example: "This warrants further study.", translation: "להצדיק" },
    { word: "underpin", partOfSpeech: "verb", definition: "לבסס, לתמוך ביסוד", example: "Data underpins the claim.", translation: "לבסס/לתמוך ביסוד" },
    { word: "substantiate", partOfSpeech: "verb", definition: "לבסס בראיות", example: "Substantiate your argument.", translation: "לבסס/להוכיח" },
    { word: "delegate", partOfSpeech: "verb", definition: "להאציל סמכות למישהו", example: "Delegate the task.", translation: "להאציל/לאצול" },
    { word: "optimize", partOfSpeech: "verb", definition: "לייעל למצב מיטבי", example: "Optimize performance.", translation: "לייעל/למטב" },
    { word: "streamline", partOfSpeech: "verb", definition: "לייעל ולפשט תהליך", example: "Streamline the process.", translation: "לייעל/לפשט" },
    { word: "pinpoint", partOfSpeech: "verb", definition: "לאתר במדויק", example: "Pinpoint the cause.", translation: "לאתר במדויק" },
    { word: "beneficial", partOfSpeech: "adjective", definition: "מועיל", example: "A beneficial change.", translation: "מועיל" },
    { word: "dominant", partOfSpeech: "adjective", definition: "שולט, דומיננטי", example: "The dominant species.", translation: "שולט/דומיננטי" },
    { word: "influential", partOfSpeech: "adjective", definition: "רב-השפעה", example: "An influential figure.", translation: "רב-השפעה" },
    { word: "innovative", partOfSpeech: "adjective", definition: "חדשני", example: "An innovative design.", translation: "חדשני" },
    { word: "optimal", partOfSpeech: "adjective", definition: "מיטבי, הטוב ביותר", example: "Optimal conditions.", translation: "מיטבי" },
    { word: "sophisticated", partOfSpeech: "adjective", definition: "מתוחכם ומורכב", example: "A sophisticated system.", translation: "מתוחכם" },
    { word: "vital", partOfSpeech: "adjective", definition: "חיוני", example: "A vital role.", translation: "חיוני" },
    { word: "rigorous", partOfSpeech: "adjective", definition: "קפדני ומחמיר", example: "A rigorous test.", translation: "קפדני/מחמיר" },
    { word: "rationale", partOfSpeech: "noun", definition: "נימוק, הצדקה הגיונית", example: "The rationale behind the decision.", translation: "נימוק/הצדקה" },
    { word: "premise", partOfSpeech: "noun", definition: "הנחת יסוד לטיעון", example: "A false premise.", translation: "הנחת יסוד" },
    { word: "correlation", partOfSpeech: "noun", definition: "מתאם בין שני דברים", example: "A strong correlation.", translation: "מתאם" },
    { word: "surplus", partOfSpeech: "noun", definition: "עודף מעבר לצורך", example: "A budget surplus.", translation: "עודף" },
    { word: "spectrum", partOfSpeech: "noun", definition: "קשת או טווח רחב", example: "A wide spectrum of views.", translation: "קשת/טווח" },
    { word: "hierarchy", partOfSpeech: "noun", definition: "היררכיה, סדר דרגות", example: "A corporate hierarchy.", translation: "היררכיה" },
    { word: "mechanism", partOfSpeech: "noun", definition: "מנגנון", example: "A defense mechanism.", translation: "מנגנון" },
    { word: "initiative", partOfSpeech: "noun", definition: "יוזמה", example: "Take the initiative.", translation: "יוזמה" },
    { word: "infrastructure", partOfSpeech: "noun", definition: "תשתית", example: "Digital infrastructure.", translation: "תשתית" },
    { word: "magnitude", partOfSpeech: "noun", definition: "עוצמה או סדר גודל", example: "The magnitude of the problem.", translation: "עוצמה/סדר גודל" },
    { word: "objective", partOfSpeech: "noun", definition: "מטרה או יעד", example: "Our main objective.", translation: "מטרה/יעד" },
    { word: "discourse", partOfSpeech: "noun", definition: "שיח או דיון", example: "Public discourse.", translation: "שיח/דיון" },
    { word: "criterion", partOfSpeech: "noun", definition: "אמת מידה יחידה", example: "The key criterion.", translation: "קריטריון/אמת מידה" },
  ],
  C1: [
    { word: "accentuate", partOfSpeech: "verb", definition: "להדגיש, להבליט", example: "The dress accentuates her figure.", translation: "להדגיש/להבליט" },
    { word: "admonish", partOfSpeech: "verb", definition: "לגעור, להזהיר בעדינות", example: "The teacher admonished them.", translation: "לגעור/להזהיר" },
    { word: "appraise", partOfSpeech: "verb", definition: "להעריך שווי או איכות", example: "Appraise the situation.", translation: "להעריך/לשום" },
    { word: "ascribe", partOfSpeech: "verb", definition: "לייחס למקור או לגורם", example: "Success is ascribed to hard work.", translation: "לייחס" },
    { word: "assimilate", partOfSpeech: "verb", definition: "להטמיע או להיטמע", example: "Assimilate new information.", translation: "להטמיע/להיטמע" },
    { word: "delineate", partOfSpeech: "verb", definition: "לתחום או לשרטט בבירור", example: "Delineate the boundaries.", translation: "לתחום/לשרטט בבירור" },
    { word: "disseminate", partOfSpeech: "verb", definition: "להפיץ מידע", example: "Disseminate the findings.", translation: "להפיץ (מידע)" },
    { word: "expedite", partOfSpeech: "verb", definition: "לזרז תהליך", example: "Expedite the delivery.", translation: "לזרז" },
    { word: "extrapolate", partOfSpeech: "verb", definition: "להסיק ולהשליך מנתונים קיימים", example: "Extrapolate from the data.", translation: "להסיק/להשליך מנתונים" },
    { word: "instigate", partOfSpeech: "verb", definition: "לחולל או להסית", example: "Instigate a reform.", translation: "לחולל/להסית" },
    { word: "necessitate", partOfSpeech: "verb", definition: "לחייב, להצריך", example: "This necessitates change.", translation: "לחייב/להצריך" },
    { word: "reconcile", partOfSpeech: "verb", definition: "ליישב מחלוקת, להשלים בין", example: "Reconcile the differences.", translation: "ליישב/להשלים בין" },
    { word: "relinquish", partOfSpeech: "verb", definition: "לוותר על, למסור", example: "Relinquish control.", translation: "לוותר על/למסור" },
    { word: "supplant", partOfSpeech: "verb", definition: "לתפוס את מקומו של", example: "Email supplanted letters.", translation: "לתפוס מקומו של" },
    { word: "vindicate", partOfSpeech: "verb", definition: "להצדיק, לנקות משם", example: "The results vindicated her.", translation: "להצדיק/לנקות משם" },
    { word: "convoluted", partOfSpeech: "adjective", definition: "מפותל ומסובך", example: "A convoluted plot.", translation: "מפותל/מסובך" },
    { word: "discernible", partOfSpeech: "adjective", definition: "ניתן להבחנה", example: "No discernible difference.", translation: "ניתן להבחנה" },
    { word: "innate", partOfSpeech: "adjective", definition: "מולד, טבעי", example: "An innate talent.", translation: "מולד/טבעי" },
    { word: "rudimentary", partOfSpeech: "adjective", definition: "בסיסי, ראשוני", example: "Rudimentary skills.", translation: "בסיסי/ראשוני" },
    { word: "staunch", partOfSpeech: "adjective", definition: "נחוש, נאמן ומושבע", example: "A staunch supporter.", translation: "נחוש/מושבע" },
    { word: "superfluous", partOfSpeech: "adjective", definition: "מיותר", example: "Superfluous details.", translation: "מיותר" },
    { word: "tenable", partOfSpeech: "adjective", definition: "בר-הגנה, הגיוני", example: "A tenable position.", translation: "בר-הגנה/הגיוני" },
    { word: "unequivocal", partOfSpeech: "adjective", definition: "חד-משמעי", example: "An unequivocal answer.", translation: "חד-משמעי" },
    { word: "unwarranted", partOfSpeech: "adjective", definition: "לא מוצדק", example: "Unwarranted criticism.", translation: "לא מוצדק" },
    { word: "verbose", partOfSpeech: "adjective", definition: "רב-מילים, מלל", example: "A verbose report.", translation: "רב-מילים/מלל" },
    { word: "adversity", partOfSpeech: "noun", definition: "מצוקה, פורענות", example: "Strength in adversity.", translation: "מצוקה/פורענות" },
    { word: "affront", partOfSpeech: "noun", definition: "עלבון גלוי", example: "An affront to his dignity.", translation: "עלבון" },
    { word: "aftermath", partOfSpeech: "noun", definition: "מה שבא אחרי אירוע קשה", example: "The aftermath of the storm.", translation: "תוצאה/מה שבא אחרי" },
    { word: "caveat", partOfSpeech: "noun", definition: "הסתייגות או אזהרה", example: "With one caveat.", translation: "הסתייגות/אזהרה" },
    { word: "connotation", partOfSpeech: "noun", definition: "משמעות נלווית של מילה", example: "A negative connotation.", translation: "קונוטציה/משמעות נלווית" },
    { word: "deterrent", partOfSpeech: "noun", definition: "גורם מרתיע", example: "A deterrent to crime.", translation: "גורם מרתיע" },
    { word: "dilemma", partOfSpeech: "noun", definition: "התלבטות בין שתי אפשרויות", example: "A moral dilemma.", translation: "דילמה/התלבטות" },
    { word: "paradox", partOfSpeech: "noun", definition: "פרדוקס, סתירה לכאורה", example: "An interesting paradox.", translation: "פרדוקס" },
    { word: "rapport", partOfSpeech: "noun", definition: "יחסי קרבה והבנה", example: "Build rapport with clients.", translation: "יחסי קרבה/כימיה" },
    { word: "misconception", partOfSpeech: "noun", definition: "תפיסה שגויה נפוצה", example: "A common misconception.", translation: "תפיסה שגויה" },
    { word: "hindsight", partOfSpeech: "noun", definition: "חוכמה שבדיעבד", example: "In hindsight, it was wrong.", translation: "חוכמה שבדיעבד" },
    { word: "leverage", partOfSpeech: "noun", definition: "מנוף או יתרון להשגת מטרה", example: "Financial leverage.", translation: "מנוף/יתרון" },
    { word: "proximity", partOfSpeech: "noun", definition: "קרבה במרחב", example: "In close proximity.", translation: "קרבה" },
    { word: "setback", partOfSpeech: "noun", definition: "נסיגה או מכשול זמני", example: "A temporary setback.", translation: "נסיגה/מכשול" },
    { word: "turmoil", partOfSpeech: "noun", definition: "מהומה, אי-שקט", example: "Political turmoil.", translation: "מהומה/אי-שקט" },
    { word: "vicinity", partOfSpeech: "noun", definition: "סביבה, קרבת מקום", example: "In the vicinity of the station.", translation: "סביבה/קרבת מקום" },
    { word: "influx", partOfSpeech: "noun", definition: "זרם או נהירה פנימה", example: "An influx of tourists.", translation: "זרם/נהירה" },
    { word: "shortfall", partOfSpeech: "noun", definition: "מחסור, גירעון ביחס לצורך", example: "A budget shortfall.", translation: "מחסור/גירעון" },
  ],
  C2: [
    { word: "abrogate", partOfSpeech: "verb", definition: "לבטל רשמית חוק או הסכם", example: "Abrogate the treaty.", translation: "לבטל (חוק/הסכם)" },
    { word: "adumbrate", partOfSpeech: "verb", definition: "לשרטט בקווים כלליים, לרמז מראש", example: "The report adumbrates a plan.", translation: "לשרטט בכלליות/לרמז" },
    { word: "arrogate", partOfSpeech: "verb", definition: "לנכס לעצמו שלא כדין", example: "He arrogated power to himself.", translation: "לנכס לעצמו שלא כדין" },
    { word: "castigate", partOfSpeech: "verb", definition: "לגנות בחריפות", example: "Critics castigated the film.", translation: "לגנות בחריפות" },
    { word: "coalesce", partOfSpeech: "verb", definition: "להתאחד ולהתמזג לכדי אחד", example: "The groups coalesced.", translation: "להתאחד/להתמזג" },
    { word: "excoriate", partOfSpeech: "verb", definition: "למתוח ביקורת קטלנית", example: "The press excoriated him.", translation: "למתוח ביקורת חריפה" },
    { word: "expiate", partOfSpeech: "verb", definition: "לכפר על חטא", example: "Expiate one's guilt.", translation: "לכפר" },
    { word: "foment", partOfSpeech: "verb", definition: "ללבות, להסית מהומה", example: "Foment unrest.", translation: "ללבות/להסית" },
    { word: "gainsay", partOfSpeech: "verb", definition: "להכחיש, לחלוק על", example: "No one can gainsay the facts.", translation: "להכחיש/לחלוק על" },
    { word: "inveigh", partOfSpeech: "verb", definition: "לצאת בחריפות מילולית נגד", example: "Inveigh against corruption.", translation: "לצאת בחריפות נגד" },
    { word: "obviate", partOfSpeech: "verb", definition: "לייתר, למנוע צורך מראש", example: "This obviates the need for a car.", translation: "לייתר/למנוע מראש" },
    { word: "promulgate", partOfSpeech: "verb", definition: "לפרסם ולהנהיג חוק או רעיון", example: "Promulgate a decree.", translation: "לפרסם/להנהיג (חוק)" },
    { word: "repudiate", partOfSpeech: "verb", definition: "להתכחש ולדחות מכל וכל", example: "Repudiate the accusation.", translation: "להתכחש/לדחות מכל וכל" },
    { word: "vacillate", partOfSpeech: "verb", definition: "להסס ולהתנדנד בין אפשרויות", example: "She vacillated for weeks.", translation: "להסס/להתנדנד" },
    { word: "venerate", partOfSpeech: "verb", definition: "להעריץ, לרחוש כבוד עמוק", example: "They venerate their elders.", translation: "להעריץ/לרחוש כבוד" },
    { word: "abstemious", partOfSpeech: "adjective", definition: "מתון, מסתפק במועט", example: "An abstemious lifestyle.", translation: "מתון/מסתפק במועט" },
    { word: "diaphanous", partOfSpeech: "adjective", definition: "שקוף ודק (בעיקר בד)", example: "A diaphanous veil.", translation: "שקוף/דק" },
    { word: "fractious", partOfSpeech: "adjective", definition: "רגזן, נוטה למריבות", example: "A fractious crowd.", translation: "רגזן/מתמרד" },
    { word: "grandiose", partOfSpeech: "adjective", definition: "מפואר עד רברבנות", example: "Grandiose plans.", translation: "מפואר/רברבני" },
    { word: "inimical", partOfSpeech: "adjective", definition: "עוין או מזיק", example: "Inimical to progress.", translation: "עוין/מזיק" },
    { word: "insipid", partOfSpeech: "adjective", definition: "תפל, חסר טעם או עניין", example: "An insipid speech.", translation: "תפל/חסר טעם" },
    { word: "mercurial", partOfSpeech: "adjective", definition: "הפכפך ותזזיתי", example: "A mercurial temperament.", translation: "הפכפך/תזזיתי" },
    { word: "munificent", partOfSpeech: "adjective", definition: "נדיב מאוד", example: "A munificent gift.", translation: "נדיב מאוד" },
    { word: "perspicacious", partOfSpeech: "adjective", definition: "חד-תפיסה ופיקח", example: "A perspicacious analyst.", translation: "חד-תפיסה/פיקח" },
    { word: "pusillanimous", partOfSpeech: "adjective", definition: "פחדן ומוג-לב", example: "A pusillanimous retreat.", translation: "פחדן/מוג-לב" },
    { word: "querulous", partOfSpeech: "adjective", definition: "מתלונן ורטנן", example: "A querulous tone.", translation: "מתלונן/רטנן" },
    { word: "sanctimonious", partOfSpeech: "adjective", definition: "צבוע ומתחסד מוסרית", example: "A sanctimonious lecture.", translation: "צבוע/מתחסד" },
    { word: "truculent", partOfSpeech: "adjective", definition: "תוקפני ולוחמני", example: "A truculent reply.", translation: "תוקפני/לוחמני" },
    { word: "turgid", partOfSpeech: "adjective", definition: "נפוח, מליצי ומסורבל", example: "Turgid prose.", translation: "נפוח/מליצי מדי" },
    { word: "vapid", partOfSpeech: "adjective", definition: "רדוד ותפל", example: "A vapid conversation.", translation: "רדוד/תפל" },
    { word: "approbation", partOfSpeech: "noun", definition: "הסכמה או אישור נלהב", example: "Public approbation.", translation: "הסכמה/אישור נלהב" },
    { word: "asperity", partOfSpeech: "noun", definition: "חריפות או גסות בדיבור", example: "He spoke with asperity.", translation: "חריפות/גסות" },
    { word: "calumny", partOfSpeech: "noun", definition: "השמצה, דיבה", example: "A victim of calumny.", translation: "השמצה/דיבה" },
    { word: "chicanery", partOfSpeech: "noun", definition: "תחבולנות ורמאות", example: "Political chicanery.", translation: "תחבולנות/רמאות" },
    { word: "obloquy", partOfSpeech: "noun", definition: "גינוי ציבורי, חרפה", example: "Subjected to obloquy.", translation: "גינוי/חרפה" },
    { word: "opprobrium", partOfSpeech: "noun", definition: "חרפה וגינוי ציבורי חריף", example: "Public opprobrium.", translation: "חרפה/גינוי ציבורי" },
    { word: "pariah", partOfSpeech: "noun", definition: "מנודה חברתי", example: "Treated as a pariah.", translation: "מנודה" },
    { word: "penchant", partOfSpeech: "noun", definition: "נטייה או חיבה חזקה", example: "A penchant for risk.", translation: "נטייה/חיבה" },
    { word: "perfidy", partOfSpeech: "noun", definition: "בגידה, מעילה באמון", example: "An act of perfidy.", translation: "בגידה/מעל" },
    { word: "platitude", partOfSpeech: "noun", definition: "קלישאה, אמירה נדושה", example: "Empty platitudes.", translation: "קלישאה" },
    { word: "rectitude", partOfSpeech: "noun", definition: "יושרה והגינות מוסרית", example: "Moral rectitude.", translation: "יושרה/הגינות" },
    { word: "sagacity", partOfSpeech: "noun", definition: "תבונה וחוכמת שיפוט", example: "Political sagacity.", translation: "תבונה/חוכמה" },
    { word: "veracity", partOfSpeech: "noun", definition: "אמינות, דבקות באמת", example: "Doubt the veracity of the report.", translation: "אמינות/דבקות באמת" },
    { word: "verisimilitude", partOfSpeech: "noun", definition: "מראית של אמת, אמינות סבירה", example: "The film has great verisimilitude.", translation: "מראית של אמת/אמינות" },
    { word: "zeal", partOfSpeech: "noun", definition: "התלהבות עזה, מסירות", example: "Reformist zeal.", translation: "התלהבות/קנאות" },
  ],
};
