// Round 7 of additional CEFR vocabulary — weighted to A1-B1. Merged into
// WORD_BANKS by the generator (validated for duplicates).

export const MORE_WORDS7 = {
  A1: [
    { word: "foot", partOfSpeech: "noun", definition: "החלק התחתון של הרגל", example: "My foot is cold.", translation: "כף רגל" },
    { word: "knee", partOfSpeech: "noun", definition: "המפרק באמצע הרגל", example: "He hurt his knee.", translation: "ברך" },
    { word: "back", partOfSpeech: "noun", definition: "החלק האחורי של הגוף", example: "My back hurts.", translation: "גב" },
    { word: "neck", partOfSpeech: "noun", definition: "החלק שמחבר ראש וגוף", example: "A long neck.", translation: "צוואר" },
    { word: "stomach", partOfSpeech: "noun", definition: "הבטן, איבר העיכול", example: "My stomach hurts.", translation: "בטן/קיבה" },
    { word: "lion", partOfSpeech: "noun", definition: "חיית טרף גדולה", example: "The lion is strong.", translation: "אריה" },
    { word: "monkey", partOfSpeech: "noun", definition: "חיה שמטפסת על עצים", example: "A funny monkey.", translation: "קוף" },
    { word: "bear", partOfSpeech: "noun", definition: "חיה גדולה ופרוותית", example: "A brown bear.", translation: "דוב" },
    { word: "rabbit", partOfSpeech: "noun", definition: "חיה קטנה עם אוזניים ארוכות", example: "A white rabbit.", translation: "ארנב" },
    { word: "duck", partOfSpeech: "noun", definition: "עוף מים", example: "A duck in the pond.", translation: "ברווז" },
    { word: "pizza", partOfSpeech: "noun", definition: "מאכל איטלקי עגול", example: "Let's order pizza.", translation: "פיצה" },
    { word: "sandwich", partOfSpeech: "noun", definition: "כריך", example: "A cheese sandwich.", translation: "כריך" },
    { word: "candy", partOfSpeech: "noun", definition: "ממתק", example: "The kids love candy.", translation: "ממתק" },
    { word: "honey", partOfSpeech: "noun", definition: "חומר מתוק מדבורים", example: "Tea with honey.", translation: "דבש" },
    { word: "lemon", partOfSpeech: "noun", definition: "פרי חמוץ צהוב", example: "A slice of lemon.", translation: "לימון" },
    { word: "grape", partOfSpeech: "noun", definition: "פרי קטן באשכול", example: "Sweet grapes.", translation: "ענב" },
    { word: "carrot", partOfSpeech: "noun", definition: "ירק כתום וארוך", example: "Rabbits eat carrots.", translation: "גזר" },
    { word: "onion", partOfSpeech: "noun", definition: "ירק חריף שמבכה", example: "Cut the onion.", translation: "בצל" },
    { word: "roof", partOfSpeech: "noun", definition: "החלק העליון של הבית", example: "A red roof.", translation: "גג" },
    { word: "yard", partOfSpeech: "noun", definition: "חצר ליד הבית", example: "Play in the yard.", translation: "חצר" },
    { word: "stairs", partOfSpeech: "noun", definition: "מדרגות", example: "Go up the stairs.", translation: "מדרגות" },
    { word: "towel", partOfSpeech: "noun", definition: "בד לייבוש", example: "A clean towel.", translation: "מגבת" },
    { word: "soap", partOfSpeech: "noun", definition: "חומר לרחצה", example: "Wash with soap.", translation: "סבון" },
    { word: "mirror", partOfSpeech: "noun", definition: "משטח שמשקף", example: "Look in the mirror.", translation: "מראה" },
    { word: "pillow", partOfSpeech: "noun", definition: "כרית לראש", example: "A soft pillow.", translation: "כרית" },
    { word: "blanket", partOfSpeech: "noun", definition: "שמיכה לחימום", example: "A warm blanket.", translation: "שמיכה" },
    { word: "basket", partOfSpeech: "noun", definition: "סל לנשיאה", example: "A basket of fruit.", translation: "סל" },
    { word: "bottle", partOfSpeech: "noun", definition: "מיכל לנוזלים", example: "A bottle of water.", translation: "בקבוק" },
    { word: "glass", partOfSpeech: "noun", definition: "כוס, או זכוכית", example: "A glass of milk.", translation: "כוס/זכוכית" },
    { word: "watch", partOfSpeech: "noun", definition: "שעון יד", example: "A new watch.", translation: "שעון יד" },
    { word: "camera", partOfSpeech: "noun", definition: "מכשיר לצילום", example: "Bring a camera.", translation: "מצלמה" },
    { word: "computer", partOfSpeech: "noun", definition: "מחשב", example: "Work on the computer.", translation: "מחשב" },
    { word: "television", partOfSpeech: "noun", definition: "טלוויזיה", example: "Watch television.", translation: "טלוויזיה" },
    { word: "map", partOfSpeech: "noun", definition: "מפה", example: "Look at the map.", translation: "מפה" },
    { word: "cousin", partOfSpeech: "noun", definition: "בן או בת של דוד/דודה", example: "My cousin visits us.", translation: "בן/בת דוד" },
    { word: "doll", partOfSpeech: "noun", definition: "בובה למשחק", example: "The girl's doll.", translation: "בובה" },
  ],
  A2: [
    { word: "add", partOfSpeech: "verb", definition: "להוסיף", example: "Add some salt.", translation: "להוסיף" },
    { word: "attack", partOfSpeech: "verb", definition: "לתקוף", example: "The dog attacked the gate.", translation: "לתקוף" },
    { word: "bake", partOfSpeech: "verb", definition: "לאפות", example: "Bake a cake.", translation: "לאפות" },
    { word: "bend", partOfSpeech: "verb", definition: "לכופף או להתכופף", example: "Bend your knees.", translation: "לכופף/להתכופף" },
    { word: "bite", partOfSpeech: "verb", definition: "לנשוך", example: "The dog might bite.", translation: "לנשוך" },
    { word: "blow", partOfSpeech: "verb", definition: "לנשוף או לנשב", example: "The wind blows.", translation: "לנשוף/לנשב" },
    { word: "boil", partOfSpeech: "verb", definition: "להרתיח", example: "Boil the water.", translation: "להרתיח/לרתוח" },
    { word: "burn", partOfSpeech: "verb", definition: "לשרוף או להישרף", example: "Don't burn the toast.", translation: "לשרוף/להישרף" },
    { word: "crash", partOfSpeech: "verb", definition: "להתרסק", example: "The car crashed.", translation: "להתרסק" },
    { word: "dig", partOfSpeech: "verb", definition: "לחפור", example: "Dig a hole.", translation: "לחפור" },
    { word: "dive", partOfSpeech: "verb", definition: "לצלול", example: "Dive into the pool.", translation: "לצלול" },
    { word: "fold", partOfSpeech: "verb", definition: "לקפל", example: "Fold the clothes.", translation: "לקפל" },
    { word: "hang", partOfSpeech: "verb", definition: "לתלות", example: "Hang the picture.", translation: "לתלות" },
    { word: "hide", partOfSpeech: "verb", definition: "להחביא או להתחבא", example: "Hide behind the tree.", translation: "להחביא/להתחבא" },
    { word: "hit", partOfSpeech: "verb", definition: "להכות, לפגוע", example: "The ball hit the window.", translation: "להכות/לפגוע" },
    { word: "hug", partOfSpeech: "verb", definition: "לחבק", example: "She hugged her friend.", translation: "לחבק" },
    { word: "kick", partOfSpeech: "verb", definition: "לבעוט", example: "Kick the ball.", translation: "לבעוט" },
    { word: "kiss", partOfSpeech: "verb", definition: "לנשק", example: "She kissed the baby.", translation: "לנשק" },
    { word: "melt", partOfSpeech: "verb", definition: "להמיס או להימס", example: "The ice melted.", translation: "להמיס/להימס" },
    { word: "nod", partOfSpeech: "verb", definition: "להנהן בראש", example: "He nodded in agreement.", translation: "להנהן" },
    { word: "press", partOfSpeech: "verb", definition: "ללחוץ", example: "Press the button.", translation: "ללחוץ" },
    { word: "print", partOfSpeech: "verb", definition: "להדפיס", example: "Print the document.", translation: "להדפיס" },
    { word: "repeat", partOfSpeech: "verb", definition: "לחזור על", example: "Please repeat that.", translation: "לחזור על" },
    { word: "ring", partOfSpeech: "verb", definition: "לצלצל", example: "The phone rang.", translation: "לצלצל" },
    { word: "rub", partOfSpeech: "verb", definition: "לשפשף", example: "Rub your hands.", translation: "לשפשף" },
    { word: "shake", partOfSpeech: "verb", definition: "לנער או לרעוד", example: "Shake the bottle.", translation: "לנער/לרעוד" },
    { word: "shine", partOfSpeech: "verb", definition: "לזרוח, לבהוק", example: "The sun shines.", translation: "לזרוח/לבהוק" },
    { word: "slip", partOfSpeech: "verb", definition: "להחליק", example: "I slipped on the ice.", translation: "להחליק" },
    { word: "spread", partOfSpeech: "verb", definition: "למרוח או להתפשט", example: "Spread the butter.", translation: "למרוח/להתפשט" },
    { word: "squeeze", partOfSpeech: "verb", definition: "לסחוט או ללחוץ", example: "Squeeze the lemon.", translation: "לסחוט/ללחוץ" },
    { word: "stick", partOfSpeech: "verb", definition: "להדביק או להיתקע", example: "Stick the stamp here.", translation: "להדביק/להיתקע" },
    { word: "tear", partOfSpeech: "verb", definition: "לקרוע", example: "Don't tear the page.", translation: "לקרוע" },
    { word: "tie", partOfSpeech: "verb", definition: "לקשור", example: "Tie your shoes.", translation: "לקשור" },
    { word: "touch", partOfSpeech: "verb", definition: "לגעת", example: "Don't touch it.", translation: "לגעת" },
    { word: "wrap", partOfSpeech: "verb", definition: "לעטוף", example: "Wrap the gift.", translation: "לעטוף" },
    { word: "lock", partOfSpeech: "verb", definition: "לנעול", example: "Lock the door.", translation: "לנעול" },
  ],
  B1: [
    { word: "absorb", partOfSpeech: "verb", definition: "לספוג", example: "The sponge absorbs water.", translation: "לספוג" },
    { word: "accuse", partOfSpeech: "verb", definition: "להאשים", example: "They accused him of lying.", translation: "להאשים" },
    { word: "amaze", partOfSpeech: "verb", definition: "להדהים", example: "The view amazed us.", translation: "להדהים" },
    { word: "arrest", partOfSpeech: "verb", definition: "לעצור (משטרה)", example: "Police arrested the thief.", translation: "לעצור/לאסור" },
    { word: "assemble", partOfSpeech: "verb", definition: "להרכיב, או להתאסף", example: "Assemble the furniture.", translation: "להרכיב/להתאסף" },
    { word: "assign", partOfSpeech: "verb", definition: "להקצות, לשבץ למשימה", example: "She assigned the tasks.", translation: "להקצות/לשבץ" },
    { word: "assure", partOfSpeech: "verb", definition: "להבטיח, להרגיע", example: "I assure you it's safe.", translation: "להבטיח/להרגיע" },
    { word: "boast", partOfSpeech: "verb", definition: "להתרברב", example: "He boasts about his car.", translation: "להתרברב" },
    { word: "broaden", partOfSpeech: "verb", definition: "להרחיב", example: "Travel broadens the mind.", translation: "להרחיב" },
    { word: "calculate", partOfSpeech: "verb", definition: "לחשב", example: "Calculate the total.", translation: "לחשב" },
    { word: "classify", partOfSpeech: "verb", definition: "לסווג", example: "Classify the books.", translation: "לסווג" },
    { word: "compose", partOfSpeech: "verb", definition: "לחבר, להלחין", example: "She composed a song.", translation: "לחבר/להלחין" },
    { word: "conclude", partOfSpeech: "verb", definition: "להסיק, לסכם", example: "We concluded the meeting.", translation: "להסיק/לסכם" },
    { word: "confess", partOfSpeech: "verb", definition: "להתוודות", example: "He confessed the truth.", translation: "להתוודות" },
    { word: "consult", partOfSpeech: "verb", definition: "להתייעץ", example: "Consult a doctor.", translation: "להתייעץ" },
    { word: "convert", partOfSpeech: "verb", definition: "להמיר, להפוך", example: "Convert dollars to euros.", translation: "להמיר" },
    { word: "declare", partOfSpeech: "verb", definition: "להכריז", example: "They declared independence.", translation: "להכריז" },
    { word: "define", partOfSpeech: "verb", definition: "להגדיר", example: "Define the word.", translation: "להגדיר" },
    { word: "ancient", partOfSpeech: "adjective", definition: "עתיק", example: "Ancient Rome.", translation: "עתיק" },
    { word: "annual", partOfSpeech: "adjective", definition: "שנתי", example: "An annual event.", translation: "שנתי" },
    { word: "anxious", partOfSpeech: "adjective", definition: "חרד, מודאג", example: "Anxious about the result.", translation: "חרד/מודאג" },
    { word: "artificial", partOfSpeech: "adjective", definition: "מלאכותי", example: "Artificial light.", translation: "מלאכותי" },
    { word: "authentic", partOfSpeech: "adjective", definition: "אותנטי, אמיתי", example: "Authentic food.", translation: "אותנטי/אמיתי" },
    { word: "bitter", partOfSpeech: "adjective", definition: "מר", example: "A bitter taste.", translation: "מר" },
    { word: "bold", partOfSpeech: "adjective", definition: "נועז", example: "A bold decision.", translation: "נועז" },
    { word: "brilliant", partOfSpeech: "adjective", definition: "מבריק, מצוין", example: "A brilliant idea.", translation: "מבריק/מצוין" },
    { word: "cautious", partOfSpeech: "adjective", definition: "זהיר", example: "A cautious driver.", translation: "זהיר" },
    { word: "conscious", partOfSpeech: "adjective", definition: "מודע, בהכרה", example: "Conscious of the danger.", translation: "מודע/בהכרה" },
    { word: "crisp", partOfSpeech: "adjective", definition: "פריך, או צונן ונעים", example: "Crisp toast.", translation: "פריך" },
    { word: "cruel", partOfSpeech: "adjective", definition: "אכזרי", example: "A cruel act.", translation: "אכזרי" },
    { word: "fluent", partOfSpeech: "adjective", definition: "שולט בשטף", example: "Fluent in English.", translation: "שולט בשטף/רהוט" },
    { word: "genuine", partOfSpeech: "adjective", definition: "אמיתי, כן", example: "Genuine leather.", translation: "אמיתי/כן" },
    { word: "gradual", partOfSpeech: "adjective", definition: "הדרגתי", example: "A gradual change.", translation: "הדרגתי" },
    { word: "humble", partOfSpeech: "adjective", definition: "צנוע", example: "A humble person.", translation: "צנוע" },
    { word: "intense", partOfSpeech: "adjective", definition: "עז, אינטנסיבי", example: "Intense heat.", translation: "עז/אינטנסיבי" },
    { word: "mature", partOfSpeech: "adjective", definition: "בוגר, בשל", example: "A mature attitude.", translation: "בוגר/בשל" },
  ],
  B2: [
    { word: "embody", partOfSpeech: "verb", definition: "לגלם, לבטא במוחשי", example: "She embodies kindness.", translation: "לגלם" },
    { word: "enforce", partOfSpeech: "verb", definition: "לאכוף", example: "Enforce the rules.", translation: "לאכוף" },
    { word: "entitle", partOfSpeech: "verb", definition: "לזכות, להקנות זכאות", example: "This ticket entitles you to entry.", translation: "לזכות/להעניק זכאות" },
    { word: "evoke", partOfSpeech: "verb", definition: "לעורר רגש או זיכרון", example: "The song evokes memories.", translation: "לעורר/להעלות בזיכרון" },
    { word: "exert", partOfSpeech: "verb", definition: "להפעיל מאמץ או כוח", example: "Exert influence.", translation: "להפעיל (מאמץ/כוח)" },
    { word: "exploit", partOfSpeech: "verb", definition: "לנצל (משאב או אדם)", example: "Exploit the opportunity.", translation: "לנצל" },
    { word: "fluctuate", partOfSpeech: "verb", definition: "להשתנות, לנוע מעלה ומטה", example: "Prices fluctuate daily.", translation: "להשתנות/לנוע" },
    { word: "impose", partOfSpeech: "verb", definition: "לכפות, להטיל", example: "Impose a tax.", translation: "לכפות/להטיל" },
    { word: "incorporate", partOfSpeech: "verb", definition: "לשלב, לכלול בתוך", example: "Incorporate feedback.", translation: "לשלב/לכלול" },
    { word: "induce", partOfSpeech: "verb", definition: "לגרום, לשדל", example: "Induce sleep.", translation: "לגרום/לשדל" },
    { word: "inhibit", partOfSpeech: "verb", definition: "לעכב, לרסן", example: "Fear inhibits action.", translation: "לעכב/לרסן" },
    { word: "yield", partOfSpeech: "verb", definition: "להניב, או להיכנע ולפנות מקום", example: "The land yields crops.", translation: "להניב/להיכנע" },
  ],
  C1: [
    { word: "diligent", partOfSpeech: "adjective", definition: "חרוץ ומתמיד", example: "A diligent student.", translation: "חרוץ/מתמיד" },
    { word: "dismay", partOfSpeech: "noun", definition: "מורת רוח מהולה בחרדה", example: "To my dismay.", translation: "מורת רוח/חרדה" },
    { word: "disposition", partOfSpeech: "noun", definition: "נטייה או מזג", example: "A cheerful disposition.", translation: "נטייה/מזג" },
    { word: "empirical", partOfSpeech: "adjective", definition: "אמפירי, מבוסס תצפית", example: "Empirical evidence.", translation: "אמפירי/ניסיוני" },
    { word: "erratic", partOfSpeech: "adjective", definition: "לא יציב, הפכפך", example: "Erratic behaviour.", translation: "לא יציב/הפכפך" },
    { word: "exemplary", partOfSpeech: "adjective", definition: "מופתי, ראוי לחיקוי", example: "Exemplary conduct.", translation: "מופתי/למופת" },
  ],
  C2: [
    { word: "epiphany", partOfSpeech: "noun", definition: "התגלות, רגע של הארה פתאומית", example: "She had an epiphany.", translation: "התגלות/הארה" },
    { word: "euphemism", partOfSpeech: "noun", definition: "לשון נקייה, ביטוי ממתן", example: "A euphemism for death.", translation: "לשון נקייה/המעטה" },
    { word: "exonerate", partOfSpeech: "verb", definition: "לזכות מאשמה", example: "The evidence exonerated him.", translation: "לזכות מאשמה" },
    { word: "expedient", partOfSpeech: "adjective", definition: "מועיל ותכליתי (לא בהכרח מוסרי)", example: "A politically expedient move.", translation: "מועיל/תכליתי" },
  ],
};
