// Round 3 of additional CEFR-leveled vocabulary, merged into WORD_BANKS by the
// generator. The generator validates the combined set for duplicates/missing
// fields. Rarest C1/C2 Hebrew translations are best-effort pending review.

export const MORE_WORDS3 = {
  A1: [
    { word: "leg", partOfSpeech: "noun", definition: "חלק הגוף שעליו עומדים", example: "My leg hurts.", translation: "רגל" },
    { word: "arm", partOfSpeech: "noun", definition: "חלק הגוף מהכתף ליד", example: "He broke his arm.", translation: "זרוע" },
    { word: "face", partOfSpeech: "noun", definition: "החלק הקדמי של הראש", example: "Wash your face.", translation: "פנים" },
    { word: "hair", partOfSpeech: "noun", definition: "מה שגדל על הראש", example: "She has long hair.", translation: "שיער" },
    { word: "mouth", partOfSpeech: "noun", definition: "החלק שבו אוכלים ומדברים", example: "Open your mouth.", translation: "פה" },
    { word: "nose", partOfSpeech: "noun", definition: "האיבר שבו מריחים", example: "A red nose.", translation: "אף" },
    { word: "ear", partOfSpeech: "noun", definition: "האיבר שבו שומעים", example: "I have an ear infection.", translation: "אוזן" },
    { word: "finger", partOfSpeech: "noun", definition: "אצבע של היד", example: "Point with your finger.", translation: "אצבע" },
    { word: "baby", partOfSpeech: "noun", definition: "תינוק קטן", example: "The baby is sleeping.", translation: "תינוק" },
    { word: "grandmother", partOfSpeech: "noun", definition: "אמא של אחד ההורים", example: "My grandmother bakes well.", translation: "סבתא" },
    { word: "grandfather", partOfSpeech: "noun", definition: "אבא של אחד ההורים", example: "My grandfather tells stories.", translation: "סבא" },
    { word: "key", partOfSpeech: "noun", definition: "מה שפותח מנעול", example: "I lost my key.", translation: "מפתח" },
    { word: "clock", partOfSpeech: "noun", definition: "מכשיר שמראה את השעה", example: "The clock is on the wall.", translation: "שעון (קיר)" },
    { word: "phone", partOfSpeech: "noun", definition: "מכשיר לדבר עם אנשים מרחוק", example: "Answer the phone.", translation: "טלפון" },
    { word: "floor", partOfSpeech: "noun", definition: "המשטח שעליו הולכים בבית", example: "The book is on the floor.", translation: "רצפה/קומה" },
    { word: "wall", partOfSpeech: "noun", definition: "הצד האנכי של חדר", example: "A picture on the wall.", translation: "קיר" },
    { word: "box", partOfSpeech: "noun", definition: "קופסה לאחסון", example: "A box of toys.", translation: "קופסה/ארגז" },
    { word: "letter", partOfSpeech: "noun", definition: "מכתב, או אות בכתב", example: "I wrote a letter.", translation: "מכתב/אות" },
    { word: "word", partOfSpeech: "noun", definition: "יחידה של שפה", example: "What does this word mean?", translation: "מילה" },
    { word: "number", partOfSpeech: "noun", definition: "סימן לכמות, כמו 5", example: "Pick a number.", translation: "מספר" },
    { word: "picture", partOfSpeech: "noun", definition: "תמונה או ציור", example: "A picture of the sea.", translation: "תמונה" },
    { word: "gift", partOfSpeech: "noun", definition: "מתנה שנותנים למישהו", example: "A birthday gift.", translation: "מתנה" },
    { word: "rice", partOfSpeech: "noun", definition: "מאכל בסיסי של גרגרים לבנים", example: "We ate rice and chicken.", translation: "אורז" },
    { word: "tea", partOfSpeech: "noun", definition: "משקה חם מעלים", example: "A cup of tea.", translation: "תה" },
  ],
  A2: [
    { word: "lucky", partOfSpeech: "adjective", definition: "בר מזל, שיש לו מזל טוב", example: "You're so lucky!", translation: "בר מזל" },
    { word: "angry", partOfSpeech: "adjective", definition: "כועס", example: "Don't be angry with me.", translation: "כועס" },
    { word: "bored", partOfSpeech: "adjective", definition: "משועמם, חסר עניין", example: "The kids are bored.", translation: "משועמם" },
    { word: "excited", partOfSpeech: "adjective", definition: "נרגש, מלא ציפייה", example: "I'm excited about the trip.", translation: "נרגש" },
    { word: "hungry", partOfSpeech: "adjective", definition: "רעב, רוצה לאכול", example: "I'm hungry.", translation: "רעב" },
    { word: "thirsty", partOfSpeech: "adjective", definition: "צמא, רוצה לשתות", example: "Are you thirsty?", translation: "צמא" },
    { word: "sick", partOfSpeech: "adjective", definition: "חולה, לא מרגיש טוב", example: "She is sick today.", translation: "חולה" },
    { word: "famous", partOfSpeech: "adjective", definition: "מפורסם, מוכר לרבים", example: "A famous singer.", translation: "מפורסם" },
    { word: "favourite", partOfSpeech: "adjective", definition: "האהוב ביותר", example: "My favourite book.", translation: "אהוב/מועדף" },
    { word: "enjoy", partOfSpeech: "verb", definition: "ליהנות ממשהו", example: "I enjoy swimming.", translation: "ליהנות" },
    { word: "hurry", partOfSpeech: "verb", definition: "למהר", example: "Hurry, we're late!", translation: "למהר" },
    { word: "worry", partOfSpeech: "verb", definition: "לדאוג, לחשוש", example: "Don't worry about it.", translation: "לדאוג" },
    { word: "finish", partOfSpeech: "verb", definition: "לסיים", example: "I finished my work.", translation: "לסיים" },
    { word: "forget", partOfSpeech: "verb", definition: "לשכוח", example: "Don't forget your keys.", translation: "לשכוח" },
    { word: "lose", partOfSpeech: "verb", definition: "לאבד או להפסיד", example: "Don't lose the ticket.", translation: "לאבד/להפסיד" },
    { word: "break", partOfSpeech: "verb", definition: "לשבור", example: "Be careful not to break it.", translation: "לשבור" },
    { word: "throw", partOfSpeech: "verb", definition: "לזרוק", example: "Throw the ball to me.", translation: "לזרוק" },
    { word: "catch", partOfSpeech: "verb", definition: "לתפוס", example: "Catch the ball!", translation: "לתפוס" },
    { word: "climb", partOfSpeech: "verb", definition: "לטפס", example: "We climbed the hill.", translation: "לטפס" },
    { word: "pull", partOfSpeech: "verb", definition: "למשוך אליך", example: "Pull the door.", translation: "למשוך" },
    { word: "push", partOfSpeech: "verb", definition: "לדחוף", example: "Push the button.", translation: "לדחוף" },
    { word: "carry", partOfSpeech: "verb", definition: "לשאת משהו", example: "Carry the bag for me.", translation: "לשאת" },
    { word: "drop", partOfSpeech: "verb", definition: "להפיל בטעות", example: "Don't drop the plate.", translation: "להפיל" },
    { word: "cut", partOfSpeech: "verb", definition: "לחתוך", example: "Cut the bread.", translation: "לחתוך" },
  ],
  B1: [
    { word: "discover", partOfSpeech: "verb", definition: "לגלות משהו חדש", example: "They discovered a cave.", translation: "לגלות" },
    { word: "explore", partOfSpeech: "verb", definition: "לחקור ולתור מקום או נושא", example: "Let's explore the old town.", translation: "לחקור/לתור" },
    { word: "express", partOfSpeech: "verb", definition: "לבטא רגש או רעיון", example: "Express your opinion.", translation: "לבטא" },
    { word: "focus", partOfSpeech: "verb", definition: "להתמקד, לרכז תשומת לב", example: "Focus on the task.", translation: "להתמקד" },
    { word: "gain", partOfSpeech: "verb", definition: "להרוויח או לצבור", example: "You gain experience over time.", translation: "להרוויח/לצבור" },
    { word: "handle", partOfSpeech: "verb", definition: "לטפל או להתמודד עם", example: "She handled the problem well.", translation: "לטפל ב-" },
    { word: "ignore", partOfSpeech: "verb", definition: "להתעלם בכוונה", example: "Don't ignore the warning.", translation: "להתעלם" },
    { word: "imagine", partOfSpeech: "verb", definition: "לדמיין במחשבה", example: "Imagine a quiet beach.", translation: "לדמיין" },
    { word: "include", partOfSpeech: "verb", definition: "לכלול בתוך מכלול", example: "The price includes breakfast.", translation: "לכלול" },
    { word: "influence", partOfSpeech: "verb", definition: "להשפיע על", example: "Friends influence our choices.", translation: "להשפיע/השפעה" },
    { word: "measure", partOfSpeech: "verb", definition: "למדוד גודל או כמות", example: "Measure the room.", translation: "למדוד" },
    { word: "mention", partOfSpeech: "verb", definition: "להזכיר בקצרה", example: "She mentioned your name.", translation: "להזכיר" },
    { word: "notice", partOfSpeech: "verb", definition: "להבחין במשהו", example: "I didn't notice the sign.", translation: "להבחין" },
    { word: "offer", partOfSpeech: "verb", definition: "להציע משהו", example: "They offered me tea.", translation: "להציע" },
    { word: "perform", partOfSpeech: "verb", definition: "לבצע, או להופיע", example: "The band performed live.", translation: "לבצע/להופיע" },
    { word: "protect", partOfSpeech: "verb", definition: "להגן מפני נזק", example: "Protect your skin from the sun.", translation: "להגן" },
    { word: "recognize", partOfSpeech: "verb", definition: "לזהות משהו מוכר", example: "I recognized her voice.", translation: "לזהות/להכיר" },
    { word: "reflect", partOfSpeech: "verb", definition: "לשקף, או להרהר", example: "The lake reflects the sky.", translation: "לשקף/להרהר" },
    { word: "refuse", partOfSpeech: "verb", definition: "לסרב", example: "He refused to help.", translation: "לסרב" },
    { word: "remain", partOfSpeech: "verb", definition: "להישאר", example: "Please remain seated.", translation: "להישאר" },
    { word: "replace", partOfSpeech: "verb", definition: "להחליף בדבר אחר", example: "Replace the batteries.", translation: "להחליף" },
    { word: "represent", partOfSpeech: "verb", definition: "לייצג מישהו או משהו", example: "She represents our team.", translation: "לייצג" },
    { word: "survive", partOfSpeech: "verb", definition: "לשרוד, להישאר בחיים", example: "Plants need water to survive.", translation: "לשרוד" },
    { word: "predict", partOfSpeech: "verb", definition: "לחזות מה יקרה בעתיד", example: "Experts predict rain tomorrow.", translation: "לחזות/לנבא" },
  ],
  B2: [
    { word: "restrict", partOfSpeech: "verb", definition: "להגביל, לצמצם", example: "The rule restricts access.", translation: "להגביל" },
    { word: "retain", partOfSpeech: "verb", definition: "לשמר, להחזיק", example: "Plants retain water.", translation: "לשמר/להחזיק" },
    { word: "reverse", partOfSpeech: "verb", definition: "להפוך כיוון או החלטה", example: "They reversed the decision.", translation: "להפוך/לבטל" },
    { word: "signify", partOfSpeech: "verb", definition: "לסמן, להורות על משמעות", example: "A red light signifies danger.", translation: "לסמן/להורות" },
    { word: "specify", partOfSpeech: "verb", definition: "לפרט במדויק", example: "Please specify the size.", translation: "לפרט/לציין" },
    { word: "stimulate", partOfSpeech: "verb", definition: "לעורר, לעודד פעילות", example: "Coffee stimulates the brain.", translation: "לעורר/לעודד" },
    { word: "sufficient", partOfSpeech: "adjective", definition: "מספיק, די הצורך", example: "We have sufficient funds.", translation: "מספיק" },
    { word: "supplement", partOfSpeech: "verb", definition: "להוסיף כדי להשלים", example: "He supplements his income.", translation: "להשלים/תוסף" },
    { word: "suspend", partOfSpeech: "verb", definition: "להשעות או להשהות", example: "The service was suspended.", translation: "להשעות/להשהות" },
    { word: "sustain", partOfSpeech: "verb", definition: "לקיים, לתמוך לאורך זמן", example: "Hard to sustain the pace.", translation: "לקיים/לתמוך" },
    { word: "terminate", partOfSpeech: "verb", definition: "לסיים או להפסיק", example: "They terminated the contract.", translation: "לסיים/להפסיק" },
    { word: "transmit", partOfSpeech: "verb", definition: "לשדר או להעביר", example: "The device transmits data.", translation: "לשדר/להעביר" },
    { word: "utilize", partOfSpeech: "verb", definition: "לעשות שימוש ב-", example: "Utilize all resources.", translation: "לנצל/להשתמש" },
    { word: "validate", partOfSpeech: "verb", definition: "לאמת או לתקף", example: "Validate the results.", translation: "לאמת/לתקף" },
    { word: "verify", partOfSpeech: "verb", definition: "לוודא נכונות", example: "Please verify your email.", translation: "לאמת/לוודא" },
    { word: "widespread", partOfSpeech: "adjective", definition: "נרחב, נפוץ באזור גדול", example: "Widespread support.", translation: "נרחב/נפוץ" },
    { word: "accordingly", partOfSpeech: "adverb", definition: "בהתאם לכך", example: "Plan accordingly.", translation: "בהתאם" },
    { word: "comprehend", partOfSpeech: "verb", definition: "להבין, לתפוס בשכל", example: "Hard to comprehend the scale.", translation: "להבין/לתפוס" },
    { word: "dynamic", partOfSpeech: "adjective", definition: "דינמי, מלא תנועה ושינוי", example: "A dynamic market.", translation: "דינמי" },
    { word: "external", partOfSpeech: "adjective", definition: "חיצוני", example: "An external hard drive.", translation: "חיצוני" },
    { word: "internal", partOfSpeech: "adjective", definition: "פנימי", example: "An internal report.", translation: "פנימי" },
    { word: "prior", partOfSpeech: "adjective", definition: "קודם, שקדם בזמן", example: "Prior experience required.", translation: "קודם" },
    { word: "ratio", partOfSpeech: "noun", definition: "יחס בין כמויות", example: "A ratio of two to one.", translation: "יחס" },
    { word: "theme", partOfSpeech: "noun", definition: "נושא או רעיון מרכזי", example: "The theme of the book.", translation: "נושא/מוטיב" },
  ],
  C1: [
    { word: "encompass", partOfSpeech: "verb", definition: "להקיף, לכלול בתוכו", example: "The course encompasses many topics.", translation: "להקיף/לכלול" },
    { word: "endorse", partOfSpeech: "verb", definition: "לתמוך בפומבי, לאשר", example: "The mayor endorsed the plan.", translation: "לאשר/לתמוך" },
    { word: "entail", partOfSpeech: "verb", definition: "לחייב, לגרור בעקבותיו", example: "The job entails travel.", translation: "לחייב/לגרור" },
    { word: "erode", partOfSpeech: "verb", definition: "לשחוק בהדרגה", example: "Trust can erode over time.", translation: "לשחוק" },
    { word: "formulate", partOfSpeech: "verb", definition: "לנסח באופן מסודר", example: "Formulate a strategy.", translation: "לנסח" },
    { word: "foster", partOfSpeech: "verb", definition: "לטפח, לעודד צמיחה", example: "Foster creativity.", translation: "לטפח" },
    { word: "gauge", partOfSpeech: "verb", definition: "להעריך או למדוד", example: "Hard to gauge his mood.", translation: "להעריך/למדוד" },
    { word: "hamper", partOfSpeech: "verb", definition: "לעכב ולהקשות", example: "Rain hampered the search.", translation: "לעכב/להכביד" },
    { word: "hinder", partOfSpeech: "verb", definition: "לעכב, להפריע להתקדמות", example: "Noise hinders concentration.", translation: "לעכב/להפריע" },
    { word: "implicit", partOfSpeech: "adjective", definition: "מרומז, לא נאמר במפורש", example: "An implicit agreement.", translation: "מרומז" },
    { word: "incremental", partOfSpeech: "adjective", definition: "הדרגתי, בצעדים קטנים", example: "Incremental progress.", translation: "הדרגתי" },
    { word: "irrespective", partOfSpeech: "adjective", definition: "ללא קשר ל-", example: "Open to all, irrespective of age.", translation: "ללא קשר ל-" },
    { word: "juncture", partOfSpeech: "noun", definition: "צומת, שלב מכריע", example: "At this juncture, we must decide.", translation: "צומת/שלב" },
    { word: "latent", partOfSpeech: "adjective", definition: "רדום, חבוי וטרם התגלה", example: "Latent talent.", translation: "רדום/חבוי" },
    { word: "manifest", partOfSpeech: "verb", definition: "לבטא או להתגלות בבירור", example: "Stress can manifest as pain.", translation: "להתבטא/לבוא לידי ביטוי" },
    { word: "offset", partOfSpeech: "verb", definition: "לקזז, לאזן השפעה", example: "Gains offset the losses.", translation: "לקזז/לאזן" },
    { word: "onset", partOfSpeech: "noun", definition: "תחילתו של דבר (לרוב שלילי)", example: "The onset of winter.", translation: "התחלה/פרוץ" },
    { word: "overt", partOfSpeech: "adjective", definition: "גלוי, בריש גלי", example: "Overt hostility.", translation: "גלוי" },
    { word: "poignant", partOfSpeech: "adjective", definition: "נוגע ללב, מעורר רגש", example: "A poignant memory.", translation: "נוגע ללב" },
    { word: "precede", partOfSpeech: "verb", definition: "לבוא לפני", example: "A storm preceded the calm.", translation: "לבוא לפני/לקדום" },
    { word: "preclude", partOfSpeech: "verb", definition: "למנוע מראש", example: "This doesn't preclude later changes.", translation: "למנוע מראש" },
    { word: "presume", partOfSpeech: "verb", definition: "להניח, לשער ללא ודאות מלאה", example: "I presume you agree.", translation: "להניח/לשער" },
    { word: "prospective", partOfSpeech: "adjective", definition: "עתידי, פוטנציאלי", example: "A prospective buyer.", translation: "עתידי/פוטנציאלי" },
    { word: "reciprocal", partOfSpeech: "adjective", definition: "הדדי, של נתינה וקבלה", example: "A reciprocal arrangement.", translation: "הדדי" },
  ],
  C2: [
    { word: "auspicious", partOfSpeech: "adjective", definition: "מבשר טובות, מעורר תקווה", example: "An auspicious start.", translation: "מבשר טובות" },
    { word: "banal", partOfSpeech: "adjective", definition: "בנאלי, נדוש וחסר מקוריות", example: "A banal observation.", translation: "בנאלי/נדוש" },
    { word: "callous", partOfSpeech: "adjective", definition: "אטום רגשית, חסר אכפתיות", example: "A callous remark.", translation: "אטום/חסר רגש" },
    { word: "candour", partOfSpeech: "noun", definition: "גילוי לב וכנות", example: "I admire her candour.", translation: "גילוי לב/כנות" },
    { word: "cursory", partOfSpeech: "adjective", definition: "שטחי וחפוז", example: "A cursory glance.", translation: "שטחי/חפוז" },
    { word: "dearth", partOfSpeech: "noun", definition: "מחסור, מיעוט", example: "A dearth of evidence.", translation: "מחסור/מיעוט" },
    { word: "debacle", partOfSpeech: "noun", definition: "מפלה, כישלון חרוץ ומביך", example: "The launch was a debacle.", translation: "מפלה/כישלון חרוץ" },
    { word: "decorum", partOfSpeech: "noun", definition: "נימוס והתנהגות הולמת", example: "Maintain decorum in court.", translation: "נימוס/הליכות" },
    { word: "deference", partOfSpeech: "noun", definition: "התחשבות וכבוד לסמכות", example: "Out of deference to elders.", translation: "התחשבות/כבוד" },
    { word: "diatribe", partOfSpeech: "noun", definition: "נאום נזעם ותקיף", example: "A diatribe against the press.", translation: "נאום נזעם" },
    { word: "disdain", partOfSpeech: "noun", definition: "בוז, יחס מזלזל", example: "She looked at him with disdain.", translation: "בוז/זלזול" },
    { word: "dogmatic", partOfSpeech: "adjective", definition: "דוגמטי, נוקשה בדעותיו", example: "A dogmatic attitude.", translation: "דוגמטי/נוקשה" },
    { word: "eclectic", partOfSpeech: "adjective", definition: "אקלקטי, מורכב ממקורות מגוונים", example: "An eclectic taste in music.", translation: "אקלקטי/מגוון" },
    { word: "elucidate", partOfSpeech: "verb", definition: "להבהיר, להסביר בבירור", example: "Let me elucidate the point.", translation: "להבהיר" },
    { word: "enmity", partOfSpeech: "noun", definition: "איבה, עוינות עמוקה", example: "Old enmity between them.", translation: "איבה/עוינות" },
    { word: "epitome", partOfSpeech: "noun", definition: "התגלמות, דוגמה מובהקת", example: "The epitome of elegance.", translation: "התגלמות/דוגמה מובהקת" },
    { word: "equanimity", partOfSpeech: "noun", definition: "שלוות נפש בעת קושי", example: "She faced it with equanimity.", translation: "שלוות נפש" },
    { word: "fervent", partOfSpeech: "adjective", definition: "נלהב ולוהט ברגשותיו", example: "A fervent supporter.", translation: "נלהב/לוהט" },
    { word: "furtive", partOfSpeech: "adjective", definition: "חשאי ומתגנב", example: "A furtive glance.", translation: "חשאי/מתגנב" },
    { word: "galvanize", partOfSpeech: "verb", definition: "להמריץ לפעולה נמרצת", example: "The speech galvanized the crowd.", translation: "להמריץ/לזרז" },
    { word: "hackneyed", partOfSpeech: "adjective", definition: "נדוש ושחוק מרוב שימוש", example: "A hackneyed phrase.", translation: "נדוש/שחוק" },
    { word: "idyllic", partOfSpeech: "adjective", definition: "אידילי, שלֵו ומושלם", example: "An idyllic village.", translation: "אידילי" },
    { word: "impeccable", partOfSpeech: "adjective", definition: "ללא רבב, מושלם", example: "Impeccable manners.", translation: "ללא רבב/מושלם" },
    { word: "cajole", partOfSpeech: "verb", definition: "לשדל בדברי חלקות", example: "He cajoled her into agreeing.", translation: "לשדל/לפתות בדברים" },
  ],
};
