// Round 6 of additional CEFR vocabulary — weighted to A1-B1 where real CEFR
// vocabulary is plentiful and Hebrew is reliable; only a few high-confidence
// C1/C2 words. Merged into WORD_BANKS by the generator (validated for dups).

export const MORE_WORDS6 = {
  A1: [
    { word: "trousers", partOfSpeech: "noun", definition: "בגד לרגליים", example: "He wore black trousers.", translation: "מכנסיים" },
    { word: "jacket", partOfSpeech: "noun", definition: "מעיל קצר", example: "Put on your jacket.", translation: "ז'קט/מעיל" },
    { word: "skirt", partOfSpeech: "noun", definition: "בגד לנשים מהמותניים ומטה", example: "A long skirt.", translation: "חצאית" },
    { word: "glove", partOfSpeech: "noun", definition: "כיסוי ליד", example: "Wear warm gloves.", translation: "כפפה" },
    { word: "scarf", partOfSpeech: "noun", definition: "בד לצוואר", example: "A red scarf.", translation: "צעיף" },
    { word: "boot", partOfSpeech: "noun", definition: "נעל גבוהה", example: "Winter boots.", translation: "מגף" },
    { word: "cheese", partOfSpeech: "noun", definition: "מאכל מחלב", example: "Bread and cheese.", translation: "גבינה" },
    { word: "butter", partOfSpeech: "noun", definition: "מאכל שומני מחלב", example: "Butter on toast.", translation: "חמאה" },
    { word: "soup", partOfSpeech: "noun", definition: "מאכל נוזלי חם", example: "Hot soup.", translation: "מרק" },
    { word: "cake", partOfSpeech: "noun", definition: "מאפה מתוק", example: "A birthday cake.", translation: "עוגה" },
    { word: "salad", partOfSpeech: "noun", definition: "מנה של ירקות", example: "A green salad.", translation: "סלט" },
    { word: "fruit", partOfSpeech: "noun", definition: "פרי, מזון מתוק מצמחים", example: "Eat more fruit.", translation: "פרי/פירות" },
    { word: "vegetable", partOfSpeech: "noun", definition: "ירק", example: "Fresh vegetables.", translation: "ירק" },
    { word: "chocolate", partOfSpeech: "noun", definition: "ממתק מקקאו", example: "Dark chocolate.", translation: "שוקולד" },
    { word: "radio", partOfSpeech: "noun", definition: "מכשיר לשמיעת תחנות", example: "Turn on the radio.", translation: "רדיו" },
    { word: "grass", partOfSpeech: "noun", definition: "הצמח הירוק על האדמה", example: "Sit on the grass.", translation: "דשא/עשב" },
    { word: "sea", partOfSpeech: "noun", definition: "גוף מים מלוחים גדול", example: "We swam in the sea.", translation: "ים" },
    { word: "fire", partOfSpeech: "noun", definition: "אש", example: "A warm fire.", translation: "אש" },
    { word: "ice", partOfSpeech: "noun", definition: "מים קפואים", example: "Ice in the drink.", translation: "קרח" },
    { word: "stone", partOfSpeech: "noun", definition: "אבן", example: "A small stone.", translation: "אבן" },
    { word: "uncle", partOfSpeech: "noun", definition: "אח של אחד ההורים", example: "My uncle is funny.", translation: "דוד" },
    { word: "aunt", partOfSpeech: "noun", definition: "אחות של אחד ההורים", example: "My aunt lives nearby.", translation: "דודה" },
    { word: "son", partOfSpeech: "noun", definition: "ילד ממין זכר במשפחה", example: "Their son is five.", translation: "בן" },
    { word: "daughter", partOfSpeech: "noun", definition: "ילדה ממין נקבה במשפחה", example: "Their daughter sings.", translation: "בת" },
    { word: "wife", partOfSpeech: "noun", definition: "בת הזוג הנשואה", example: "His wife is a doctor.", translation: "אישה/רעיה" },
    { word: "husband", partOfSpeech: "noun", definition: "בן הזוג הנשוי", example: "Her husband cooks.", translation: "בעל" },
    { word: "sit", partOfSpeech: "verb", definition: "לשבת", example: "Please sit down.", translation: "לשבת" },
    { word: "stand", partOfSpeech: "verb", definition: "לעמוד", example: "Stand up, please.", translation: "לעמוד" },
    { word: "sing", partOfSpeech: "verb", definition: "לשיר", example: "She sings well.", translation: "לשיר" },
    { word: "wash", partOfSpeech: "verb", definition: "לנקות במים", example: "Wash your hands.", translation: "לשטוף/לרחוץ" },
    { word: "smile", partOfSpeech: "verb", definition: "לחייך", example: "She smiled at me.", translation: "לחייך" },
    { word: "cry", partOfSpeech: "verb", definition: "לבכות", example: "The baby cried.", translation: "לבכות" },
    { word: "tall", partOfSpeech: "adjective", definition: "גבוה", example: "A tall man.", translation: "גבוה" },
    { word: "young", partOfSpeech: "adjective", definition: "צעיר", example: "A young child.", translation: "צעיר" },
    { word: "nice", partOfSpeech: "adjective", definition: "נחמד, נעים", example: "A nice day.", translation: "נחמד/נעים" },
    { word: "toy", partOfSpeech: "noun", definition: "צעצוע למשחק", example: "The child's toy.", translation: "צעצוע" },
  ],
  A2: [
    { word: "answer", partOfSpeech: "verb", definition: "לענות", example: "Answer the question.", translation: "לענות" },
    { word: "ask", partOfSpeech: "verb", definition: "לשאול, או לבקש", example: "Ask the teacher.", translation: "לשאול/לבקש" },
    { word: "count", partOfSpeech: "verb", definition: "לספור", example: "Count to ten.", translation: "לספור" },
    { word: "knock", partOfSpeech: "verb", definition: "לדפוק (בדלת)", example: "Knock before you enter.", translation: "לדפוק" },
    { word: "lift", partOfSpeech: "verb", definition: "להרים", example: "Lift the box carefully.", translation: "להרים" },
    { word: "mix", partOfSpeech: "verb", definition: "לערבב", example: "Mix the eggs and flour.", translation: "לערבב" },
    { word: "pack", partOfSpeech: "verb", definition: "לארוז", example: "Pack your bag.", translation: "לארוז" },
    { word: "paint", partOfSpeech: "verb", definition: "לצבוע, או לצייר", example: "We painted the wall.", translation: "לצבוע/לצייר" },
    { word: "plant", partOfSpeech: "verb", definition: "לשתול", example: "We planted a tree.", translation: "לשתול" },
    { word: "pour", partOfSpeech: "verb", definition: "למזוג נוזל", example: "Pour the water.", translation: "למזוג" },
    { word: "promise", partOfSpeech: "verb", definition: "להבטיח", example: "I promise to come.", translation: "להבטיח" },
    { word: "rest", partOfSpeech: "verb", definition: "לנוח", example: "You should rest.", translation: "לנוח" },
    { word: "share", partOfSpeech: "verb", definition: "לחלוק עם אחרים", example: "Share the cake.", translation: "לחלוק" },
    { word: "spell", partOfSpeech: "verb", definition: "לאיית", example: "How do you spell it?", translation: "לאיית" },
    { word: "taste", partOfSpeech: "verb", definition: "לטעום", example: "Taste the soup.", translation: "לטעום" },
    { word: "wake", partOfSpeech: "verb", definition: "להתעורר או להעיר", example: "Wake up early.", translation: "להתעורר/להעיר" },
    { word: "waste", partOfSpeech: "verb", definition: "לבזבז", example: "Don't waste water.", translation: "לבזבז" },
    { word: "wave", partOfSpeech: "verb", definition: "לנופף", example: "She waved goodbye.", translation: "לנופף" },
    { word: "accident", partOfSpeech: "noun", definition: "תאונה", example: "A car accident.", translation: "תאונה" },
    { word: "army", partOfSpeech: "noun", definition: "צבא", example: "He joined the army.", translation: "צבא" },
    { word: "art", partOfSpeech: "noun", definition: "אמנות", example: "Modern art.", translation: "אמנות" },
    { word: "bridge", partOfSpeech: "noun", definition: "גשר", example: "Cross the bridge.", translation: "גשר" },
    { word: "capital", partOfSpeech: "noun", definition: "עיר הבירה", example: "Rome is the capital of Italy.", translation: "בירה" },
    { word: "corner", partOfSpeech: "noun", definition: "פינה", example: "The shop on the corner.", translation: "פינה" },
    { word: "crowd", partOfSpeech: "noun", definition: "קהל, המון אנשים", example: "A large crowd.", translation: "קהל/המון" },
    { word: "desert", partOfSpeech: "noun", definition: "מדבר", example: "The Sahara desert.", translation: "מדבר" },
    { word: "difference", partOfSpeech: "noun", definition: "הבדל", example: "What's the difference?", translation: "הבדל" },
    { word: "distance", partOfSpeech: "noun", definition: "מרחק", example: "A short distance.", translation: "מרחק" },
    { word: "edge", partOfSpeech: "noun", definition: "קצה, שפה", example: "The edge of the table.", translation: "קצה/שפה" },
    { word: "enemy", partOfSpeech: "noun", definition: "אויב", example: "They were old enemies.", translation: "אויב" },
    { word: "entrance", partOfSpeech: "noun", definition: "כניסה", example: "The main entrance.", translation: "כניסה" },
    { word: "event", partOfSpeech: "noun", definition: "אירוע", example: "A sports event.", translation: "אירוע" },
    { word: "factory", partOfSpeech: "noun", definition: "מפעל", example: "A car factory.", translation: "מפעל" },
    { word: "gate", partOfSpeech: "noun", definition: "שער", example: "Open the gate.", translation: "שער" },
    { word: "cheerful", partOfSpeech: "adjective", definition: "עליז, שמח", example: "A cheerful smile.", translation: "עליז/שמח" },
    { word: "silent", partOfSpeech: "adjective", definition: "שקט, דומם", example: "The room was silent.", translation: "שקט/דומם" },
  ],
  B1: [
    { word: "behave", partOfSpeech: "verb", definition: "להתנהג", example: "The children behaved well.", translation: "להתנהג" },
    { word: "cancel", partOfSpeech: "verb", definition: "לבטל", example: "They cancelled the trip.", translation: "לבטל" },
    { word: "chase", partOfSpeech: "verb", definition: "לרדוף", example: "The dog chased the cat.", translation: "לרדוף" },
    { word: "cheer", partOfSpeech: "verb", definition: "להריע, לעודד", example: "The crowd cheered.", translation: "להריע/לעודד" },
    { word: "collect", partOfSpeech: "verb", definition: "לאסוף", example: "He collects stamps.", translation: "לאסוף" },
    { word: "cure", partOfSpeech: "verb", definition: "לרפא", example: "The medicine cured her.", translation: "לרפא" },
    { word: "decorate", partOfSpeech: "verb", definition: "לקשט", example: "Decorate the room.", translation: "לקשט" },
    { word: "defend", partOfSpeech: "verb", definition: "להגן", example: "Defend your goal.", translation: "להגן" },
    { word: "educate", partOfSpeech: "verb", definition: "לחנך, ללמד", example: "Schools educate children.", translation: "לחנך" },
    { word: "elect", partOfSpeech: "verb", definition: "לבחור בבחירות", example: "They elected a mayor.", translation: "לבחור (בבחירות)" },
    { word: "escape", partOfSpeech: "verb", definition: "להימלט", example: "The bird escaped.", translation: "להימלט" },
    { word: "exchange", partOfSpeech: "verb", definition: "להחליף", example: "Exchange money at the bank.", translation: "להחליף" },
    { word: "feed", partOfSpeech: "verb", definition: "להאכיל", example: "Feed the cat.", translation: "להאכיל" },
    { word: "float", partOfSpeech: "verb", definition: "לצוף", example: "Wood floats on water.", translation: "לצוף" },
    { word: "forgive", partOfSpeech: "verb", definition: "לסלוח", example: "Please forgive me.", translation: "לסלוח" },
    { word: "freeze", partOfSpeech: "verb", definition: "להקפיא, לקפוא", example: "Water freezes at zero.", translation: "להקפיא/לקפוא" },
    { word: "greet", partOfSpeech: "verb", definition: "לברך לשלום", example: "She greeted the guests.", translation: "לברך לשלום" },
    { word: "heal", partOfSpeech: "verb", definition: "לרפא, להירפא", example: "The wound healed.", translation: "לרפא/להירפא" },
    { word: "hire", partOfSpeech: "verb", definition: "לשכור עובד או ציוד", example: "They hired a guide.", translation: "לשכור" },
    { word: "impress", partOfSpeech: "verb", definition: "להרשים", example: "Her work impressed us.", translation: "להרשים" },
    { word: "average", partOfSpeech: "adjective", definition: "ממוצע", example: "An average score.", translation: "ממוצע" },
    { word: "brief", partOfSpeech: "adjective", definition: "קצר, תמציתי", example: "A brief meeting.", translation: "קצר/תמציתי" },
    { word: "capable", partOfSpeech: "adjective", definition: "מסוגל", example: "She is very capable.", translation: "מסוגל" },
    { word: "casual", partOfSpeech: "adjective", definition: "לא רשמי", example: "Casual clothes.", translation: "לא רשמי/יומיומי" },
    { word: "complex", partOfSpeech: "adjective", definition: "מורכב", example: "A complex problem.", translation: "מורכב" },
    { word: "constant", partOfSpeech: "adjective", definition: "קבוע, מתמיד", example: "Constant noise.", translation: "קבוע/מתמיד" },
    { word: "curious", partOfSpeech: "adjective", definition: "סקרן", example: "A curious child.", translation: "סקרן" },
    { word: "decent", partOfSpeech: "adjective", definition: "הגון, סביר", example: "A decent salary.", translation: "הגון/סביר" },
    { word: "delicate", partOfSpeech: "adjective", definition: "עדין, שביר", example: "A delicate flower.", translation: "עדין/שביר" },
    { word: "eager", partOfSpeech: "adjective", definition: "להוט, מלא חשק", example: "Eager to learn.", translation: "להוט" },
    { word: "efficient", partOfSpeech: "adjective", definition: "יעיל", example: "An efficient worker.", translation: "יעיל" },
    { word: "elegant", partOfSpeech: "adjective", definition: "אלגנטי, מעודן", example: "An elegant dress.", translation: "אלגנטי" },
    { word: "essential", partOfSpeech: "adjective", definition: "חיוני, הכרחי", example: "Water is essential.", translation: "חיוני/הכרחי" },
    { word: "generous", partOfSpeech: "adjective", definition: "נדיב", example: "A generous gift.", translation: "נדיב" },
    { word: "obvious", partOfSpeech: "adjective", definition: "ברור, מובן מאליו", example: "The answer is obvious.", translation: "ברור/מובן מאליו" },
    { word: "rare", partOfSpeech: "adjective", definition: "נדיר", example: "A rare bird.", translation: "נדיר" },
  ],
  B2: [
    { word: "accelerate", partOfSpeech: "verb", definition: "להאיץ", example: "The car accelerated.", translation: "להאיץ" },
    { word: "accomplish", partOfSpeech: "verb", definition: "להשיג, לבצע בהצלחה", example: "We accomplished the goal.", translation: "להשיג/לבצע" },
    { word: "accountable", partOfSpeech: "adjective", definition: "אחראי, בר-דיווח", example: "Leaders are accountable.", translation: "אחראי/בר-דיווח" },
    { word: "adhere", partOfSpeech: "verb", definition: "לדבוק, לציית לכללים", example: "Adhere to the rules.", translation: "לדבוק/לציית" },
    { word: "clarify", partOfSpeech: "verb", definition: "להבהיר", example: "Let me clarify.", translation: "להבהיר" },
    { word: "compensate", partOfSpeech: "verb", definition: "לפצות", example: "We'll compensate you for the delay.", translation: "לפצות" },
    { word: "comply", partOfSpeech: "verb", definition: "לציית, לעמוד בדרישה", example: "Comply with the law.", translation: "לציית" },
    { word: "conceive", partOfSpeech: "verb", definition: "להגות רעיון, לתפוס", example: "Hard to conceive of it.", translation: "להגות/לתפוס" },
    { word: "consequently", partOfSpeech: "adverb", definition: "כתוצאה מכך", example: "It rained; consequently, we stayed in.", translation: "כתוצאה מכך" },
    { word: "contradict", partOfSpeech: "verb", definition: "לסתור", example: "The two reports contradict.", translation: "לסתור" },
    { word: "designate", partOfSpeech: "verb", definition: "לייעד, למנות", example: "A designated driver.", translation: "לייעד/למנות" },
    { word: "detect", partOfSpeech: "verb", definition: "לזהות, לאתר", example: "Detect a problem early.", translation: "לזהות/לאתר" },
    { word: "deter", partOfSpeech: "verb", definition: "להרתיע", example: "High prices deter buyers.", translation: "להרתיע" },
    { word: "disclose", partOfSpeech: "verb", definition: "לחשוף מידע", example: "They disclosed the figures.", translation: "לחשוף" },
    { word: "dispose", partOfSpeech: "verb", definition: "להיפטר מ-, לסלק", example: "Dispose of the waste.", translation: "להיפטר מ-/לסלק" },
    { word: "distort", partOfSpeech: "verb", definition: "לעוות", example: "The media distorted the story.", translation: "לעוות" },
    { word: "diverge", partOfSpeech: "verb", definition: "להסתעף, להתפצל", example: "Our views diverge.", translation: "להסתעף/להתפצל" },
    { word: "compile", partOfSpeech: "verb", definition: "לאסוף ולערוך לכלל מסמך", example: "Compile a report.", translation: "לאסוף/לערוך" },
  ],
  C1: [
    { word: "condescend", partOfSpeech: "verb", definition: "להתנשא, לדבר מגבוה", example: "Don't condescend to me.", translation: "להתנשא" },
    { word: "confound", partOfSpeech: "verb", definition: "לבלבל, או לסכל ציפיות", example: "The results confounded experts.", translation: "לבלבל/לסכל" },
    { word: "conscientious", partOfSpeech: "adjective", definition: "מצפוני, יסודי ואחראי", example: "A conscientious worker.", translation: "מצפוני/שקדן" },
    { word: "consensus", partOfSpeech: "noun", definition: "הסכמה רחבה", example: "We reached a consensus.", translation: "הסכמה רחבה/קונצנזוס" },
    { word: "contemplate", partOfSpeech: "verb", definition: "להרהר, לשקול ברצינות", example: "She contemplated leaving.", translation: "להרהר/לשקול" },
    { word: "contempt", partOfSpeech: "noun", definition: "בוז", example: "He showed contempt for the rules.", translation: "בוז" },
    { word: "credible", partOfSpeech: "adjective", definition: "אמין", example: "A credible witness.", translation: "אמין" },
    { word: "cumulative", partOfSpeech: "adjective", definition: "מצטבר", example: "The cumulative effect.", translation: "מצטבר" },
  ],
  C2: [
    { word: "cynicism", partOfSpeech: "noun", definition: "ציניות, חוסר אמון בכוונות אחרים", example: "A note of cynicism.", translation: "ציניות" },
    { word: "demise", partOfSpeech: "noun", definition: "קץ, מות או חדלון", example: "The demise of the empire.", translation: "קץ/חדלון" },
    { word: "disparage", partOfSpeech: "verb", definition: "לזלזל, להמעיט בערך", example: "He disparaged their efforts.", translation: "לזלזל/להמעיט" },
    { word: "dogma", partOfSpeech: "noun", definition: "דוגמה, עיקר אמונה נוקשה", example: "Political dogma.", translation: "דוגמה/עיקר אמונה" },
    { word: "duplicity", partOfSpeech: "noun", definition: "דו-פרצופיות, מרמה", example: "Accused of duplicity.", translation: "דו-פרצופיות/מרמה" },
    { word: "eloquence", partOfSpeech: "noun", definition: "רהיטות, יכולת ביטוי משכנעת", example: "She spoke with eloquence.", translation: "רהיטות" },
  ],
};
