import type { GemListening, GemReading, GemSpeaking, Level } from "../types";
import { LEVELS } from "../types";
import { pickRandom } from "./offline";

// Offline content for the "real use" pillars (Reading Lab, Listening, Speaking),
// generated by scripts/generate-content.mjs. Each level/type is a separate
// dynamic-import() chunk, loaded only when that pillar is opened — so none of it
// is in the initial bundle. `pickExtra` falls back to the nearest available
// level so the offline path never breaks.

type Loader<T> = () => Promise<T[]>;

const READING_LOADERS: Record<Level, Loader<GemReading>> = {
  A1: () => import("./offline/a1.reading.json").then((m) => m.default as GemReading[]),
  A2: () => import("./offline/a2.reading.json").then((m) => m.default as GemReading[]),
  B1: () => import("./offline/b1.reading.json").then((m) => m.default as GemReading[]),
  B2: () => import("./offline/b2.reading.json").then((m) => m.default as GemReading[]),
  C1: () => import("./offline/c1.reading.json").then((m) => m.default as GemReading[]),
  C2: () => import("./offline/c2.reading.json").then((m) => m.default as GemReading[]),
};

const LISTENING_LOADERS: Record<Level, Loader<GemListening>> = {
  A1: () => import("./offline/a1.listening.json").then((m) => m.default as GemListening[]),
  A2: () => import("./offline/a2.listening.json").then((m) => m.default as GemListening[]),
  B1: () => import("./offline/b1.listening.json").then((m) => m.default as GemListening[]),
  B2: () => import("./offline/b2.listening.json").then((m) => m.default as GemListening[]),
  C1: () => import("./offline/c1.listening.json").then((m) => m.default as GemListening[]),
  C2: () => import("./offline/c2.listening.json").then((m) => m.default as GemListening[]),
};

const SPEAKING_LOADERS: Record<Level, Loader<GemSpeaking>> = {
  A1: () => import("./offline/a1.speaking.json").then((m) => m.default as GemSpeaking[]),
  A2: () => import("./offline/a2.speaking.json").then((m) => m.default as GemSpeaking[]),
  B1: () => import("./offline/b1.speaking.json").then((m) => m.default as GemSpeaking[]),
  B2: () => import("./offline/b2.speaking.json").then((m) => m.default as GemSpeaking[]),
  C1: () => import("./offline/c1.speaking.json").then((m) => m.default as GemSpeaking[]),
  C2: () => import("./offline/c2.speaking.json").then((m) => m.default as GemSpeaking[]),
};

export const READINGS = READING_LOADERS;
export const LISTENINGS = LISTENING_LOADERS;
export const SPEAKINGS = SPEAKING_LOADERS;

// Load a random item for the given level, falling back to the nearest level that
// has content so the offline path always returns something.
export async function pickExtra<T>(
  loaders: Record<Level, Loader<T>>,
  level: Level,
): Promise<T> {
  for (const lvl of [level, ...LEVELS]) {
    const items = await loaders[lvl]();
    if (items && items.length) return pickRandom(items);
  }
  throw new Error("No offline content available for this feature.");
}
