import type { Level, OfflineLevelContent } from "../types";

// Bundled offline content per CEFR level — a full year of daily lessons, vocab
// and quizzes (generated by scripts/generate-content.mjs). Each level is a
// separate ~1 MB chunk loaded on demand via dynamic import(), so a learner only
// ever downloads their own level rather than all six up front.
const LOADERS: Record<Level, () => Promise<OfflineLevelContent>> = {
  A1: () => import("./offline/a1.json").then((m) => m.default as OfflineLevelContent),
  A2: () => import("./offline/a2.json").then((m) => m.default as OfflineLevelContent),
  B1: () => import("./offline/b1.json").then((m) => m.default as OfflineLevelContent),
  B2: () => import("./offline/b2.json").then((m) => m.default as OfflineLevelContent),
  C1: () => import("./offline/c1.json").then((m) => m.default as OfflineLevelContent),
  C2: () => import("./offline/c2.json").then((m) => m.default as OfflineLevelContent),
};

// Memoize so repeated calls for the same level don't re-import.
const cache = new Map<Level, Promise<OfflineLevelContent>>();

export function loadOfflineContent(level: Level): Promise<OfflineLevelContent> {
  if (!cache.has(level)) cache.set(level, LOADERS[level]());
  return cache.get(level)!;
}

export function pickRandom<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)];
}

export { pickByDay, dayIndex } from "../utils/daily";
