import type { Level, OfflineLevelContent } from "../types";
import { dayIndex, resolveQuarter } from "../utils/daily";

// Bundled offline content per CEFR level — a full year of daily lessons,
// vocab and quizzes (generated by scripts/generate-content.mjs), split into 4
// quarter files per level instead of one ~365-entry file. A learner only ever
// downloads their own level's *current quarter* (~90 days) via dynamic
// import(), not a full year up front.
const LOADERS: Record<Level, (quarter: 1 | 2 | 3 | 4) => Promise<OfflineLevelContent>> = {
  A1: (q) => import(`./offline/a1.q${q}.json`).then((m) => m.default as OfflineLevelContent),
  A2: (q) => import(`./offline/a2.q${q}.json`).then((m) => m.default as OfflineLevelContent),
  B1: (q) => import(`./offline/b1.q${q}.json`).then((m) => m.default as OfflineLevelContent),
  B2: (q) => import(`./offline/b2.q${q}.json`).then((m) => m.default as OfflineLevelContent),
  C1: (q) => import(`./offline/c1.q${q}.json`).then((m) => m.default as OfflineLevelContent),
  C2: (q) => import(`./offline/c2.q${q}.json`).then((m) => m.default as OfflineLevelContent),
};

// Memoize per (level, quarter) so repeated calls for the same quarter don't
// re-import — but switching quarters (a new season, or a caller asking for a
// different day) fetches only that quarter, not the whole year.
const cache = new Map<string, Promise<OfflineLevelContent>>();

export interface OfflineLoad {
  content: OfflineLevelContent;
  /** Index within `content`'s arrays for the requested day. */
  localDay: number;
}

export function loadOfflineContent(level: Level, day = dayIndex()): Promise<OfflineLoad> {
  const { quarter, localDay } = resolveQuarter(day);
  const key = `${level}-${quarter}`;
  if (!cache.has(key)) cache.set(key, LOADERS[level](quarter));
  return cache.get(key)!.then((content) => ({ content, localDay }));
}

export { pickByDay, dayIndex } from "../utils/daily";
